//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.16 at 11:47:04 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.projekat.org/korisnik_portal_poverenik", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package projectXML.team10.poverenik.models.korisnik;
