//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.09 at 03:55:47 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.projekat.org/zalba_na_odluku", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED, xmlns={@XmlNs(prefix="zno", namespaceURI="http://www.projekat.org/zalba_na_odluku"), @XmlNs(prefix="xs", namespaceURI="http://www.w3.org/2001/XMLSchema#"), @XmlNs(prefix="pred", namespaceURI="http://www.projekat.org/predicate/"), @XmlNs(prefix="common", namespaceURI = "http://www.projekat.org/common")})
package projectXML.team10.poverenik.models.zalbaNaOdluku;

import javax.xml.bind.annotation.XmlNs;