//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.10 at 07:08:56 PM CET 
//


package projectXML.team10.poverenik.models.zalbaNaOdluku;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;

import projectXML.team10.poverenik.models.common.TAdresa;
import projectXML.team10.poverenik.models.common.TFizickoLice;
import projectXML.team10.poverenik.models.common.TLice;


/**
 * &lt;p&gt;Java class for anonymous complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *       &amp;lt;sequence&amp;gt;
 *         &amp;lt;element name="adresa_poverenika" type="{http://www.projekat.org/common}TAdresa"/&amp;gt;
 *         &amp;lt;element name="zalilac" type="{http://www.projekat.org/common}TLice"/&amp;gt;
 *         &amp;lt;element name="podaci_o_resenju"&amp;gt;
 *           &amp;lt;complexType&amp;gt;
 *             &amp;lt;complexContent&amp;gt;
 *               &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *                 &amp;lt;sequence&amp;gt;
 *                   &amp;lt;element name="godina"&amp;gt;
 *                     &amp;lt;simpleType&amp;gt;
 *                       &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}positiveInteger"&amp;gt;
 *                         &amp;lt;totalDigits value="4"/&amp;gt;
 *                       &amp;lt;/restriction&amp;gt;
 *                     &amp;lt;/simpleType&amp;gt;
 *                   &amp;lt;/element&amp;gt;
 *                   &amp;lt;element name="naziv_organa"&amp;gt;
 *                     &amp;lt;complexType&amp;gt;
 *                       &amp;lt;simpleContent&amp;gt;
 *                         &amp;lt;extension base="&amp;lt;http://www.w3.org/2001/XMLSchema&amp;gt;string"&amp;gt;
 *                           &amp;lt;attribute name="property" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="pred:organ_koji_je_doneo_odluku" /&amp;gt;
 *                           &amp;lt;attribute name="datatype" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="xs:string" /&amp;gt;
 *                         &amp;lt;/extension&amp;gt;
 *                       &amp;lt;/simpleContent&amp;gt;
 *                     &amp;lt;/complexType&amp;gt;
 *                   &amp;lt;/element&amp;gt;
 *                 &amp;lt;/sequence&amp;gt;
 *               &amp;lt;/restriction&amp;gt;
 *             &amp;lt;/complexContent&amp;gt;
 *           &amp;lt;/complexType&amp;gt;
 *         &amp;lt;/element&amp;gt;
 *         &amp;lt;element name="datum_zahteva" type="{http://www.w3.org/2001/XMLSchema}date"/&amp;gt;
 *         &amp;lt;element name="podaci_o_zalbi"&amp;gt;
 *           &amp;lt;complexType&amp;gt;
 *             &amp;lt;complexContent&amp;gt;
 *               &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *                 &amp;lt;sequence&amp;gt;
 *                   &amp;lt;element name="podnosilac_zalbe"&amp;gt;
 *                     &amp;lt;complexType&amp;gt;
 *                       &amp;lt;complexContent&amp;gt;
 *                         &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *                           &amp;lt;sequence&amp;gt;
 *                             &amp;lt;element name="lice" type="{http://www.projekat.org/common}TFizicko_lice"/&amp;gt;
 *                             &amp;lt;element name="drugi_podaci_za_kontakt"&amp;gt;
 *                               &amp;lt;simpleType&amp;gt;
 *                                 &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt;
 *                                   &amp;lt;minLength value="1"/&amp;gt;
 *                                 &amp;lt;/restriction&amp;gt;
 *                               &amp;lt;/simpleType&amp;gt;
 *                             &amp;lt;/element&amp;gt;
 *                           &amp;lt;/sequence&amp;gt;
 *                           &amp;lt;attribute name="property" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="pred:podnosilac_zalbe" /&amp;gt;
 *                           &amp;lt;attribute name="id_podnosioca" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&amp;gt;
 *                           &amp;lt;attribute name="resource" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&amp;gt;
 *                         &amp;lt;/restriction&amp;gt;
 *                       &amp;lt;/complexContent&amp;gt;
 *                     &amp;lt;/complexType&amp;gt;
 *                   &amp;lt;/element&amp;gt;
 *                   &amp;lt;element name="datum_podnosenja"&amp;gt;
 *                     &amp;lt;complexType&amp;gt;
 *                       &amp;lt;simpleContent&amp;gt;
 *                         &amp;lt;extension base="&amp;lt;http://www.w3.org/2001/XMLSchema&amp;gt;date"&amp;gt;
 *                           &amp;lt;attribute name="property" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="pred:datum_podnosenja" /&amp;gt;
 *                           &amp;lt;attribute name="datatype" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="xs:date" /&amp;gt;
 *                         &amp;lt;/extension&amp;gt;
 *                       &amp;lt;/simpleContent&amp;gt;
 *                     &amp;lt;/complexType&amp;gt;
 *                   &amp;lt;/element&amp;gt;
 *                   &amp;lt;element name="mesto"&amp;gt;
 *                     &amp;lt;complexType&amp;gt;
 *                       &amp;lt;simpleContent&amp;gt;
 *                         &amp;lt;extension base="&amp;lt;http://www.w3.org/2001/XMLSchema&amp;gt;string"&amp;gt;
 *                           &amp;lt;attribute name="property" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="pred:mesto_podnosenja" /&amp;gt;
 *                           &amp;lt;attribute name="datatype" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="xs:string" /&amp;gt;
 *                         &amp;lt;/extension&amp;gt;
 *                       &amp;lt;/simpleContent&amp;gt;
 *                     &amp;lt;/complexType&amp;gt;
 *                   &amp;lt;/element&amp;gt;
 *                   &amp;lt;element name="opis"&amp;gt;
 *                     &amp;lt;simpleType&amp;gt;
 *                       &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt;
 *                         &amp;lt;minLength value="1"/&amp;gt;
 *                       &amp;lt;/restriction&amp;gt;
 *                     &amp;lt;/simpleType&amp;gt;
 *                   &amp;lt;/element&amp;gt;
 *                 &amp;lt;/sequence&amp;gt;
 *               &amp;lt;/restriction&amp;gt;
 *             &amp;lt;/complexContent&amp;gt;
 *           &amp;lt;/complexType&amp;gt;
 *         &amp;lt;/element&amp;gt;
 *       &amp;lt;/sequence&amp;gt;
 *       &amp;lt;attribute name="broj_zalbe"&amp;gt;
 *         &amp;lt;simpleType&amp;gt;
 *           &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt;
 *             &amp;lt;minLength value="1"/&amp;gt;
 *           &amp;lt;/restriction&amp;gt;
 *         &amp;lt;/simpleType&amp;gt;
 *       &amp;lt;/attribute&amp;gt;
 *       &amp;lt;attribute name="broj_zahteva" use="required"&amp;gt;
 *         &amp;lt;simpleType&amp;gt;
 *           &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt;
 *             &amp;lt;minLength value="1"/&amp;gt;
 *           &amp;lt;/restriction&amp;gt;
 *         &amp;lt;/simpleType&amp;gt;
 *       &amp;lt;/attribute&amp;gt;
 *       &amp;lt;attribute name="broj_resenja" use="required"&amp;gt;
 *         &amp;lt;simpleType&amp;gt;
 *           &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt;
 *             &amp;lt;minLength value="1"/&amp;gt;
 *           &amp;lt;/restriction&amp;gt;
 *         &amp;lt;/simpleType&amp;gt;
 *       &amp;lt;/attribute&amp;gt;
 *       &amp;lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" /&amp;gt;
 *       &amp;lt;attribute name="vocab" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="http://www.projekat.org/predicate" /&amp;gt;
 *       &amp;lt;attribute name="about" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&amp;gt;
 *     &amp;lt;/restriction&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "adresaPoverenika",
    "zalilac",
    "podaciOResenju",
    "datumZahteva",
    "podaciOZalbi"
})
@XmlRootElement(name = "zalba_na_odluku", namespace = "http://www.projekat.org/zalba_na_odluku")
public class ZalbaNaOdluku {

    @XmlElement(name = "adresa_poverenika", namespace = "http://www.projekat.org/zalba_na_odluku", required = true)
    protected TAdresa adresaPoverenika;
    @XmlElement(namespace = "http://www.projekat.org/zalba_na_odluku", required = true)
    protected TLice zalilac;
    @XmlElement(name = "podaci_o_resenju", namespace = "http://www.projekat.org/zalba_na_odluku", required = true)
    protected ZalbaNaOdluku.PodaciOResenju podaciOResenju;
    @XmlElement(name = "datum_zahteva", namespace = "http://www.projekat.org/zalba_na_odluku", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumZahteva;
    @XmlElement(name = "podaci_o_zalbi", namespace = "http://www.projekat.org/zalba_na_odluku", required = true)
    protected ZalbaNaOdluku.PodaciOZalbi podaciOZalbi;
    @XmlAttribute(name = "broj_zalbe")
    protected String brojZalbe;
    @XmlAttribute(name = "broj_zahteva", required = true)
    protected String brojZahteva;
    @XmlAttribute(name = "broj_resenja", required = true)
    protected String brojResenja;
    @XmlAttribute(name = "id")
    protected String id;
    @XmlAttribute(name = "vocab", required = false)
    protected String vocab;
    @XmlAttribute(name = "about", required = false)
    protected String about;
    @XmlAttribute(name = "property", required = false)
	protected String property;
	@XmlAttribute(name = "content", required = false)
	protected String content;

    /**
     * Gets the value of the adresaPoverenika property.
     * 
     * @return
     *     possible object is
     *     {@link TAdresa }
     *     
     */
    public TAdresa getAdresaPoverenika() {
        return adresaPoverenika;
    }

    /**
     * Sets the value of the adresaPoverenika property.
     * 
     * @param value
     *     allowed object is
     *     {@link TAdresa }
     *     
     */
    public void setAdresaPoverenika(TAdresa value) {
        this.adresaPoverenika = value;
    }

    /**
     * Gets the value of the zalilac property.
     * 
     * @return
     *     possible object is
     *     {@link TLice }
     *     
     */
    public TLice getZalilac() {
        return zalilac;
    }

    /**
     * Sets the value of the zalilac property.
     * 
     * @param value
     *     allowed object is
     *     {@link TLice }
     *     
     */
    public void setZalilac(TLice value) {
        this.zalilac = value;
    }

    /**
     * Gets the value of the podaciOResenju property.
     * 
     * @return
     *     possible object is
     *     {@link ZalbaNaOdluku.PodaciOResenju }
     *     
     */
    public ZalbaNaOdluku.PodaciOResenju getPodaciOResenju() {
        return podaciOResenju;
    }

    /**
     * Sets the value of the podaciOResenju property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZalbaNaOdluku.PodaciOResenju }
     *     
     */
    public void setPodaciOResenju(ZalbaNaOdluku.PodaciOResenju value) {
        this.podaciOResenju = value;
    }

    /**
     * Gets the value of the datumZahteva property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumZahteva() {
        return datumZahteva;
    }

    /**
     * Sets the value of the datumZahteva property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumZahteva(XMLGregorianCalendar value) {
        this.datumZahteva = value;
    }

    /**
     * Gets the value of the podaciOZalbi property.
     * 
     * @return
     *     possible object is
     *     {@link ZalbaNaOdluku.PodaciOZalbi }
     *     
     */
    public ZalbaNaOdluku.PodaciOZalbi getPodaciOZalbi() {
        return podaciOZalbi;
    }

    /**
     * Sets the value of the podaciOZalbi property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZalbaNaOdluku.PodaciOZalbi }
     *     
     */
    public void setPodaciOZalbi(ZalbaNaOdluku.PodaciOZalbi value) {
        this.podaciOZalbi = value;
    }

    /**
     * Gets the value of the brojZalbe property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrojZalbe() {
        return brojZalbe;
    }

    /**
     * Sets the value of the brojZalbe property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrojZalbe(String value) {
        this.brojZalbe = value;
    }

    /**
     * Gets the value of the brojZahteva property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrojZahteva() {
        return brojZahteva;
    }

    /**
     * Sets the value of the brojZahteva property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrojZahteva(String value) {
        this.brojZahteva = value;
    }

    /**
     * Gets the value of the brojResenja property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrojResenja() {
        return brojResenja;
    }

    /**
     * Sets the value of the brojResenja property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrojResenja(String value) {
        this.brojResenja = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the vocab property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVocab() {
        if (vocab == null) {
            return "http://www.projekat.org/predicate";
        } else {
            return vocab;
        }
    }

    /**
     * Sets the value of the vocab property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVocab() {
        this.vocab = "http://www.projekat.org/predicate";
    }

    /**
     * Gets the value of the about property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAbout() {
        return about;
    }

    /**
     * Sets the value of the about property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAbout(String value) {
        this.about = value;
    }

    public String getProperty() {
		if (property == null) {
			return "pred:zahtev_na_koji_se_odnosi_zalba";
		} else {
			return property;
		}
	}

	/**
	 * Sets the value of the property property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setProperty() {
		this.property = "pred:zahtev_na_koji_se_odnosi_zalba";
	}

	/**
	 * Gets the value of the datatype property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getContent() {
		return content;
	}

	/**
	 * Sets the value of the datatype property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setContent(String value) {
		this.content = value;
	}
    /**
     * &lt;p&gt;Java class for anonymous complex type.
     * 
     * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
     * 
     * &lt;pre&gt;
     * &amp;lt;complexType&amp;gt;
     *   &amp;lt;complexContent&amp;gt;
     *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
     *       &amp;lt;sequence&amp;gt;
     *         &amp;lt;element name="godina"&amp;gt;
     *           &amp;lt;simpleType&amp;gt;
     *             &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}positiveInteger"&amp;gt;
     *               &amp;lt;totalDigits value="4"/&amp;gt;
     *             &amp;lt;/restriction&amp;gt;
     *           &amp;lt;/simpleType&amp;gt;
     *         &amp;lt;/element&amp;gt;
     *         &amp;lt;element name="naziv_organa"&amp;gt;
     *           &amp;lt;complexType&amp;gt;
     *             &amp;lt;simpleContent&amp;gt;
     *               &amp;lt;extension base="&amp;lt;http://www.w3.org/2001/XMLSchema&amp;gt;string"&amp;gt;
     *                 &amp;lt;attribute name="property" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="pred:organ_koji_je_doneo_odluku" /&amp;gt;
     *                 &amp;lt;attribute name="datatype" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="xs:string" /&amp;gt;
     *               &amp;lt;/extension&amp;gt;
     *             &amp;lt;/simpleContent&amp;gt;
     *           &amp;lt;/complexType&amp;gt;
     *         &amp;lt;/element&amp;gt;
     *       &amp;lt;/sequence&amp;gt;
     *     &amp;lt;/restriction&amp;gt;
     *   &amp;lt;/complexContent&amp;gt;
     * &amp;lt;/complexType&amp;gt;
     * &lt;/pre&gt;
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "godina",
        "nazivOrgana"
    })
    public static class PodaciOResenju {

        @XmlElement(namespace = "http://www.projekat.org/zalba_na_odluku", required = true)
        protected BigInteger godina;
        @XmlElement(name = "naziv_organa", namespace = "http://www.projekat.org/zalba_na_odluku", required = true)
        protected ZalbaNaOdluku.PodaciOResenju.NazivOrgana nazivOrgana;

        /**
         * Gets the value of the godina property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getGodina() {
            return godina;
        }

        /**
         * Sets the value of the godina property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setGodina(BigInteger value) {
            this.godina = value;
        }

        /**
         * Gets the value of the nazivOrgana property.
         * 
         * @return
         *     possible object is
         *     {@link ZalbaNaOdluku.PodaciOResenju.NazivOrgana }
         *     
         */
        public ZalbaNaOdluku.PodaciOResenju.NazivOrgana getNazivOrgana() {
            return nazivOrgana;
        }

        /**
         * Sets the value of the nazivOrgana property.
         * 
         * @param value
         *     allowed object is
         *     {@link ZalbaNaOdluku.PodaciOResenju.NazivOrgana }
         *     
         */
        public void setNazivOrgana(ZalbaNaOdluku.PodaciOResenju.NazivOrgana value) {
            this.nazivOrgana = value;
        }


        /**
         * &lt;p&gt;Java class for anonymous complex type.
         * 
         * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
         * 
         * &lt;pre&gt;
         * &amp;lt;complexType&amp;gt;
         *   &amp;lt;simpleContent&amp;gt;
         *     &amp;lt;extension base="&amp;lt;http://www.w3.org/2001/XMLSchema&amp;gt;string"&amp;gt;
         *       &amp;lt;attribute name="property" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="pred:organ_koji_je_doneo_odluku" /&amp;gt;
         *       &amp;lt;attribute name="datatype" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="xs:string" /&amp;gt;
         *     &amp;lt;/extension&amp;gt;
         *   &amp;lt;/simpleContent&amp;gt;
         * &amp;lt;/complexType&amp;gt;
         * &lt;/pre&gt;
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class NazivOrgana {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "property", required = false)
            protected String property;
            @XmlAttribute(name = "datatype", required = false)
            protected String datatype;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the property property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getProperty() {
                if (property == null) {
                    return "pred:organ_koji_je_doneo_odluku";
                } else {
                    return property;
                }
            }

            /**
             * Sets the value of the property property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setProperty() {
                this.property = "pred:organ_koji_je_doneo_odluku";
            }

            /**
             * Gets the value of the datatype property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDatatype() {
                if (datatype == null) {
                    return "xs:string";
                } else {
                    return datatype;
                }
            }

            /**
             * Sets the value of the datatype property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDatatype() {
                this.datatype = "xs:string";
            }

        }

    }


    /**
     * &lt;p&gt;Java class for anonymous complex type.
     * 
     * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
     * 
     * &lt;pre&gt;
     * &amp;lt;complexType&amp;gt;
     *   &amp;lt;complexContent&amp;gt;
     *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
     *       &amp;lt;sequence&amp;gt;
     *         &amp;lt;element name="podnosilac_zalbe"&amp;gt;
     *           &amp;lt;complexType&amp;gt;
     *             &amp;lt;complexContent&amp;gt;
     *               &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
     *                 &amp;lt;sequence&amp;gt;
     *                   &amp;lt;element name="lice" type="{http://www.projekat.org/common}TFizicko_lice"/&amp;gt;
     *                   &amp;lt;element name="drugi_podaci_za_kontakt"&amp;gt;
     *                     &amp;lt;simpleType&amp;gt;
     *                       &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt;
     *                         &amp;lt;minLength value="1"/&amp;gt;
     *                       &amp;lt;/restriction&amp;gt;
     *                     &amp;lt;/simpleType&amp;gt;
     *                   &amp;lt;/element&amp;gt;
     *                 &amp;lt;/sequence&amp;gt;
     *                 &amp;lt;attribute name="property" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="pred:podnosilac_zalbe" /&amp;gt;
     *                 &amp;lt;attribute name="id_podnosioca" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&amp;gt;
     *                 &amp;lt;attribute name="resource" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&amp;gt;
     *               &amp;lt;/restriction&amp;gt;
     *             &amp;lt;/complexContent&amp;gt;
     *           &amp;lt;/complexType&amp;gt;
     *         &amp;lt;/element&amp;gt;
     *         &amp;lt;element name="datum_podnosenja"&amp;gt;
     *           &amp;lt;complexType&amp;gt;
     *             &amp;lt;simpleContent&amp;gt;
     *               &amp;lt;extension base="&amp;lt;http://www.w3.org/2001/XMLSchema&amp;gt;date"&amp;gt;
     *                 &amp;lt;attribute name="property" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="pred:datum_podnosenja" /&amp;gt;
     *                 &amp;lt;attribute name="datatype" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="xs:date" /&amp;gt;
     *               &amp;lt;/extension&amp;gt;
     *             &amp;lt;/simpleContent&amp;gt;
     *           &amp;lt;/complexType&amp;gt;
     *         &amp;lt;/element&amp;gt;
     *         &amp;lt;element name="mesto"&amp;gt;
     *           &amp;lt;complexType&amp;gt;
     *             &amp;lt;simpleContent&amp;gt;
     *               &amp;lt;extension base="&amp;lt;http://www.w3.org/2001/XMLSchema&amp;gt;string"&amp;gt;
     *                 &amp;lt;attribute name="property" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="pred:mesto_podnosenja" /&amp;gt;
     *                 &amp;lt;attribute name="datatype" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="xs:string" /&amp;gt;
     *               &amp;lt;/extension&amp;gt;
     *             &amp;lt;/simpleContent&amp;gt;
     *           &amp;lt;/complexType&amp;gt;
     *         &amp;lt;/element&amp;gt;
     *         &amp;lt;element name="opis"&amp;gt;
     *           &amp;lt;simpleType&amp;gt;
     *             &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt;
     *               &amp;lt;minLength value="1"/&amp;gt;
     *             &amp;lt;/restriction&amp;gt;
     *           &amp;lt;/simpleType&amp;gt;
     *         &amp;lt;/element&amp;gt;
     *       &amp;lt;/sequence&amp;gt;
     *     &amp;lt;/restriction&amp;gt;
     *   &amp;lt;/complexContent&amp;gt;
     * &amp;lt;/complexType&amp;gt;
     * &lt;/pre&gt;
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "podnosilacZalbe",
        "datumPodnosenja",
        "mesto",
        "opis"
    })
    public static class PodaciOZalbi {

        @XmlElement(name = "podnosilac_zalbe", namespace = "http://www.projekat.org/zalba_na_odluku", required = true)
        protected ZalbaNaOdluku.PodaciOZalbi.PodnosilacZalbe podnosilacZalbe;
        @XmlElement(name = "datum_podnosenja", namespace = "http://www.projekat.org/zalba_na_odluku", required = true)
        protected ZalbaNaOdluku.PodaciOZalbi.DatumPodnosenja datumPodnosenja;
        @XmlElement(namespace = "http://www.projekat.org/zalba_na_odluku", required = true)
        protected ZalbaNaOdluku.PodaciOZalbi.Mesto mesto;
        @XmlElement(namespace = "http://www.projekat.org/zalba_na_odluku", required = true)
        protected String opis;

        /**
         * Gets the value of the podnosilacZalbe property.
         * 
         * @return
         *     possible object is
         *     {@link ZalbaNaOdluku.PodaciOZalbi.PodnosilacZalbe }
         *     
         */
        public ZalbaNaOdluku.PodaciOZalbi.PodnosilacZalbe getPodnosilacZalbe() {
            return podnosilacZalbe;
        }

        /**
         * Sets the value of the podnosilacZalbe property.
         * 
         * @param value
         *     allowed object is
         *     {@link ZalbaNaOdluku.PodaciOZalbi.PodnosilacZalbe }
         *     
         */
        public void setPodnosilacZalbe(ZalbaNaOdluku.PodaciOZalbi.PodnosilacZalbe value) {
            this.podnosilacZalbe = value;
        }

        /**
         * Gets the value of the datumPodnosenja property.
         * 
         * @return
         *     possible object is
         *     {@link ZalbaNaOdluku.PodaciOZalbi.DatumPodnosenja }
         *     
         */
        public ZalbaNaOdluku.PodaciOZalbi.DatumPodnosenja getDatumPodnosenja() {
            return datumPodnosenja;
        }

        /**
         * Sets the value of the datumPodnosenja property.
         * 
         * @param value
         *     allowed object is
         *     {@link ZalbaNaOdluku.PodaciOZalbi.DatumPodnosenja }
         *     
         */
        public void setDatumPodnosenja(ZalbaNaOdluku.PodaciOZalbi.DatumPodnosenja value) {
            this.datumPodnosenja = value;
        }

        /**
         * Gets the value of the mesto property.
         * 
         * @return
         *     possible object is
         *     {@link ZalbaNaOdluku.PodaciOZalbi.Mesto }
         *     
         */
        public ZalbaNaOdluku.PodaciOZalbi.Mesto getMesto() {
            return mesto;
        }

        /**
         * Sets the value of the mesto property.
         * 
         * @param value
         *     allowed object is
         *     {@link ZalbaNaOdluku.PodaciOZalbi.Mesto }
         *     
         */
        public void setMesto(ZalbaNaOdluku.PodaciOZalbi.Mesto value) {
            this.mesto = value;
        }

        /**
         * Gets the value of the opis property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOpis() {
            return opis;
        }

        /**
         * Sets the value of the opis property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOpis(String value) {
            this.opis = value;
        }


        /**
         * &lt;p&gt;Java class for anonymous complex type.
         * 
         * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
         * 
         * &lt;pre&gt;
         * &amp;lt;complexType&amp;gt;
         *   &amp;lt;simpleContent&amp;gt;
         *     &amp;lt;extension base="&amp;lt;http://www.w3.org/2001/XMLSchema&amp;gt;date"&amp;gt;
         *       &amp;lt;attribute name="property" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="pred:datum_podnosenja" /&amp;gt;
         *       &amp;lt;attribute name="datatype" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="xs:date" /&amp;gt;
         *     &amp;lt;/extension&amp;gt;
         *   &amp;lt;/simpleContent&amp;gt;
         * &amp;lt;/complexType&amp;gt;
         * &lt;/pre&gt;
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class DatumPodnosenja {

            @XmlValue
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar value;
            @XmlAttribute(name = "property", required = false)
            protected String property;
            @XmlAttribute(name = "datatype", required = false)
            protected String datatype;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setValue(XMLGregorianCalendar value) {
                this.value = value;
            }

            /**
             * Gets the value of the property property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getProperty() {
                if (property == null) {
                    return "pred:datum_podnosenja";
                } else {
                    return property;
                }
            }

            /**
             * Sets the value of the property property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setProperty() {
                this.property = "pred:datum_podnosenja";
            }

            /**
             * Gets the value of the datatype property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDatatype() {
                if (datatype == null) {
                    return "xs:date";
                } else {
                    return datatype;
                }
            }

            /**
             * Sets the value of the datatype property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDatatype() {
                this.datatype = "xs:date";
            }

        }


        /**
         * &lt;p&gt;Java class for anonymous complex type.
         * 
         * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
         * 
         * &lt;pre&gt;
         * &amp;lt;complexType&amp;gt;
         *   &amp;lt;simpleContent&amp;gt;
         *     &amp;lt;extension base="&amp;lt;http://www.w3.org/2001/XMLSchema&amp;gt;string"&amp;gt;
         *       &amp;lt;attribute name="property" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="pred:mesto_podnosenja" /&amp;gt;
         *       &amp;lt;attribute name="datatype" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="xs:string" /&amp;gt;
         *     &amp;lt;/extension&amp;gt;
         *   &amp;lt;/simpleContent&amp;gt;
         * &amp;lt;/complexType&amp;gt;
         * &lt;/pre&gt;
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Mesto {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "property", required = false)
            protected String property;
            @XmlAttribute(name = "datatype", required = false)
            protected String datatype;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the property property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getProperty() {
                if (property == null) {
                    return "pred:mesto_podnosenja";
                } else {
                    return property;
                }
            }

            /**
             * Sets the value of the property property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setProperty() {
                this.property = "pred:mesto_podnosenja";
            }

            /**
             * Gets the value of the datatype property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDatatype() {
                if (datatype == null) {
                    return "xs:string";
                } else {
                    return datatype;
                }
            }

            /**
             * Sets the value of the datatype property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDatatype() {
                this.datatype = "xs:string";
            }

        }


        /**
         * &lt;p&gt;Java class for anonymous complex type.
         * 
         * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
         * 
         * &lt;pre&gt;
         * &amp;lt;complexType&amp;gt;
         *   &amp;lt;complexContent&amp;gt;
         *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
         *       &amp;lt;sequence&amp;gt;
         *         &amp;lt;element name="lice" type="{http://www.projekat.org/common}TFizicko_lice"/&amp;gt;
         *         &amp;lt;element name="drugi_podaci_za_kontakt"&amp;gt;
         *           &amp;lt;simpleType&amp;gt;
         *             &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt;
         *               &amp;lt;minLength value="1"/&amp;gt;
         *             &amp;lt;/restriction&amp;gt;
         *           &amp;lt;/simpleType&amp;gt;
         *         &amp;lt;/element&amp;gt;
         *       &amp;lt;/sequence&amp;gt;
         *       &amp;lt;attribute name="property" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="pred:podnosilac_zalbe" /&amp;gt;
         *       &amp;lt;attribute name="id_podnosioca" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&amp;gt;
         *       &amp;lt;attribute name="resource" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&amp;gt;
         *     &amp;lt;/restriction&amp;gt;
         *   &amp;lt;/complexContent&amp;gt;
         * &amp;lt;/complexType&amp;gt;
         * &lt;/pre&gt;
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "lice",
            "drugiPodaciZaKontakt"
        })
        public static class PodnosilacZalbe {

            @XmlElement(namespace = "http://www.projekat.org/zalba_na_odluku", required = true)
            protected TLice lice;
            @XmlElement(name = "drugi_podaci_za_kontakt", namespace = "http://www.projekat.org/zalba_na_odluku", required = true)
            protected String drugiPodaciZaKontakt;
            @XmlAttribute(name = "property", required = false)
            protected String property;
            @XmlAttribute(name = "content", required = false)
            protected String content;

            /**
             * Gets the value of the lice property.
             * 
             * @return
             *     possible object is
             *     {@link TFizickoLice }
             *     
             */
            public TLice getLice() {
                return lice;
            }

            /**
             * Sets the value of the lice property.
             * 
             * @param value
             *     allowed object is
             *     {@link TFizickoLice }
             *     
             */
            public void setLice(TLice value) {
                this.lice = value;
            }

            /**
             * Gets the value of the drugiPodaciZaKontakt property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDrugiPodaciZaKontakt() {
                return drugiPodaciZaKontakt;
            }

            /**
             * Sets the value of the drugiPodaciZaKontakt property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDrugiPodaciZaKontakt(String value) {
                this.drugiPodaciZaKontakt = value;
            }

            /**
             * Gets the value of the property property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getProperty() {
                if (property == null) {
                    return "pred:podnosilac_zalbe";
                } else {
                    return property;
                }
            }

            /**
             * Sets the value of the property property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setProperty() {
                this.property = "pred:podnosilac_zalbe";
            }

            /**
             * Gets the value of the resource property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getContent() {
                return content;
            }

            /**
             * Sets the value of the resource property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setContent(String value) {
                this.content = value;
            }

        }

    }

}
