//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.05 at 03:34:09 PM CET 
//


package projectXML.team9.models.obavestenje;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the projectXML.team9.models.obavestenjeNovo package. 
 * &lt;p&gt;An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: projectXML.team9.models.obavestenjeNovo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Obavestenje }
     * 
     */
    public Obavestenje createObavestenje() {
        return new Obavestenje();
    }

    /**
     * Create an instance of {@link Obavestenje.OdgovorNaZahtev }
     * 
     */
    public Obavestenje.OdgovorNaZahtev createObavestenjeOdgovorNaZahtev() {
        return new Obavestenje.OdgovorNaZahtev();
    }

    /**
     * Create an instance of {@link Obavestenje.OdgovorNaZahtev.Zahtevi }
     * 
     */
    public Obavestenje.OdgovorNaZahtev.Zahtevi createObavestenjeOdgovorNaZahtevZahtevi() {
        return new Obavestenje.OdgovorNaZahtev.Zahtevi();
    }

    /**
     * Create an instance of {@link Obavestenje.OdgovorNaZahtev.Zahtevi.InformacijeOUvidu }
     * 
     */
    public Obavestenje.OdgovorNaZahtev.Zahtevi.InformacijeOUvidu createObavestenjeOdgovorNaZahtevZahteviInformacijeOUvidu() {
        return new Obavestenje.OdgovorNaZahtev.Zahtevi.InformacijeOUvidu();
    }

    /**
     * Create an instance of {@link Obavestenje.OdgovorNaZahtev.Zahtevi.InformacijeOUvidu.VremeUvida }
     * 
     */
    public Obavestenje.OdgovorNaZahtev.Zahtevi.InformacijeOUvidu.VremeUvida createObavestenjeOdgovorNaZahtevZahteviInformacijeOUviduVremeUvida() {
        return new Obavestenje.OdgovorNaZahtev.Zahtevi.InformacijeOUvidu.VremeUvida();
    }

    /**
     * Create an instance of {@link Obavestenje.OdgovorNaZahtev.UplataTroskova }
     * 
     */
    public Obavestenje.OdgovorNaZahtev.UplataTroskova createObavestenjeOdgovorNaZahtevUplataTroskova() {
        return new Obavestenje.OdgovorNaZahtev.UplataTroskova();
    }

    /**
     * Create an instance of {@link Obavestenje.OdgovorNaZahtev.UplataTroskova.Troskovi }
     * 
     */
    public Obavestenje.OdgovorNaZahtev.UplataTroskova.Troskovi createObavestenjeOdgovorNaZahtevUplataTroskovaTroskovi() {
        return new Obavestenje.OdgovorNaZahtev.UplataTroskova.Troskovi();
    }

    /**
     * Create an instance of {@link Obavestenje.InformacijeOObavestenju }
     * 
     */
    public Obavestenje.InformacijeOObavestenju createObavestenjeInformacijeOObavestenju() {
        return new Obavestenje.InformacijeOObavestenju();
    }

    /**
     * Create an instance of {@link Obavestenje.Zahtev }
     * 
     */
    public Obavestenje.Zahtev createObavestenjeZahtev() {
        return new Obavestenje.Zahtev();
    }

    /**
     * Create an instance of {@link Obavestenje.Dostavljeno }
     * 
     */
    public Obavestenje.Dostavljeno createObavestenjeDostavljeno() {
        return new Obavestenje.Dostavljeno();
    }

    /**
     * Create an instance of {@link TAdresa }
     * 
     */
    public TAdresa createTAdresa() {
        return new TAdresa();
    }

    /**
     * Create an instance of {@link TPravnoLice }
     * 
     */
    public TPravnoLice createTPravnoLice() {
        return new TPravnoLice();
    }

    /**
     * Create an instance of {@link TFizickoLice }
     * 
     */
    public TFizickoLice createTFizickoLice() {
        return new TFizickoLice();
    }

    /**
     * Create an instance of {@link TUplatnica }
     * 
     */
    public TUplatnica createTUplatnica() {
        return new TUplatnica();
    }

    /**
     * Create an instance of {@link Obavestenje.OdgovorNaZahtev.Zahtevi.InformacijeOPosedovanju }
     * 
     */
    public Obavestenje.OdgovorNaZahtev.Zahtevi.InformacijeOPosedovanju createObavestenjeOdgovorNaZahtevZahteviInformacijeOPosedovanju() {
        return new Obavestenje.OdgovorNaZahtev.Zahtevi.InformacijeOPosedovanju();
    }

    /**
     * Create an instance of {@link Obavestenje.OdgovorNaZahtev.Zahtevi.InformacijeOIzradiKopije }
     * 
     */
    public Obavestenje.OdgovorNaZahtev.Zahtevi.InformacijeOIzradiKopije createObavestenjeOdgovorNaZahtevZahteviInformacijeOIzradiKopije() {
        return new Obavestenje.OdgovorNaZahtev.Zahtevi.InformacijeOIzradiKopije();
    }

    /**
     * Create an instance of {@link Obavestenje.OdgovorNaZahtev.Zahtevi.InformacijeODostavljanjuDokumenta }
     * 
     */
    public Obavestenje.OdgovorNaZahtev.Zahtevi.InformacijeODostavljanjuDokumenta createObavestenjeOdgovorNaZahtevZahteviInformacijeODostavljanjuDokumenta() {
        return new Obavestenje.OdgovorNaZahtev.Zahtevi.InformacijeODostavljanjuDokumenta();
    }

    /**
     * Create an instance of {@link Obavestenje.OdgovorNaZahtev.Zahtevi.InformacijeOUvidu.MestoUvida }
     * 
     */
    public Obavestenje.OdgovorNaZahtev.Zahtevi.InformacijeOUvidu.MestoUvida createObavestenjeOdgovorNaZahtevZahteviInformacijeOUviduMestoUvida() {
        return new Obavestenje.OdgovorNaZahtev.Zahtevi.InformacijeOUvidu.MestoUvida();
    }

    /**
     * Create an instance of {@link Obavestenje.OdgovorNaZahtev.Zahtevi.InformacijeOUvidu.VremeUvida.IntervalUvida }
     * 
     */
    public Obavestenje.OdgovorNaZahtev.Zahtevi.InformacijeOUvidu.VremeUvida.IntervalUvida createObavestenjeOdgovorNaZahtevZahteviInformacijeOUviduVremeUvidaIntervalUvida() {
        return new Obavestenje.OdgovorNaZahtev.Zahtevi.InformacijeOUvidu.VremeUvida.IntervalUvida();
    }

    /**
     * Create an instance of {@link Obavestenje.OdgovorNaZahtev.UplataTroskova.Troskovi.Trosak }
     * 
     */
    public Obavestenje.OdgovorNaZahtev.UplataTroskova.Troskovi.Trosak createObavestenjeOdgovorNaZahtevUplataTroskovaTroskoviTrosak() {
        return new Obavestenje.OdgovorNaZahtev.UplataTroskova.Troskovi.Trosak();
    }

}
