//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.08 at 02:59:50 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.projekat.org/zalba_cutanja", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED, xmlns={@XmlNs(prefix="zc", namespaceURI="http://www.projekat.org/zalba_cutanja"), @XmlNs(prefix="common", namespaceURI = "http://www.projekat.org/common")})
package projectXML.team10.poverenik.models.zalbaCutanje;

import javax.xml.bind.annotation.XmlNs;
