//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.08 at 02:59:50 PM CET 
//


package projectXML.team10.poverenik.models.zalbaCutanje;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import projectXML.team10.poverenik.models.common.TAdresa;
import projectXML.team10.poverenik.models.common.TLice;
import projectXML.team10.poverenik.models.common.TPravnoLice;


/**
 * &lt;p&gt;Java class for anonymous complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *       &amp;lt;sequence&amp;gt;
 *         &amp;lt;element name="adresa_poverenika" type="{http://www.projekat.org/common}TAdresa"/&amp;gt;
 *         &amp;lt;element name="organ_protiv_kojeg_je_zalba" type="{http://www.projekat.org/common}TPravno_lice"/&amp;gt;
 *         &amp;lt;element name="podaci_o_zahtevu"&amp;gt;
 *           &amp;lt;complexType&amp;gt;
 *             &amp;lt;complexContent&amp;gt;
 *               &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *                 &amp;lt;sequence&amp;gt;
 *                   &amp;lt;element name="informacije"&amp;gt;
 *                     &amp;lt;simpleType&amp;gt;
 *                       &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt;
 *                         &amp;lt;minLength value="1"/&amp;gt;
 *                       &amp;lt;/restriction&amp;gt;
 *                     &amp;lt;/simpleType&amp;gt;
 *                   &amp;lt;/element&amp;gt;
 *                   &amp;lt;element name="datum" type="{http://www.w3.org/2001/XMLSchema}date"/&amp;gt;
 *                   &amp;lt;element name="zahtevi"&amp;gt;
 *                     &amp;lt;complexType&amp;gt;
 *                       &amp;lt;complexContent&amp;gt;
 *                         &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *                           &amp;lt;sequence&amp;gt;
 *                             &amp;lt;element name="uvid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&amp;gt;
 *                             &amp;lt;element name="kopija" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&amp;gt;
 *                             &amp;lt;element name="dostava" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&amp;gt;
 *                             &amp;lt;element name="posedovanje" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&amp;gt;
 *                           &amp;lt;/sequence&amp;gt;
 *                         &amp;lt;/restriction&amp;gt;
 *                       &amp;lt;/complexContent&amp;gt;
 *                     &amp;lt;/complexType&amp;gt;
 *                   &amp;lt;/element&amp;gt;
 *                 &amp;lt;/sequence&amp;gt;
 *               &amp;lt;/restriction&amp;gt;
 *             &amp;lt;/complexContent&amp;gt;
 *           &amp;lt;/complexType&amp;gt;
 *         &amp;lt;/element&amp;gt;
 *         &amp;lt;element name="podaci_o_zalbi"&amp;gt;
 *           &amp;lt;complexType&amp;gt;
 *             &amp;lt;complexContent&amp;gt;
 *               &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *                 &amp;lt;sequence&amp;gt;
 *                   &amp;lt;element name="podnosilac_zalbe"&amp;gt;
 *                     &amp;lt;complexType&amp;gt;
 *                       &amp;lt;complexContent&amp;gt;
 *                         &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *                           &amp;lt;sequence&amp;gt;
 *                             &amp;lt;element name="lice" type="{http://www.projekat.org/common}TLice"/&amp;gt;
 *                             &amp;lt;element name="drugi_podaci_za_kontakt"&amp;gt;
 *                               &amp;lt;simpleType&amp;gt;
 *                                 &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt;
 *                                   &amp;lt;minLength value="1"/&amp;gt;
 *                                 &amp;lt;/restriction&amp;gt;
 *                               &amp;lt;/simpleType&amp;gt;
 *                             &amp;lt;/element&amp;gt;
 *                           &amp;lt;/sequence&amp;gt;
 *                         &amp;lt;/restriction&amp;gt;
 *                       &amp;lt;/complexContent&amp;gt;
 *                     &amp;lt;/complexType&amp;gt;
 *                   &amp;lt;/element&amp;gt;
 *                   &amp;lt;element name="datum_podnosenja" type="{http://www.w3.org/2001/XMLSchema}date"/&amp;gt;
 *                   &amp;lt;element name="mesto"&amp;gt;
 *                     &amp;lt;simpleType&amp;gt;
 *                       &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt;
 *                         &amp;lt;minLength value="1"/&amp;gt;
 *                       &amp;lt;/restriction&amp;gt;
 *                     &amp;lt;/simpleType&amp;gt;
 *                   &amp;lt;/element&amp;gt;
 *                   &amp;lt;element name="razlog_zalbe"&amp;gt;
 *                     &amp;lt;simpleType&amp;gt;
 *                       &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt;
 *                         &amp;lt;enumeration value="nije postupio"/&amp;gt;
 *                         &amp;lt;enumeration value="nije postupio u celosti"/&amp;gt;
 *                         &amp;lt;enumeration value="nije postupio u zakonskom roku"/&amp;gt;
 *                       &amp;lt;/restriction&amp;gt;
 *                     &amp;lt;/simpleType&amp;gt;
 *                   &amp;lt;/element&amp;gt;
 *                 &amp;lt;/sequence&amp;gt;
 *               &amp;lt;/restriction&amp;gt;
 *             &amp;lt;/complexContent&amp;gt;
 *           &amp;lt;/complexType&amp;gt;
 *         &amp;lt;/element&amp;gt;
 *       &amp;lt;/sequence&amp;gt;
 *       &amp;lt;attribute name="broj_zalbe"&amp;gt;
 *         &amp;lt;simpleType&amp;gt;
 *           &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt;
 *             &amp;lt;minLength value="1"/&amp;gt;
 *           &amp;lt;/restriction&amp;gt;
 *         &amp;lt;/simpleType&amp;gt;
 *       &amp;lt;/attribute&amp;gt;
 *       &amp;lt;attribute name="broj_zahteva"&amp;gt;
 *         &amp;lt;simpleType&amp;gt;
 *           &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt;
 *             &amp;lt;minLength value="1"/&amp;gt;
 *           &amp;lt;/restriction&amp;gt;
 *         &amp;lt;/simpleType&amp;gt;
 *       &amp;lt;/attribute&amp;gt;
 *       &amp;lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&amp;gt;
 *     &amp;lt;/restriction&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", namespace = "http://www.projekat.org/zalba_cutanja", propOrder = {
    "adresaPoverenika",
    "organProtivKojegJeZalba",
    "podaciOZahtevu",
    "podaciOZalbi"
})
@XmlRootElement(name = "zalba_na_cutanje", namespace = "http://www.projekat.org/zalba_cutanja")
public class ZalbaNaCutanje {

    @XmlElement(name = "adresa_poverenika", namespace = "http://www.projekat.org/zalba_cutanja", required = true)
    protected TAdresa adresaPoverenika;
    @XmlElement(name = "organ_protiv_kojeg_je_zalba", namespace = "http://www.projekat.org/zalba_cutanja", required = true)
    protected TPravnoLice organProtivKojegJeZalba;
    @XmlElement(name = "podaci_o_zahtevu", namespace = "http://www.projekat.org/zalba_cutanja", required = true)
    protected ZalbaNaCutanje.PodaciOZahtevu podaciOZahtevu;
    @XmlElement(name = "podaci_o_zalbi", namespace = "http://www.projekat.org/zalba_cutanja", required = true)
    protected ZalbaNaCutanje.PodaciOZalbi podaciOZalbi;
    @XmlAttribute(name = "broj_zalbe")
    protected String brojZalbe;
    @XmlAttribute(name = "broj_zahteva")
    protected String brojZahteva;
    @XmlAttribute(name = "id", required = true)
    protected String id;

    /**
     * Gets the value of the adresaPoverenika property.
     * 
     * @return
     *     possible object is
     *     {@link TAdresa }
     *     
     */
    public TAdresa getAdresaPoverenika() {
        return adresaPoverenika;
    }

    /**
     * Sets the value of the adresaPoverenika property.
     * 
     * @param value
     *     allowed object is
     *     {@link TAdresa }
     *     
     */
    public void setAdresaPoverenika(TAdresa value) {
        this.adresaPoverenika = value;
    }

    /**
     * Gets the value of the organProtivKojegJeZalba property.
     * 
     * @return
     *     possible object is
     *     {@link TPravnoLice }
     *     
     */
    public TPravnoLice getOrganProtivKojegJeZalba() {
        return organProtivKojegJeZalba;
    }

    /**
     * Sets the value of the organProtivKojegJeZalba property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPravnoLice }
     *     
     */
    public void setOrganProtivKojegJeZalba(TPravnoLice value) {
        this.organProtivKojegJeZalba = value;
    }

    /**
     * Gets the value of the podaciOZahtevu property.
     * 
     * @return
     *     possible object is
     *     {@link ZalbaNaCutanje.PodaciOZahtevu }
     *     
     */
    public ZalbaNaCutanje.PodaciOZahtevu getPodaciOZahtevu() {
        return podaciOZahtevu;
    }

    /**
     * Sets the value of the podaciOZahtevu property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZalbaNaCutanje.PodaciOZahtevu }
     *     
     */
    public void setPodaciOZahtevu(ZalbaNaCutanje.PodaciOZahtevu value) {
        this.podaciOZahtevu = value;
    }

    /**
     * Gets the value of the podaciOZalbi property.
     * 
     * @return
     *     possible object is
     *     {@link ZalbaNaCutanje.PodaciOZalbi }
     *     
     */
    public ZalbaNaCutanje.PodaciOZalbi getPodaciOZalbi() {
        return podaciOZalbi;
    }

    /**
     * Sets the value of the podaciOZalbi property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZalbaNaCutanje.PodaciOZalbi }
     *     
     */
    public void setPodaciOZalbi(ZalbaNaCutanje.PodaciOZalbi value) {
        this.podaciOZalbi = value;
    }

    /**
     * Gets the value of the brojZalbe property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrojZalbe() {
        return brojZalbe;
    }

    /**
     * Sets the value of the brojZalbe property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrojZalbe(String value) {
        this.brojZalbe = value;
    }

    /**
     * Gets the value of the brojZahteva property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrojZahteva() {
        return brojZahteva;
    }

    /**
     * Sets the value of the brojZahteva property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrojZahteva(String value) {
        this.brojZahteva = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }


    /**
     * &lt;p&gt;Java class for anonymous complex type.
     * 
     * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
     * 
     * &lt;pre&gt;
     * &amp;lt;complexType&amp;gt;
     *   &amp;lt;complexContent&amp;gt;
     *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
     *       &amp;lt;sequence&amp;gt;
     *         &amp;lt;element name="informacije"&amp;gt;
     *           &amp;lt;simpleType&amp;gt;
     *             &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt;
     *               &amp;lt;minLength value="1"/&amp;gt;
     *             &amp;lt;/restriction&amp;gt;
     *           &amp;lt;/simpleType&amp;gt;
     *         &amp;lt;/element&amp;gt;
     *         &amp;lt;element name="datum" type="{http://www.w3.org/2001/XMLSchema}date"/&amp;gt;
     *         &amp;lt;element name="zahtevi"&amp;gt;
     *           &amp;lt;complexType&amp;gt;
     *             &amp;lt;complexContent&amp;gt;
     *               &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
     *                 &amp;lt;sequence&amp;gt;
     *                   &amp;lt;element name="uvid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&amp;gt;
     *                   &amp;lt;element name="kopija" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&amp;gt;
     *                   &amp;lt;element name="dostava" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&amp;gt;
     *                   &amp;lt;element name="posedovanje" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&amp;gt;
     *                 &amp;lt;/sequence&amp;gt;
     *               &amp;lt;/restriction&amp;gt;
     *             &amp;lt;/complexContent&amp;gt;
     *           &amp;lt;/complexType&amp;gt;
     *         &amp;lt;/element&amp;gt;
     *       &amp;lt;/sequence&amp;gt;
     *     &amp;lt;/restriction&amp;gt;
     *   &amp;lt;/complexContent&amp;gt;
     * &amp;lt;/complexType&amp;gt;
     * &lt;/pre&gt;
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", namespace = "http://www.projekat.org/zalba_cutanja", propOrder = {
        "informacije",
        "datum",
        "zahtevi"
    })
    public static class PodaciOZahtevu {

        @XmlElement(namespace = "http://www.projekat.org/zalba_cutanja", required = true)
        protected String informacije;
        @XmlElement(namespace = "http://www.projekat.org/zalba_cutanja", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar datum;
        @XmlElement(namespace = "http://www.projekat.org/zalba_cutanja", required = true)
        protected ZalbaNaCutanje.PodaciOZahtevu.Zahtevi zahtevi;

        /**
         * Gets the value of the informacije property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInformacije() {
            return informacije;
        }

        /**
         * Sets the value of the informacije property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInformacije(String value) {
            this.informacije = value;
        }

        /**
         * Gets the value of the datum property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDatum() {
            return datum;
        }

        /**
         * Sets the value of the datum property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDatum(XMLGregorianCalendar value) {
            this.datum = value;
        }

        /**
         * Gets the value of the zahtevi property.
         * 
         * @return
         *     possible object is
         *     {@link ZalbaNaCutanje.PodaciOZahtevu.Zahtevi }
         *     
         */
        public ZalbaNaCutanje.PodaciOZahtevu.Zahtevi getZahtevi() {
            return zahtevi;
        }

        /**
         * Sets the value of the zahtevi property.
         * 
         * @param value
         *     allowed object is
         *     {@link ZalbaNaCutanje.PodaciOZahtevu.Zahtevi }
         *     
         */
        public void setZahtevi(ZalbaNaCutanje.PodaciOZahtevu.Zahtevi value) {
            this.zahtevi = value;
        }


        /**
         * &lt;p&gt;Java class for anonymous complex type.
         * 
         * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
         * 
         * &lt;pre&gt;
         * &amp;lt;complexType&amp;gt;
         *   &amp;lt;complexContent&amp;gt;
         *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
         *       &amp;lt;sequence&amp;gt;
         *         &amp;lt;element name="uvid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&amp;gt;
         *         &amp;lt;element name="kopija" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&amp;gt;
         *         &amp;lt;element name="dostava" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&amp;gt;
         *         &amp;lt;element name="posedovanje" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&amp;gt;
         *       &amp;lt;/sequence&amp;gt;
         *     &amp;lt;/restriction&amp;gt;
         *   &amp;lt;/complexContent&amp;gt;
         * &amp;lt;/complexType&amp;gt;
         * &lt;/pre&gt;
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", namespace = "http://www.projekat.org/zalba_cutanja", propOrder = {
            "uvid",
            "kopija",
            "dostava",
            "posedovanje"
        })
        public static class Zahtevi {

            @XmlElement(namespace = "http://www.projekat.org/zalba_cutanja")
            protected String uvid;
            @XmlElement(namespace = "http://www.projekat.org/zalba_cutanja")
            protected String kopija;
            @XmlElement(namespace = "http://www.projekat.org/zalba_cutanja")
            protected String dostava;
            @XmlElement(namespace = "http://www.projekat.org/zalba_cutanja")
            protected String posedovanje;

            /**
             * Gets the value of the uvid property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUvid() {
                return uvid;
            }

            /**
             * Sets the value of the uvid property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUvid(String value) {
                this.uvid = value;
            }

            /**
             * Gets the value of the kopija property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getKopija() {
                return kopija;
            }

            /**
             * Sets the value of the kopija property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setKopija(String value) {
                this.kopija = value;
            }

            /**
             * Gets the value of the dostava property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDostava() {
                return dostava;
            }

            /**
             * Sets the value of the dostava property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDostava(String value) {
                this.dostava = value;
            }

            /**
             * Gets the value of the posedovanje property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPosedovanje() {
                return posedovanje;
            }

            /**
             * Sets the value of the posedovanje property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPosedovanje(String value) {
                this.posedovanje = value;
            }

        }

    }


    /**
     * &lt;p&gt;Java class for anonymous complex type.
     * 
     * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
     * 
     * &lt;pre&gt;
     * &amp;lt;complexType&amp;gt;
     *   &amp;lt;complexContent&amp;gt;
     *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
     *       &amp;lt;sequence&amp;gt;
     *         &amp;lt;element name="podnosilac_zalbe"&amp;gt;
     *           &amp;lt;complexType&amp;gt;
     *             &amp;lt;complexContent&amp;gt;
     *               &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
     *                 &amp;lt;sequence&amp;gt;
     *                   &amp;lt;element name="lice" type="{http://www.projekat.org/common}TLice"/&amp;gt;
     *                   &amp;lt;element name="drugi_podaci_za_kontakt"&amp;gt;
     *                     &amp;lt;simpleType&amp;gt;
     *                       &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt;
     *                         &amp;lt;minLength value="1"/&amp;gt;
     *                       &amp;lt;/restriction&amp;gt;
     *                     &amp;lt;/simpleType&amp;gt;
     *                   &amp;lt;/element&amp;gt;
     *                 &amp;lt;/sequence&amp;gt;
     *               &amp;lt;/restriction&amp;gt;
     *             &amp;lt;/complexContent&amp;gt;
     *           &amp;lt;/complexType&amp;gt;
     *         &amp;lt;/element&amp;gt;
     *         &amp;lt;element name="datum_podnosenja" type="{http://www.w3.org/2001/XMLSchema}date"/&amp;gt;
     *         &amp;lt;element name="mesto"&amp;gt;
     *           &amp;lt;simpleType&amp;gt;
     *             &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt;
     *               &amp;lt;minLength value="1"/&amp;gt;
     *             &amp;lt;/restriction&amp;gt;
     *           &amp;lt;/simpleType&amp;gt;
     *         &amp;lt;/element&amp;gt;
     *         &amp;lt;element name="razlog_zalbe"&amp;gt;
     *           &amp;lt;simpleType&amp;gt;
     *             &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt;
     *               &amp;lt;enumeration value="nije postupio"/&amp;gt;
     *               &amp;lt;enumeration value="nije postupio u celosti"/&amp;gt;
     *               &amp;lt;enumeration value="nije postupio u zakonskom roku"/&amp;gt;
     *             &amp;lt;/restriction&amp;gt;
     *           &amp;lt;/simpleType&amp;gt;
     *         &amp;lt;/element&amp;gt;
     *       &amp;lt;/sequence&amp;gt;
     *     &amp;lt;/restriction&amp;gt;
     *   &amp;lt;/complexContent&amp;gt;
     * &amp;lt;/complexType&amp;gt;
     * &lt;/pre&gt;
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", namespace = "http://www.projekat.org/zalba_cutanja", propOrder = {
        "podnosilacZalbe",
        "datumPodnosenja",
        "mesto",
        "razlogZalbe"
    })
    public static class PodaciOZalbi {

        @XmlElement(name = "podnosilac_zalbe", namespace = "http://www.projekat.org/zalba_cutanja", required = true)
        protected ZalbaNaCutanje.PodaciOZalbi.PodnosilacZalbe podnosilacZalbe;
        @XmlElement(name = "datum_podnosenja", namespace = "http://www.projekat.org/zalba_cutanja", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar datumPodnosenja;
        @XmlElement(namespace = "http://www.projekat.org/zalba_cutanja", required = true)
        protected String mesto;
        @XmlElement(name = "razlog_zalbe", namespace = "http://www.projekat.org/zalba_cutanja", required = true)
        protected String razlogZalbe;

        /**
         * Gets the value of the podnosilacZalbe property.
         * 
         * @return
         *     possible object is
         *     {@link ZalbaNaCutanje.PodaciOZalbi.PodnosilacZalbe }
         *     
         */
        public ZalbaNaCutanje.PodaciOZalbi.PodnosilacZalbe getPodnosilacZalbe() {
            return podnosilacZalbe;
        }

        /**
         * Sets the value of the podnosilacZalbe property.
         * 
         * @param value
         *     allowed object is
         *     {@link ZalbaNaCutanje.PodaciOZalbi.PodnosilacZalbe }
         *     
         */
        public void setPodnosilacZalbe(ZalbaNaCutanje.PodaciOZalbi.PodnosilacZalbe value) {
            this.podnosilacZalbe = value;
        }

        /**
         * Gets the value of the datumPodnosenja property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDatumPodnosenja() {
            return datumPodnosenja;
        }

        /**
         * Sets the value of the datumPodnosenja property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDatumPodnosenja(XMLGregorianCalendar value) {
            this.datumPodnosenja = value;
        }

        /**
         * Gets the value of the mesto property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMesto() {
            return mesto;
        }

        /**
         * Sets the value of the mesto property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMesto(String value) {
            this.mesto = value;
        }

        /**
         * Gets the value of the razlogZalbe property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRazlogZalbe() {
            return razlogZalbe;
        }

        /**
         * Sets the value of the razlogZalbe property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRazlogZalbe(String value) {
            this.razlogZalbe = value;
        }


        /**
         * &lt;p&gt;Java class for anonymous complex type.
         * 
         * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
         * 
         * &lt;pre&gt;
         * &amp;lt;complexType&amp;gt;
         *   &amp;lt;complexContent&amp;gt;
         *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
         *       &amp;lt;sequence&amp;gt;
         *         &amp;lt;element name="lice" type="{http://www.projekat.org/common}TLice"/&amp;gt;
         *         &amp;lt;element name="drugi_podaci_za_kontakt"&amp;gt;
         *           &amp;lt;simpleType&amp;gt;
         *             &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt;
         *               &amp;lt;minLength value="1"/&amp;gt;
         *             &amp;lt;/restriction&amp;gt;
         *           &amp;lt;/simpleType&amp;gt;
         *         &amp;lt;/element&amp;gt;
         *       &amp;lt;/sequence&amp;gt;
         *     &amp;lt;/restriction&amp;gt;
         *   &amp;lt;/complexContent&amp;gt;
         * &amp;lt;/complexType&amp;gt;
         * &lt;/pre&gt;
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", namespace = "http://www.projekat.org/zalba_cutanja", propOrder = {
            "lice",
            "drugiPodaciZaKontakt"
        })
        public static class PodnosilacZalbe {

            @XmlElement(namespace = "http://www.projekat.org/zalba_cutanja", required = true)
            protected TLice lice;
            @XmlElement(name = "drugi_podaci_za_kontakt", namespace = "http://www.projekat.org/zalba_cutanja", required = true)
            protected String drugiPodaciZaKontakt;

            /**
             * Gets the value of the lice property.
             * 
             * @return
             *     possible object is
             *     {@link TLice }
             *     
             */
            public TLice getLice() {
                return lice;
            }

            /**
             * Sets the value of the lice property.
             * 
             * @param value
             *     allowed object is
             *     {@link TLice }
             *     
             */
            public void setLice(TLice value) {
                this.lice = value;
            }

            /**
             * Gets the value of the drugiPodaciZaKontakt property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDrugiPodaciZaKontakt() {
                return drugiPodaciZaKontakt;
            }

            /**
             * Sets the value of the drugiPodaciZaKontakt property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDrugiPodaciZaKontakt(String value) {
                this.drugiPodaciZaKontakt = value;
            }

        }

    }

}
