//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.10 at 07:08:21 PM CET 
//


package projectXML.team10.poverenik.models.zalbaCutanje;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;

import projectXML.team10.poverenik.models.common.TAdresa;
import projectXML.team10.poverenik.models.common.TFizickoLice;
import projectXML.team10.poverenik.models.common.TPravnoLice;


/**
 * &lt;p&gt;Java class for anonymous complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *       &amp;lt;sequence&amp;gt;
 *         &amp;lt;element name="adresa_poverenika" type="{http://www.projekat.org/common}TAdresa"/&amp;gt;
 *         &amp;lt;element name="organ_protiv_kojeg_je_zalba"&amp;gt;
 *           &amp;lt;complexType&amp;gt;
 *             &amp;lt;complexContent&amp;gt;
 *               &amp;lt;extension base="{http://www.projekat.org/common}TPravno_lice"&amp;gt;
 *                 &amp;lt;attribute name="property" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="pred:organ_protiv_kojeg_je_zalba" /&amp;gt;
 *                 &amp;lt;attribute name="datatype" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="xs:string" /&amp;gt;
 *               &amp;lt;/extension&amp;gt;
 *             &amp;lt;/complexContent&amp;gt;
 *           &amp;lt;/complexType&amp;gt;
 *         &amp;lt;/element&amp;gt;
 *         &amp;lt;element name="podaci_o_zahtevu"&amp;gt;
 *           &amp;lt;complexType&amp;gt;
 *             &amp;lt;complexContent&amp;gt;
 *               &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *                 &amp;lt;sequence&amp;gt;
 *                   &amp;lt;element name="informacije"&amp;gt;
 *                     &amp;lt;simpleType&amp;gt;
 *                       &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt;
 *                         &amp;lt;minLength value="1"/&amp;gt;
 *                       &amp;lt;/restriction&amp;gt;
 *                     &amp;lt;/simpleType&amp;gt;
 *                   &amp;lt;/element&amp;gt;
 *                   &amp;lt;element name="datum" type="{http://www.w3.org/2001/XMLSchema}date"/&amp;gt;
 *                   &amp;lt;element name="zahtevi"&amp;gt;
 *                     &amp;lt;complexType&amp;gt;
 *                       &amp;lt;complexContent&amp;gt;
 *                         &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *                           &amp;lt;sequence&amp;gt;
 *                             &amp;lt;element name="uvid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&amp;gt;
 *                             &amp;lt;element name="kopija" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&amp;gt;
 *                             &amp;lt;element name="dostava" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&amp;gt;
 *                             &amp;lt;element name="posedovanje" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&amp;gt;
 *                           &amp;lt;/sequence&amp;gt;
 *                         &amp;lt;/restriction&amp;gt;
 *                       &amp;lt;/complexContent&amp;gt;
 *                     &amp;lt;/complexType&amp;gt;
 *                   &amp;lt;/element&amp;gt;
 *                 &amp;lt;/sequence&amp;gt;
 *               &amp;lt;/restriction&amp;gt;
 *             &amp;lt;/complexContent&amp;gt;
 *           &amp;lt;/complexType&amp;gt;
 *         &amp;lt;/element&amp;gt;
 *         &amp;lt;element name="podaci_o_zalbi"&amp;gt;
 *           &amp;lt;complexType&amp;gt;
 *             &amp;lt;complexContent&amp;gt;
 *               &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *                 &amp;lt;sequence&amp;gt;
 *                   &amp;lt;element name="podnosilac_zalbe"&amp;gt;
 *                     &amp;lt;complexType&amp;gt;
 *                       &amp;lt;complexContent&amp;gt;
 *                         &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *                           &amp;lt;sequence&amp;gt;
 *                             &amp;lt;element name="lice" type="{http://www.projekat.org/common}TFizicko_lice"/&amp;gt;
 *                             &amp;lt;element name="drugi_podaci_za_kontakt"&amp;gt;
 *                               &amp;lt;simpleType&amp;gt;
 *                                 &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt;
 *                                   &amp;lt;minLength value="1"/&amp;gt;
 *                                 &amp;lt;/restriction&amp;gt;
 *                               &amp;lt;/simpleType&amp;gt;
 *                             &amp;lt;/element&amp;gt;
 *                           &amp;lt;/sequence&amp;gt;
 *                           &amp;lt;attribute name="property" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="pred:podnosilac_zalbe" /&amp;gt;
 *                           &amp;lt;attribute name="id_podnosioca" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&amp;gt;
 *                           &amp;lt;attribute name="resource" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&amp;gt;
 *                         &amp;lt;/restriction&amp;gt;
 *                       &amp;lt;/complexContent&amp;gt;
 *                     &amp;lt;/complexType&amp;gt;
 *                   &amp;lt;/element&amp;gt;
 *                   &amp;lt;element name="datum_podnosenja"&amp;gt;
 *                     &amp;lt;complexType&amp;gt;
 *                       &amp;lt;simpleContent&amp;gt;
 *                         &amp;lt;extension base="&amp;lt;http://www.w3.org/2001/XMLSchema&amp;gt;date"&amp;gt;
 *                           &amp;lt;attribute name="property" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="pred:datum_podnosenja" /&amp;gt;
 *                           &amp;lt;attribute name="datatype" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="xs:date" /&amp;gt;
 *                         &amp;lt;/extension&amp;gt;
 *                       &amp;lt;/simpleContent&amp;gt;
 *                     &amp;lt;/complexType&amp;gt;
 *                   &amp;lt;/element&amp;gt;
 *                   &amp;lt;element name="mesto"&amp;gt;
 *                     &amp;lt;complexType&amp;gt;
 *                       &amp;lt;simpleContent&amp;gt;
 *                         &amp;lt;extension base="&amp;lt;http://www.w3.org/2001/XMLSchema&amp;gt;string"&amp;gt;
 *                           &amp;lt;attribute name="property" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="pred:mesto_podnosenja" /&amp;gt;
 *                           &amp;lt;attribute name="datatype" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="xs:string" /&amp;gt;
 *                         &amp;lt;/extension&amp;gt;
 *                       &amp;lt;/simpleContent&amp;gt;
 *                     &amp;lt;/complexType&amp;gt;
 *                   &amp;lt;/element&amp;gt;
 *                   &amp;lt;element name="razlog_zalbe"&amp;gt;
 *                     &amp;lt;simpleType&amp;gt;
 *                       &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt;
 *                         &amp;lt;enumeration value="\u043d\u0438\u0458\u0435 \u043f\u043e\u0441\u0442\u0443\u043f\u0438\u043e"/&amp;gt;
 *                         &amp;lt;enumeration value="\u043d\u0438\u0458\u0435 \u043f\u043e\u0441\u0442\u0443\u043f\u0438\u043e \u0443 \u0446\u0435\u043b\u043e\u0441\u0442\u0438"/&amp;gt;
 *                         &amp;lt;enumeration value="\u043d\u0438\u0458\u0435 \u043f\u043e\u0441\u0442\u0443\u043f\u0438\u043e \u0443 \u0437\u0430\u043a\u043e\u043d\u0441\u043a\u043e\u043c \u0440\u043e\u043a\u0443"/&amp;gt;
 *                       &amp;lt;/restriction&amp;gt;
 *                     &amp;lt;/simpleType&amp;gt;
 *                   &amp;lt;/element&amp;gt;
 *                 &amp;lt;/sequence&amp;gt;
 *               &amp;lt;/restriction&amp;gt;
 *             &amp;lt;/complexContent&amp;gt;
 *           &amp;lt;/complexType&amp;gt;
 *         &amp;lt;/element&amp;gt;
 *       &amp;lt;/sequence&amp;gt;
 *       &amp;lt;attribute name="broj_zalbe"&amp;gt;
 *         &amp;lt;simpleType&amp;gt;
 *           &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt;
 *             &amp;lt;minLength value="1"/&amp;gt;
 *           &amp;lt;/restriction&amp;gt;
 *         &amp;lt;/simpleType&amp;gt;
 *       &amp;lt;/attribute&amp;gt;
 *       &amp;lt;attribute name="broj_zahteva" use="required"&amp;gt;
 *         &amp;lt;simpleType&amp;gt;
 *           &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt;
 *             &amp;lt;minLength value="1"/&amp;gt;
 *           &amp;lt;/restriction&amp;gt;
 *         &amp;lt;/simpleType&amp;gt;
 *       &amp;lt;/attribute&amp;gt;
 *       &amp;lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" /&amp;gt;
 *       &amp;lt;attribute name="vocab" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="http://www.projekat.org/predicate" /&amp;gt;
 *       &amp;lt;attribute name="about" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&amp;gt;
 *     &amp;lt;/restriction&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "adresaPoverenika",
    "organProtivKojegJeZalba",
    "podaciOZahtevu",
    "podaciOZalbi"
})
@XmlRootElement(name = "zalba_na_cutanje", namespace = "http://www.projekat.org/zalba_cutanja")
public class ZalbaNaCutanje {

    @XmlElement(name = "adresa_poverenika", namespace = "http://www.projekat.org/zalba_cutanja", required = true)
    protected TAdresa adresaPoverenika;
    @XmlElement(name = "organ_protiv_kojeg_je_zalba", namespace = "http://www.projekat.org/zalba_cutanja", required = true)
    protected ZalbaNaCutanje.OrganProtivKojegJeZalba organProtivKojegJeZalba;
    @XmlElement(name = "podaci_o_zahtevu", namespace = "http://www.projekat.org/zalba_cutanja", required = true)
    protected ZalbaNaCutanje.PodaciOZahtevu podaciOZahtevu;
    @XmlElement(name = "podaci_o_zalbi", namespace = "http://www.projekat.org/zalba_cutanja", required = true)
    protected ZalbaNaCutanje.PodaciOZalbi podaciOZalbi;
    @XmlAttribute(name = "broj_zalbe")
    protected String brojZalbe;
    @XmlAttribute(name = "broj_zahteva", required = true)
    protected String brojZahteva;
    @XmlAttribute(name = "id")
    protected String id;
    @XmlAttribute(name = "vocab", required = true)
    protected String vocab;
    @XmlAttribute(name = "about", required = true)
    protected String about;

    /**
     * Gets the value of the adresaPoverenika property.
     * 
     * @return
     *     possible object is
     *     {@link TAdresa }
     *     
     */
    public TAdresa getAdresaPoverenika() {
        return adresaPoverenika;
    }

    /**
     * Sets the value of the adresaPoverenika property.
     * 
     * @param value
     *     allowed object is
     *     {@link TAdresa }
     *     
     */
    public void setAdresaPoverenika(TAdresa value) {
        this.adresaPoverenika = value;
    }

    /**
     * Gets the value of the organProtivKojegJeZalba property.
     * 
     * @return
     *     possible object is
     *     {@link ZalbaNaCutanje.OrganProtivKojegJeZalba }
     *     
     */
    public ZalbaNaCutanje.OrganProtivKojegJeZalba getOrganProtivKojegJeZalba() {
        return organProtivKojegJeZalba;
    }

    /**
     * Sets the value of the organProtivKojegJeZalba property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZalbaNaCutanje.OrganProtivKojegJeZalba }
     *     
     */
    public void setOrganProtivKojegJeZalba(ZalbaNaCutanje.OrganProtivKojegJeZalba value) {
        this.organProtivKojegJeZalba = value;
    }

    /**
     * Gets the value of the podaciOZahtevu property.
     * 
     * @return
     *     possible object is
     *     {@link ZalbaNaCutanje.PodaciOZahtevu }
     *     
     */
    public ZalbaNaCutanje.PodaciOZahtevu getPodaciOZahtevu() {
        return podaciOZahtevu;
    }

    /**
     * Sets the value of the podaciOZahtevu property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZalbaNaCutanje.PodaciOZahtevu }
     *     
     */
    public void setPodaciOZahtevu(ZalbaNaCutanje.PodaciOZahtevu value) {
        this.podaciOZahtevu = value;
    }

    /**
     * Gets the value of the podaciOZalbi property.
     * 
     * @return
     *     possible object is
     *     {@link ZalbaNaCutanje.PodaciOZalbi }
     *     
     */
    public ZalbaNaCutanje.PodaciOZalbi getPodaciOZalbi() {
        return podaciOZalbi;
    }

    /**
     * Sets the value of the podaciOZalbi property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZalbaNaCutanje.PodaciOZalbi }
     *     
     */
    public void setPodaciOZalbi(ZalbaNaCutanje.PodaciOZalbi value) {
        this.podaciOZalbi = value;
    }

    /**
     * Gets the value of the brojZalbe property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrojZalbe() {
        return brojZalbe;
    }

    /**
     * Sets the value of the brojZalbe property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrojZalbe(String value) {
        this.brojZalbe = value;
    }

    /**
     * Gets the value of the brojZahteva property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrojZahteva() {
        return brojZahteva;
    }

    /**
     * Sets the value of the brojZahteva property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrojZahteva(String value) {
        this.brojZahteva = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the vocab property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVocab() {
        if (vocab == null) {
            return "http://www.projekat.org/predicate";
        } else {
            return vocab;
        }
    }

    /**
     * Sets the value of the vocab property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVocab(String value) {
        this.vocab = value;
    }

    /**
     * Gets the value of the about property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAbout() {
        return about;
    }

    /**
     * Sets the value of the about property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAbout(String value) {
        this.about = value;
    }


    /**
     * &lt;p&gt;Java class for anonymous complex type.
     * 
     * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
     * 
     * &lt;pre&gt;
     * &amp;lt;complexType&amp;gt;
     *   &amp;lt;complexContent&amp;gt;
     *     &amp;lt;extension base="{http://www.projekat.org/common}TPravno_lice"&amp;gt;
     *       &amp;lt;attribute name="property" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="pred:organ_protiv_kojeg_je_zalba" /&amp;gt;
     *       &amp;lt;attribute name="datatype" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="xs:string" /&amp;gt;
     *     &amp;lt;/extension&amp;gt;
     *   &amp;lt;/complexContent&amp;gt;
     * &amp;lt;/complexType&amp;gt;
     * &lt;/pre&gt;
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class OrganProtivKojegJeZalba
        extends TPravnoLice
    {

        @XmlAttribute(name = "property", required = true)
        protected String property;
        @XmlAttribute(name = "content", required = true)
        protected String content;

        /**
         * Gets the value of the property property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProperty() {
            if (property == null) {
                return "pred:organ_protiv_kojeg_je_zalba";
            } else {
                return property;
            }
        }

        /**
         * Sets the value of the property property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProperty(String value) {
            this.property = value;
        }

        /**
         * Gets the value of the datatype property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContent() {
           return content;
        }

        /**
         * Sets the value of the datatype property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContent(String value) {
            this.content = value;
        }

    }


    /**
     * &lt;p&gt;Java class for anonymous complex type.
     * 
     * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
     * 
     * &lt;pre&gt;
     * &amp;lt;complexType&amp;gt;
     *   &amp;lt;complexContent&amp;gt;
     *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
     *       &amp;lt;sequence&amp;gt;
     *         &amp;lt;element name="informacije"&amp;gt;
     *           &amp;lt;simpleType&amp;gt;
     *             &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt;
     *               &amp;lt;minLength value="1"/&amp;gt;
     *             &amp;lt;/restriction&amp;gt;
     *           &amp;lt;/simpleType&amp;gt;
     *         &amp;lt;/element&amp;gt;
     *         &amp;lt;element name="datum" type="{http://www.w3.org/2001/XMLSchema}date"/&amp;gt;
     *         &amp;lt;element name="zahtevi"&amp;gt;
     *           &amp;lt;complexType&amp;gt;
     *             &amp;lt;complexContent&amp;gt;
     *               &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
     *                 &amp;lt;sequence&amp;gt;
     *                   &amp;lt;element name="uvid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&amp;gt;
     *                   &amp;lt;element name="kopija" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&amp;gt;
     *                   &amp;lt;element name="dostava" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&amp;gt;
     *                   &amp;lt;element name="posedovanje" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&amp;gt;
     *                 &amp;lt;/sequence&amp;gt;
     *               &amp;lt;/restriction&amp;gt;
     *             &amp;lt;/complexContent&amp;gt;
     *           &amp;lt;/complexType&amp;gt;
     *         &amp;lt;/element&amp;gt;
     *       &amp;lt;/sequence&amp;gt;
     *     &amp;lt;/restriction&amp;gt;
     *   &amp;lt;/complexContent&amp;gt;
     * &amp;lt;/complexType&amp;gt;
     * &lt;/pre&gt;
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "informacije",
        "datum",
        "zahtevi"
    })
    public static class PodaciOZahtevu {

        @XmlElement(namespace = "http://www.projekat.org/zalba_cutanja", required = true)
        protected String informacije;
        @XmlElement(namespace = "http://www.projekat.org/zalba_cutanja", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar datum;
        @XmlElement(namespace = "http://www.projekat.org/zalba_cutanja", required = true)
        protected ZalbaNaCutanje.PodaciOZahtevu.Zahtevi zahtevi;

        /**
         * Gets the value of the informacije property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInformacije() {
            return informacije;
        }

        /**
         * Sets the value of the informacije property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInformacije(String value) {
            this.informacije = value;
        }

        /**
         * Gets the value of the datum property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDatum() {
            return datum;
        }

        /**
         * Sets the value of the datum property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDatum(XMLGregorianCalendar value) {
            this.datum = value;
        }

        /**
         * Gets the value of the zahtevi property.
         * 
         * @return
         *     possible object is
         *     {@link ZalbaNaCutanje.PodaciOZahtevu.Zahtevi }
         *     
         */
        public ZalbaNaCutanje.PodaciOZahtevu.Zahtevi getZahtevi() {
            return zahtevi;
        }

        /**
         * Sets the value of the zahtevi property.
         * 
         * @param value
         *     allowed object is
         *     {@link ZalbaNaCutanje.PodaciOZahtevu.Zahtevi }
         *     
         */
        public void setZahtevi(ZalbaNaCutanje.PodaciOZahtevu.Zahtevi value) {
            this.zahtevi = value;
        }


        /**
         * &lt;p&gt;Java class for anonymous complex type.
         * 
         * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
         * 
         * &lt;pre&gt;
         * &amp;lt;complexType&amp;gt;
         *   &amp;lt;complexContent&amp;gt;
         *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
         *       &amp;lt;sequence&amp;gt;
         *         &amp;lt;element name="uvid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&amp;gt;
         *         &amp;lt;element name="kopija" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&amp;gt;
         *         &amp;lt;element name="dostava" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&amp;gt;
         *         &amp;lt;element name="posedovanje" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&amp;gt;
         *       &amp;lt;/sequence&amp;gt;
         *     &amp;lt;/restriction&amp;gt;
         *   &amp;lt;/complexContent&amp;gt;
         * &amp;lt;/complexType&amp;gt;
         * &lt;/pre&gt;
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "uvid",
            "kopija",
            "dostava",
            "posedovanje"
        })
        public static class Zahtevi {

            @XmlElement(namespace = "http://www.projekat.org/zalba_cutanja")
            protected String uvid;
            @XmlElement(namespace = "http://www.projekat.org/zalba_cutanja")
            protected String kopija;
            @XmlElement(namespace = "http://www.projekat.org/zalba_cutanja")
            protected String dostava;
            @XmlElement(namespace = "http://www.projekat.org/zalba_cutanja")
            protected String posedovanje;

            /**
             * Gets the value of the uvid property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUvid() {
                return uvid;
            }

            /**
             * Sets the value of the uvid property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUvid(String value) {
                this.uvid = value;
            }

            /**
             * Gets the value of the kopija property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getKopija() {
                return kopija;
            }

            /**
             * Sets the value of the kopija property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setKopija(String value) {
                this.kopija = value;
            }

            /**
             * Gets the value of the dostava property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDostava() {
                return dostava;
            }

            /**
             * Sets the value of the dostava property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDostava(String value) {
                this.dostava = value;
            }

            /**
             * Gets the value of the posedovanje property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPosedovanje() {
                return posedovanje;
            }

            /**
             * Sets the value of the posedovanje property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPosedovanje(String value) {
                this.posedovanje = value;
            }

        }

    }


    /**
     * &lt;p&gt;Java class for anonymous complex type.
     * 
     * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
     * 
     * &lt;pre&gt;
     * &amp;lt;complexType&amp;gt;
     *   &amp;lt;complexContent&amp;gt;
     *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
     *       &amp;lt;sequence&amp;gt;
     *         &amp;lt;element name="podnosilac_zalbe"&amp;gt;
     *           &amp;lt;complexType&amp;gt;
     *             &amp;lt;complexContent&amp;gt;
     *               &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
     *                 &amp;lt;sequence&amp;gt;
     *                   &amp;lt;element name="lice" type="{http://www.projekat.org/common}TFizicko_lice"/&amp;gt;
     *                   &amp;lt;element name="drugi_podaci_za_kontakt"&amp;gt;
     *                     &amp;lt;simpleType&amp;gt;
     *                       &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt;
     *                         &amp;lt;minLength value="1"/&amp;gt;
     *                       &amp;lt;/restriction&amp;gt;
     *                     &amp;lt;/simpleType&amp;gt;
     *                   &amp;lt;/element&amp;gt;
     *                 &amp;lt;/sequence&amp;gt;
     *                 &amp;lt;attribute name="property" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="pred:podnosilac_zalbe" /&amp;gt;
     *                 &amp;lt;attribute name="id_podnosioca" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&amp;gt;
     *                 &amp;lt;attribute name="resource" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&amp;gt;
     *               &amp;lt;/restriction&amp;gt;
     *             &amp;lt;/complexContent&amp;gt;
     *           &amp;lt;/complexType&amp;gt;
     *         &amp;lt;/element&amp;gt;
     *         &amp;lt;element name="datum_podnosenja"&amp;gt;
     *           &amp;lt;complexType&amp;gt;
     *             &amp;lt;simpleContent&amp;gt;
     *               &amp;lt;extension base="&amp;lt;http://www.w3.org/2001/XMLSchema&amp;gt;date"&amp;gt;
     *                 &amp;lt;attribute name="property" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="pred:datum_podnosenja" /&amp;gt;
     *                 &amp;lt;attribute name="datatype" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="xs:date" /&amp;gt;
     *               &amp;lt;/extension&amp;gt;
     *             &amp;lt;/simpleContent&amp;gt;
     *           &amp;lt;/complexType&amp;gt;
     *         &amp;lt;/element&amp;gt;
     *         &amp;lt;element name="mesto"&amp;gt;
     *           &amp;lt;complexType&amp;gt;
     *             &amp;lt;simpleContent&amp;gt;
     *               &amp;lt;extension base="&amp;lt;http://www.w3.org/2001/XMLSchema&amp;gt;string"&amp;gt;
     *                 &amp;lt;attribute name="property" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="pred:mesto_podnosenja" /&amp;gt;
     *                 &amp;lt;attribute name="datatype" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="xs:string" /&amp;gt;
     *               &amp;lt;/extension&amp;gt;
     *             &amp;lt;/simpleContent&amp;gt;
     *           &amp;lt;/complexType&amp;gt;
     *         &amp;lt;/element&amp;gt;
     *         &amp;lt;element name="razlog_zalbe"&amp;gt;
     *           &amp;lt;simpleType&amp;gt;
     *             &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt;
     *               &amp;lt;enumeration value="\u043d\u0438\u0458\u0435 \u043f\u043e\u0441\u0442\u0443\u043f\u0438\u043e"/&amp;gt;
     *               &amp;lt;enumeration value="\u043d\u0438\u0458\u0435 \u043f\u043e\u0441\u0442\u0443\u043f\u0438\u043e \u0443 \u0446\u0435\u043b\u043e\u0441\u0442\u0438"/&amp;gt;
     *               &amp;lt;enumeration value="\u043d\u0438\u0458\u0435 \u043f\u043e\u0441\u0442\u0443\u043f\u0438\u043e \u0443 \u0437\u0430\u043a\u043e\u043d\u0441\u043a\u043e\u043c \u0440\u043e\u043a\u0443"/&amp;gt;
     *             &amp;lt;/restriction&amp;gt;
     *           &amp;lt;/simpleType&amp;gt;
     *         &amp;lt;/element&amp;gt;
     *       &amp;lt;/sequence&amp;gt;
     *     &amp;lt;/restriction&amp;gt;
     *   &amp;lt;/complexContent&amp;gt;
     * &amp;lt;/complexType&amp;gt;
     * &lt;/pre&gt;
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "podnosilacZalbe",
        "datumPodnosenja",
        "mesto",
        "razlogZalbe"
    })
    public static class PodaciOZalbi {

        @XmlElement(name = "podnosilac_zalbe", namespace = "http://www.projekat.org/zalba_cutanja", required = true)
        protected ZalbaNaCutanje.PodaciOZalbi.PodnosilacZalbe podnosilacZalbe;
        @XmlElement(name = "datum_podnosenja", namespace = "http://www.projekat.org/zalba_cutanja", required = true)
        protected ZalbaNaCutanje.PodaciOZalbi.DatumPodnosenja datumPodnosenja;
        @XmlElement(namespace = "http://www.projekat.org/zalba_cutanja", required = true)
        protected ZalbaNaCutanje.PodaciOZalbi.Mesto mesto;
        @XmlElement(name = "razlog_zalbe", namespace = "http://www.projekat.org/zalba_cutanja", required = true)
        protected String razlogZalbe;

        /**
         * Gets the value of the podnosilacZalbe property.
         * 
         * @return
         *     possible object is
         *     {@link ZalbaNaCutanje.PodaciOZalbi.PodnosilacZalbe }
         *     
         */
        public ZalbaNaCutanje.PodaciOZalbi.PodnosilacZalbe getPodnosilacZalbe() {
            return podnosilacZalbe;
        }

        /**
         * Sets the value of the podnosilacZalbe property.
         * 
         * @param value
         *     allowed object is
         *     {@link ZalbaNaCutanje.PodaciOZalbi.PodnosilacZalbe }
         *     
         */
        public void setPodnosilacZalbe(ZalbaNaCutanje.PodaciOZalbi.PodnosilacZalbe value) {
            this.podnosilacZalbe = value;
        }

        /**
         * Gets the value of the datumPodnosenja property.
         * 
         * @return
         *     possible object is
         *     {@link ZalbaNaCutanje.PodaciOZalbi.DatumPodnosenja }
         *     
         */
        public ZalbaNaCutanje.PodaciOZalbi.DatumPodnosenja getDatumPodnosenja() {
            return datumPodnosenja;
        }

        /**
         * Sets the value of the datumPodnosenja property.
         * 
         * @param value
         *     allowed object is
         *     {@link ZalbaNaCutanje.PodaciOZalbi.DatumPodnosenja }
         *     
         */
        public void setDatumPodnosenja(ZalbaNaCutanje.PodaciOZalbi.DatumPodnosenja value) {
            this.datumPodnosenja = value;
        }

        /**
         * Gets the value of the mesto property.
         * 
         * @return
         *     possible object is
         *     {@link ZalbaNaCutanje.PodaciOZalbi.Mesto }
         *     
         */
        public ZalbaNaCutanje.PodaciOZalbi.Mesto getMesto() {
            return mesto;
        }

        /**
         * Sets the value of the mesto property.
         * 
         * @param value
         *     allowed object is
         *     {@link ZalbaNaCutanje.PodaciOZalbi.Mesto }
         *     
         */
        public void setMesto(ZalbaNaCutanje.PodaciOZalbi.Mesto value) {
            this.mesto = value;
        }

        /**
         * Gets the value of the razlogZalbe property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRazlogZalbe() {
            return razlogZalbe;
        }

        /**
         * Sets the value of the razlogZalbe property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRazlogZalbe(String value) {
            this.razlogZalbe = value;
        }


        /**
         * &lt;p&gt;Java class for anonymous complex type.
         * 
         * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
         * 
         * &lt;pre&gt;
         * &amp;lt;complexType&amp;gt;
         *   &amp;lt;simpleContent&amp;gt;
         *     &amp;lt;extension base="&amp;lt;http://www.w3.org/2001/XMLSchema&amp;gt;date"&amp;gt;
         *       &amp;lt;attribute name="property" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="pred:datum_podnosenja" /&amp;gt;
         *       &amp;lt;attribute name="datatype" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="xs:date" /&amp;gt;
         *     &amp;lt;/extension&amp;gt;
         *   &amp;lt;/simpleContent&amp;gt;
         * &amp;lt;/complexType&amp;gt;
         * &lt;/pre&gt;
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class DatumPodnosenja {

            @XmlValue
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar value;
            @XmlAttribute(name = "property", required = true)
            protected String property;
            @XmlAttribute(name = "datatype", required = true)
            protected String datatype;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setValue(XMLGregorianCalendar value) {
                this.value = value;
            }

            /**
             * Gets the value of the property property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getProperty() {
                if (property == null) {
                    return "pred:datum_podnosenja";
                } else {
                    return property;
                }
            }

            /**
             * Sets the value of the property property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setProperty(String value) {
                this.property = value;
            }

            /**
             * Gets the value of the datatype property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDatatype() {
                if (datatype == null) {
                    return "xs:date";
                } else {
                    return datatype;
                }
            }

            /**
             * Sets the value of the datatype property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDatatype(String value) {
                this.datatype = value;
            }

        }


        /**
         * &lt;p&gt;Java class for anonymous complex type.
         * 
         * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
         * 
         * &lt;pre&gt;
         * &amp;lt;complexType&amp;gt;
         *   &amp;lt;simpleContent&amp;gt;
         *     &amp;lt;extension base="&amp;lt;http://www.w3.org/2001/XMLSchema&amp;gt;string"&amp;gt;
         *       &amp;lt;attribute name="property" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="pred:mesto_podnosenja" /&amp;gt;
         *       &amp;lt;attribute name="datatype" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="xs:string" /&amp;gt;
         *     &amp;lt;/extension&amp;gt;
         *   &amp;lt;/simpleContent&amp;gt;
         * &amp;lt;/complexType&amp;gt;
         * &lt;/pre&gt;
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Mesto {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "property", required = true)
            protected String property;
            @XmlAttribute(name = "datatype", required = true)
            protected String datatype;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the property property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getProperty() {
                if (property == null) {
                    return "pred:mesto_podnosenja";
                } else {
                    return property;
                }
            }

            /**
             * Sets the value of the property property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setProperty(String value) {
                this.property = value;
            }

            /**
             * Gets the value of the datatype property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDatatype() {
                if (datatype == null) {
                    return "xs:string";
                } else {
                    return datatype;
                }
            }

            /**
             * Sets the value of the datatype property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDatatype(String value) {
                this.datatype = value;
            }

        }


        /**
         * &lt;p&gt;Java class for anonymous complex type.
         * 
         * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
         * 
         * &lt;pre&gt;
         * &amp;lt;complexType&amp;gt;
         *   &amp;lt;complexContent&amp;gt;
         *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
         *       &amp;lt;sequence&amp;gt;
         *         &amp;lt;element name="lice" type="{http://www.projekat.org/common}TFizicko_lice"/&amp;gt;
         *         &amp;lt;element name="drugi_podaci_za_kontakt"&amp;gt;
         *           &amp;lt;simpleType&amp;gt;
         *             &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt;
         *               &amp;lt;minLength value="1"/&amp;gt;
         *             &amp;lt;/restriction&amp;gt;
         *           &amp;lt;/simpleType&amp;gt;
         *         &amp;lt;/element&amp;gt;
         *       &amp;lt;/sequence&amp;gt;
         *       &amp;lt;attribute name="property" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="pred:podnosilac_zalbe" /&amp;gt;
         *       &amp;lt;attribute name="id_podnosioca" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&amp;gt;
         *       &amp;lt;attribute name="resource" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&amp;gt;
         *     &amp;lt;/restriction&amp;gt;
         *   &amp;lt;/complexContent&amp;gt;
         * &amp;lt;/complexType&amp;gt;
         * &lt;/pre&gt;
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "lice",
            "drugiPodaciZaKontakt"
        })
        public static class PodnosilacZalbe {

            @XmlElement(namespace = "http://www.projekat.org/zalba_cutanja", required = true)
            protected TFizickoLice lice;
            @XmlElement(name = "drugi_podaci_za_kontakt", namespace = "http://www.projekat.org/zalba_cutanja", required = true)
            protected String drugiPodaciZaKontakt;
            @XmlAttribute(name = "property", required = true)
            protected String property;
            @XmlAttribute(name = "id_podnosioca", required = true)
            protected String idPodnosioca;
            @XmlAttribute(name = "content", required = true)
            protected String content;

            /**
             * Gets the value of the lice property.
             * 
             * @return
             *     possible object is
             *     {@link TFizickoLice }
             *     
             */
            public TFizickoLice getLice() {
                return lice;
            }

            /**
             * Sets the value of the lice property.
             * 
             * @param value
             *     allowed object is
             *     {@link TFizickoLice }
             *     
             */
            public void setLice(TFizickoLice value) {
                this.lice = value;
            }

            /**
             * Gets the value of the drugiPodaciZaKontakt property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDrugiPodaciZaKontakt() {
                return drugiPodaciZaKontakt;
            }

            /**
             * Sets the value of the drugiPodaciZaKontakt property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDrugiPodaciZaKontakt(String value) {
                this.drugiPodaciZaKontakt = value;
            }

            /**
             * Gets the value of the property property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getProperty() {
                if (property == null) {
                    return "pred:podnosilac_zalbe";
                } else {
                    return property;
                }
            }

            /**
             * Sets the value of the property property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setProperty(String value) {
                this.property = value;
            }

            /**
             * Gets the value of the idPodnosioca property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIdPodnosioca() {
                return idPodnosioca;
            }

            /**
             * Sets the value of the idPodnosioca property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIdPodnosioca(String value) {
                this.idPodnosioca = value;
            }

            /**
             * Gets the value of the resource property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getContent() {
                return content;
            }

            /**
             * Sets the value of the resource property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setContent(String value) {
                this.content = value;
            }

        }

    }

}
