//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.05 at 03:34:09 PM CET 
//

package projectXML.team9.models.obavestenje;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;

import projectXML.team9.models.common.TAdresa;
import projectXML.team9.models.common.TLice;
import projectXML.team9.models.common.TPravnoLice;

/**
 * &lt;p&gt;Java class for anonymous complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content
 * contained within this class.
 * 
 * &lt;pre&gt; &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 * &amp;lt;sequence&amp;gt; &amp;lt;element
 * name="informacije_o_obavestenju"&amp;gt; &amp;lt;complexType&amp;gt;
 * &amp;lt;complexContent&amp;gt; &amp;lt;restriction
 * base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 * &amp;lt;sequence&amp;gt; &amp;lt;element name="organ"
 * type="{http://www.projekat.org/obavestenje}TPravno_lice"/&amp;gt;
 * &amp;lt;element name="trazilac"
 * type="{http://www.projekat.org/obavestenje}TLice"/&amp;gt; &amp;lt;element
 * name="datum_obavestenja"
 * type="{http://www.w3.org/2001/XMLSchema}date"/&amp;gt;
 * &amp;lt;/sequence&amp;gt; &amp;lt;/restriction&amp;gt;
 * &amp;lt;/complexContent&amp;gt; &amp;lt;/complexType&amp;gt;
 * &amp;lt;/element&amp;gt; &amp;lt;element name="zahtev"&amp;gt;
 * &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 * &amp;lt;sequence&amp;gt; &amp;lt;element name="datum_trazenja_informacija"
 * type="{http://www.w3.org/2001/XMLSchema}date"/&amp;gt; &amp;lt;element
 * name="opis_trazene_informacije"&amp;gt; &amp;lt;simpleType&amp;gt;
 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt;
 * &amp;lt;minLength value="1"/&amp;gt; &amp;lt;/restriction&amp;gt;
 * &amp;lt;/simpleType&amp;gt; &amp;lt;/element&amp;gt;
 * &amp;lt;/sequence&amp;gt; &amp;lt;/restriction&amp;gt;
 * &amp;lt;/complexContent&amp;gt; &amp;lt;/complexType&amp;gt;
 * &amp;lt;/element&amp;gt; &amp;lt;element name="odgovor_na_zahtev"&amp;gt;
 * &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 * &amp;lt;sequence&amp;gt; &amp;lt;element name="uplata_troskova"
 * minOccurs="0"&amp;gt; &amp;lt;complexType&amp;gt;
 * &amp;lt;complexContent&amp;gt; &amp;lt;extension
 * base="{http://www.projekat.org/obavestenje}TUplatnica"&amp;gt;
 * &amp;lt;sequence&amp;gt; &amp;lt;element name="troskovi"&amp;gt;
 * &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 * &amp;lt;sequence&amp;gt; &amp;lt;element name="trosak"
 * maxOccurs="unbounded"&amp;gt; &amp;lt;complexType&amp;gt;
 * &amp;lt;complexContent&amp;gt; &amp;lt;restriction
 * base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 * &amp;lt;sequence&amp;gt; &amp;lt;element name="stavka"&amp;gt;
 * &amp;lt;simpleType&amp;gt; &amp;lt;restriction
 * base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt; &amp;lt;enumeration
 * value="CD"/&amp;gt; &amp;lt;enumeration value="A4 papir"/&amp;gt;
 * &amp;lt;enumeration value="A5 papir"/&amp;gt; &amp;lt;enumeration
 * value="USB"/&amp;gt; &amp;lt;enumeration value="Skeniranje"/&amp;gt;
 * &amp;lt;enumeration value="Dostava"/&amp;gt; &amp;lt;/restriction&amp;gt;
 * &amp;lt;/simpleType&amp;gt; &amp;lt;/element&amp;gt; &amp;lt;element
 * name="kolicina"
 * type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&amp;gt;
 * &amp;lt;element name="jedinicna_cijena"&amp;gt; &amp;lt;simpleType&amp;gt;
 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&amp;gt;
 * &amp;lt;fractionDigits value="2"/&amp;gt; &amp;lt;/restriction&amp;gt;
 * &amp;lt;/simpleType&amp;gt; &amp;lt;/element&amp;gt;
 * &amp;lt;/sequence&amp;gt; &amp;lt;/restriction&amp;gt;
 * &amp;lt;/complexContent&amp;gt; &amp;lt;/complexType&amp;gt;
 * &amp;lt;/element&amp;gt; &amp;lt;/sequence&amp;gt;
 * &amp;lt;/restriction&amp;gt; &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt; &amp;lt;/element&amp;gt;
 * &amp;lt;/sequence&amp;gt; &amp;lt;/extension&amp;gt;
 * &amp;lt;/complexContent&amp;gt; &amp;lt;/complexType&amp;gt;
 * &amp;lt;/element&amp;gt; &amp;lt;element name="zahtevi"&amp;gt;
 * &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 * &amp;lt;sequence&amp;gt; &amp;lt;element name="informacije_o_uvidu"
 * minOccurs="0"&amp;gt; &amp;lt;complexType&amp;gt;
 * &amp;lt;complexContent&amp;gt; &amp;lt;restriction
 * base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt; &amp;lt;sequence
 * minOccurs="0"&amp;gt; &amp;lt;element name="datum_uvida"
 * type="{http://www.w3.org/2001/XMLSchema}date"/&amp;gt; &amp;lt;element
 * name="vreme_uvida"&amp;gt; &amp;lt;complexType&amp;gt;
 * &amp;lt;complexContent&amp;gt; &amp;lt;restriction
 * base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 * &amp;lt;choice&amp;gt; &amp;lt;element name="interval_uvida"&amp;gt;
 * &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 * &amp;lt;sequence&amp;gt; &amp;lt;element name="od"&amp;gt;
 * &amp;lt;simpleType&amp;gt; &amp;lt;restriction
 * base="{http://www.w3.org/2001/XMLSchema}positiveInteger"&amp;gt;
 * &amp;lt;minInclusive value="7"/&amp;gt; &amp;lt;maxInclusive
 * value="15"/&amp;gt; &amp;lt;/restriction&amp;gt; &amp;lt;/simpleType&amp;gt;
 * &amp;lt;/element&amp;gt; &amp;lt;element name="do"&amp;gt;
 * &amp;lt;simpleType&amp;gt; &amp;lt;restriction
 * base="{http://www.w3.org/2001/XMLSchema}positiveInteger"&amp;gt;
 * &amp;lt;minInclusive value="7"/&amp;gt; &amp;lt;maxInclusive
 * value="15"/&amp;gt; &amp;lt;/restriction&amp;gt; &amp;lt;/simpleType&amp;gt;
 * &amp;lt;/element&amp;gt; &amp;lt;/sequence&amp;gt;
 * &amp;lt;/restriction&amp;gt; &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt; &amp;lt;/element&amp;gt; &amp;lt;element
 * name="tacno_vreme_uvida"&amp;gt; &amp;lt;simpleType&amp;gt;
 * &amp;lt;restriction
 * base="{http://www.w3.org/2001/XMLSchema}positiveInteger"&amp;gt;
 * &amp;lt;maxInclusive value="15"/&amp;gt; &amp;lt;minInclusive
 * value="7"/&amp;gt; &amp;lt;/restriction&amp;gt; &amp;lt;/simpleType&amp;gt;
 * &amp;lt;/element&amp;gt; &amp;lt;/choice&amp;gt; &amp;lt;/restriction&amp;gt;
 * &amp;lt;/complexContent&amp;gt; &amp;lt;/complexType&amp;gt;
 * &amp;lt;/element&amp;gt; &amp;lt;element name="mesto_uvida"&amp;gt;
 * &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt; &amp;lt;extension
 * base="{http://www.projekat.org/obavestenje}TAdresa"&amp;gt;
 * &amp;lt;sequence&amp;gt; &amp;lt;element name="kancelarija"&amp;gt;
 * &amp;lt;simpleType&amp;gt; &amp;lt;restriction
 * base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt; &amp;lt;minLength
 * value="1"/&amp;gt; &amp;lt;/restriction&amp;gt; &amp;lt;/simpleType&amp;gt;
 * &amp;lt;/element&amp;gt; &amp;lt;/sequence&amp;gt; &amp;lt;/extension&amp;gt;
 * &amp;lt;/complexContent&amp;gt; &amp;lt;/complexType&amp;gt;
 * &amp;lt;/element&amp;gt; &amp;lt;/sequence&amp;gt; &amp;lt;attribute
 * name="status" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean"
 * /&amp;gt; &amp;lt;/restriction&amp;gt; &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt; &amp;lt;/element&amp;gt; &amp;lt;element
 * name="informacije_o_posedovanju" minOccurs="0"&amp;gt;
 * &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 * &amp;lt;attribute name="poseduje"
 * type="{http://www.w3.org/2001/XMLSchema}boolean" /&amp;gt; &amp;lt;attribute
 * name="status" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean"
 * /&amp;gt; &amp;lt;/restriction&amp;gt; &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt; &amp;lt;/element&amp;gt; &amp;lt;element
 * name="informacije_o_izradi_kopije" minOccurs="0"&amp;gt;
 * &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 * &amp;lt;attribute name="status" use="required"
 * type="{http://www.w3.org/2001/XMLSchema}boolean" /&amp;gt;
 * &amp;lt;/restriction&amp;gt; &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt; &amp;lt;/element&amp;gt; &amp;lt;element
 * name="informacije_o_dostavljanju_dokumenta" minOccurs="0"&amp;gt;
 * &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 * &amp;lt;attribute name="status" use="required"
 * type="{http://www.w3.org/2001/XMLSchema}boolean" /&amp;gt;
 * &amp;lt;/restriction&amp;gt; &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt; &amp;lt;/element&amp;gt;
 * &amp;lt;/sequence&amp;gt; &amp;lt;/restriction&amp;gt;
 * &amp;lt;/complexContent&amp;gt; &amp;lt;/complexType&amp;gt;
 * &amp;lt;/element&amp;gt; &amp;lt;/sequence&amp;gt;
 * &amp;lt;/restriction&amp;gt; &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt; &amp;lt;/element&amp;gt; &amp;lt;element
 * name="dostavljeno"&amp;gt; &amp;lt;complexType&amp;gt;
 * &amp;lt;complexContent&amp;gt; &amp;lt;restriction
 * base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 * &amp;lt;sequence&amp;gt; &amp;lt;element name="imenovanom"
 * type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&amp;gt;
 * &amp;lt;element name="arhivi" type="{http://www.w3.org/2001/XMLSchema}string"
 * minOccurs="0"/&amp;gt; &amp;lt;/sequence&amp;gt; &amp;lt;/restriction&amp;gt;
 * &amp;lt;/complexContent&amp;gt; &amp;lt;/complexType&amp;gt;
 * &amp;lt;/element&amp;gt; &amp;lt;/sequence&amp;gt; &amp;lt;attribute
 * name="broj_obavestenja" use="required"&amp;gt; &amp;lt;simpleType&amp;gt;
 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt;
 * &amp;lt;minLength value="1"/&amp;gt; &amp;lt;/restriction&amp;gt;
 * &amp;lt;/simpleType&amp;gt; &amp;lt;/attribute&amp;gt; &amp;lt;attribute
 * name="broj_zahteva" use="required"&amp;gt; &amp;lt;simpleType&amp;gt;
 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt;
 * &amp;lt;minLength value="1"/&amp;gt; &amp;lt;/restriction&amp;gt;
 * &amp;lt;/simpleType&amp;gt; &amp;lt;/attribute&amp;gt;
 * &amp;lt;/restriction&amp;gt; &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt; &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "informacijeOObavestenju", "zahtev", "odgovorNaZahtev", "dostavljeno" })
@XmlRootElement(name = "obavestenje")
public class Obavestenje {

	@XmlElement(name = "informacije_o_obavestenju", required = true)
	protected Obavestenje.InformacijeOObavestenju informacijeOObavestenju;
	@XmlElement(required = true)
	protected Obavestenje.Zahtev zahtev;
	@XmlElement(name = "odgovor_na_zahtev", required = true)
	protected Obavestenje.OdgovorNaZahtev odgovorNaZahtev;
	@XmlElement(required = true)
	protected Obavestenje.Dostavljeno dostavljeno;
	@XmlAttribute(name = "broj_obavestenja", required = false)
	protected String brojObavestenja;
	@XmlAttribute(name = "id_zahteva", required = false)
	protected String brojZahteva;
	@XmlAttribute(name = "id", required = false)
	protected String id;
	@XmlAttribute(name = "vocab", required = false)
	protected String vocab;
	@XmlAttribute(name = "about", required = false)
	protected String about;
	@XmlAttribute(name = "property", required = false)
	protected String property;
	@XmlAttribute(name = "content", required = false)
	protected String content;

	@Override
	public String toString() {
		String obavestenje = String.format("!Dokument obavestenje!\nId obavestenja je: %s.\n", brojObavestenja);
		obavestenje += informacijeOObavestenju.toString();
		obavestenje += zahtev.toString();
		obavestenje += odgovorNaZahtev.toString();
		obavestenje += dostavljeno.toString();
		return obavestenje;
	}

	/**
	 * Gets the value of the informacijeOObavestenju property.
	 * 
	 * @return possible object is {@link Obavestenje.InformacijeOObavestenju }
	 * 
	 */
	public Obavestenje.InformacijeOObavestenju getInformacijeOObavestenju() {
		return informacijeOObavestenju;
	}

	/**
	 * Sets the value of the informacijeOObavestenju property.
	 * 
	 * @param value allowed object is {@link Obavestenje.InformacijeOObavestenju }
	 * 
	 */
	public void setInformacijeOObavestenju(Obavestenje.InformacijeOObavestenju value) {
		this.informacijeOObavestenju = value;
	}

	/**
	 * Gets the value of the zahtev property.
	 * 
	 * @return possible object is {@link Obavestenje.Zahtev }
	 * 
	 */
	public Obavestenje.Zahtev getZahtev() {
		return zahtev;
	}

	/**
	 * Sets the value of the zahtev property.
	 * 
	 * @param value allowed object is {@link Obavestenje.Zahtev }
	 * 
	 */
	public void setZahtev(Obavestenje.Zahtev value) {
		this.zahtev = value;
	}

	/**
	 * Gets the value of the odgovorNaZahtev property.
	 * 
	 * @return possible object is {@link Obavestenje.OdgovorNaZahtev }
	 * 
	 */
	public Obavestenje.OdgovorNaZahtev getOdgovorNaZahtev() {
		return odgovorNaZahtev;
	}

	/**
	 * Sets the value of the odgovorNaZahtev property.
	 * 
	 * @param value allowed object is {@link Obavestenje.OdgovorNaZahtev }
	 * 
	 */
	public void setOdgovorNaZahtev(Obavestenje.OdgovorNaZahtev value) {
		this.odgovorNaZahtev = value;
	}

	/**
	 * Gets the value of the dostavljeno property.
	 * 
	 * @return possible object is {@link Obavestenje.Dostavljeno }
	 * 
	 */
	public Obavestenje.Dostavljeno getDostavljeno() {
		return dostavljeno;
	}

	/**
	 * Sets the value of the dostavljeno property.
	 * 
	 * @param value allowed object is {@link Obavestenje.Dostavljeno }
	 * 
	 */
	public void setDostavljeno(Obavestenje.Dostavljeno value) {
		this.dostavljeno = value;
	}

	/**
	 * Gets the value of the brojObavestenja property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getBrojObavestenja() {
		return brojObavestenja;
	}

	/**
	 * Sets the value of the brojObavestenja property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setBrojObavestenja(String value) {
		this.brojObavestenja = value;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = "http://localhost:4200/obavestenje/" + id;
	}

	public String getVocab() {
		if (vocab == null) {
			return "http://www.projekat.org/predicate";
		} else {
			return vocab;
		}
	}

	/**
	 * Sets the value of the vocab property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setVocab() {
		this.vocab = "http://www.projekat.org/predicate";
	}

	/**
	 * Gets the value of the about property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAbout() {
		return about;
	}

	/**
	 * Sets the value of the about property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setAbout(String value) {
		this.about = "http://localhost:4200/obavestenje/" + value;
	}

	/**
	 * Gets the value of the property property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getProperty() {
		if (property == null) {
			return "pred:zahtev_na_koji_se_odnosi_obavestenje";
		} else {
			return property;
		}
	}

	/**
	 * Sets the value of the property property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setProperty() {
		this.property = "pred:zahtev_na_koji_se_odnosi_obavestenje";
	}

	/**
	 * Gets the value of the datatype property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getContent() {
		return content;
	}

	/**
	 * Sets the value of the datatype property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setContent(String value) {
		this.content = value;
	}

	public String getBrojZahteva() {
		return brojZahteva;
	}

	public void setBrojZahteva(String brojZahteva) {
		this.brojZahteva = brojZahteva;
	}

	/**
	 * &lt;p&gt;Java class for anonymous complex type.
	 * 
	 * &lt;p&gt;The following schema fragment specifies the expected content
	 * contained within this class.
	 * 
	 * &lt;pre&gt; &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
	 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
	 * &amp;lt;sequence&amp;gt; &amp;lt;element name="imenovanom"
	 * type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&amp;gt;
	 * &amp;lt;element name="arhivi" type="{http://www.w3.org/2001/XMLSchema}string"
	 * minOccurs="0"/&amp;gt; &amp;lt;/sequence&amp;gt; &amp;lt;/restriction&amp;gt;
	 * &amp;lt;/complexContent&amp;gt; &amp;lt;/complexType&amp;gt; &lt;/pre&gt;
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "imenovanom", "arhivi" })
	public static class Dostavljeno {

		protected String imenovanom;
		protected String arhivi;

		@Override
		public String toString() {
			return "Dostavljeno:\n\t" + (imenovanom == null ? "" : imenovanom + "\n\t")
					+ (arhivi == null ? "" : arhivi + "\n");

		}

		/**
		 * Gets the value of the imenovanom property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getImenovanom() {
			return imenovanom;
		}

		/**
		 * Sets the value of the imenovanom property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setImenovanom(String value) {
			this.imenovanom = value;
		}

		/**
		 * Gets the value of the arhivi property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getArhivi() {
			return arhivi;
		}

		/**
		 * Sets the value of the arhivi property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setArhivi(String value) {
			this.arhivi = value;
		}

	}

	/**
	 * &lt;p&gt;Java class for anonymous complex type.
	 * 
	 * &lt;p&gt;The following schema fragment specifies the expected content
	 * contained within this class.
	 * 
	 * &lt;pre&gt; &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
	 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
	 * &amp;lt;sequence&amp;gt; &amp;lt;element name="organ"
	 * type="{http://www.projekat.org/obavestenje}TPravno_lice"/&amp;gt;
	 * &amp;lt;element name="trazilac"
	 * type="{http://www.projekat.org/obavestenje}TLice"/&amp;gt; &amp;lt;element
	 * name="datum_obavestenja"
	 * type="{http://www.w3.org/2001/XMLSchema}date"/&amp;gt;
	 * &amp;lt;/sequence&amp;gt; &amp;lt;/restriction&amp;gt;
	 * &amp;lt;/complexContent&amp;gt; &amp;lt;/complexType&amp;gt; &lt;/pre&gt;
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "organ", "trazilac", "datumObavestenja" })
	public static class InformacijeOObavestenju {

		@Override
		public String toString() {
			return "\nOrgan:\n" + organ.toString() + "\nTrazilac informacija:\n" + trazilac.toString()
					+ String.format("\nDatum donosenja obavestenja je: %s.\n", datumObavestenja.toString());
		}

		@XmlElement(required = true)
		protected OrganOdKojegSeTrazi organ;
		@XmlElement(required = true)
		protected Trazilac trazilac;
		@XmlElement(name = "datum_obavestenja", required = true)
		@XmlSchemaType(name = "date")
		protected DatumPodnosenja datumObavestenja;

		/**
		 * Gets the value of the organ property.
		 * 
		 * @return possible object is {@link TPravnoLice }
		 * 
		 */
		public OrganOdKojegSeTrazi getOrgan() {
			return organ;
		}

		/**
		 * Sets the value of the organ property.
		 * 
		 * @param value allowed object is {@link TPravnoLice }
		 * 
		 */
		public void setOrgan(OrganOdKojegSeTrazi value) {
			this.organ = value;
		}

		/**
		 * Gets the value of the trazilac property.
		 * 
		 * @return possible object is {@link TLice }
		 * 
		 */
		public Trazilac getTrazilac() {
			return trazilac;
		}

		/**
		 * Sets the value of the trazilac property.
		 * 
		 * @param value allowed object is {@link TLice }
		 * 
		 */
		public void setTrazilac(Trazilac value) {
			this.trazilac = value;
		}

		/**
		 * Gets the value of the datumObavestenja property.
		 * 
		 * @return possible object is {@link XMLGregorianCalendar }
		 * 
		 */
		public DatumPodnosenja getDatumObavestenja() {
			return datumObavestenja;
		}

		/**
		 * Sets the value of the datumObavestenja property.
		 * 
		 * @param value allowed object is {@link XMLGregorianCalendar }
		 * 
		 */
		public void setDatumObavestenja(DatumPodnosenja value) {
			this.datumObavestenja = value;
		}

	}

	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "")
	public static class OrganOdKojegSeTrazi extends TPravnoLice {

		@XmlAttribute(name = "property", required = false)
		protected String property;
		@XmlAttribute(name = "content", required = false)
		protected String content;

		/**
		 * Gets the value of the property property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getProperty() {
			if (property == null) {
				return "pred:kreator_obavestenja";
			} else {
				return property;
			}
		}

		/**
		 * Sets the value of the property property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setProperty() {
			this.property = "pred:kreator_obavestenja";
		}

		/**
		 * Gets the value of the datatype property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getContent() {
			return content;
		}

		/**
		 * Sets the value of the datatype property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setContent(String value) {
			this.content = value;
		}

	}

	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "value" })
	public static class DatumPodnosenja {

		@XmlValue
		@XmlSchemaType(name = "date")
		protected XMLGregorianCalendar value;
		@XmlAttribute(name = "property", required = false)
		protected String property;
		@XmlAttribute(name = "datatype", required = false)
		protected String datatype;

		/**
		 * Gets the value of the value property.
		 * 
		 * @return possible object is {@link XMLGregorianCalendar }
		 * 
		 */
		public XMLGregorianCalendar getValue() {
			return value;
		}

		/**
		 * Sets the value of the value property.
		 * 
		 * @param value allowed object is {@link XMLGregorianCalendar }
		 * 
		 */
		public void setValue(XMLGregorianCalendar value) {
			this.value = value;
		}

		/**
		 * Gets the value of the property property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getProperty() {
			if (property == null) {
				return "pred:datum_donosenja";
			} else {
				return property;
			}
		}

		/**
		 * Sets the value of the property property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setProperty() {
			this.property = "pred:datum_donosenja";
		}

		/**
		 * Gets the value of the datatype property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getDatatype() {
			if (datatype == null) {
				return "xs:date";
			} else {
				return datatype;
			}
		}

		/**
		 * Sets the value of the datatype property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setDatatype(String value) {
			this.datatype = value;
		}

	}

	/**
	 * &lt;p&gt;Java class for anonymous complex type.
	 * 
	 * &lt;p&gt;The following schema fragment specifies the expected content
	 * contained within this class.
	 * 
	 * &lt;pre&gt; &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
	 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
	 * &amp;lt;sequence&amp;gt; &amp;lt;element name="uplata_troskova"
	 * minOccurs="0"&amp;gt; &amp;lt;complexType&amp;gt;
	 * &amp;lt;complexContent&amp;gt; &amp;lt;extension
	 * base="{http://www.projekat.org/obavestenje}TUplatnica"&amp;gt;
	 * &amp;lt;sequence&amp;gt; &amp;lt;element name="troskovi"&amp;gt;
	 * &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
	 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
	 * &amp;lt;sequence&amp;gt; &amp;lt;element name="trosak"
	 * maxOccurs="unbounded"&amp;gt; &amp;lt;complexType&amp;gt;
	 * &amp;lt;complexContent&amp;gt; &amp;lt;restriction
	 * base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
	 * &amp;lt;sequence&amp;gt; &amp;lt;element name="stavka"&amp;gt;
	 * &amp;lt;simpleType&amp;gt; &amp;lt;restriction
	 * base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt; &amp;lt;enumeration
	 * value="CD"/&amp;gt; &amp;lt;enumeration value="A4 papir"/&amp;gt;
	 * &amp;lt;enumeration value="A5 papir"/&amp;gt; &amp;lt;enumeration
	 * value="USB"/&amp;gt; &amp;lt;enumeration value="Skeniranje"/&amp;gt;
	 * &amp;lt;enumeration value="Dostava"/&amp;gt; &amp;lt;/restriction&amp;gt;
	 * &amp;lt;/simpleType&amp;gt; &amp;lt;/element&amp;gt; &amp;lt;element
	 * name="kolicina"
	 * type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&amp;gt;
	 * &amp;lt;element name="jedinicna_cijena"&amp;gt; &amp;lt;simpleType&amp;gt;
	 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&amp;gt;
	 * &amp;lt;fractionDigits value="2"/&amp;gt; &amp;lt;/restriction&amp;gt;
	 * &amp;lt;/simpleType&amp;gt; &amp;lt;/element&amp;gt;
	 * &amp;lt;/sequence&amp;gt; &amp;lt;/restriction&amp;gt;
	 * &amp;lt;/complexContent&amp;gt; &amp;lt;/complexType&amp;gt;
	 * &amp;lt;/element&amp;gt; &amp;lt;/sequence&amp;gt;
	 * &amp;lt;/restriction&amp;gt; &amp;lt;/complexContent&amp;gt;
	 * &amp;lt;/complexType&amp;gt; &amp;lt;/element&amp;gt;
	 * &amp;lt;/sequence&amp;gt; &amp;lt;/extension&amp;gt;
	 * &amp;lt;/complexContent&amp;gt; &amp;lt;/complexType&amp;gt;
	 * &amp;lt;/element&amp;gt; &amp;lt;element name="zahtevi"&amp;gt;
	 * &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
	 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
	 * &amp;lt;sequence&amp;gt; &amp;lt;element name="informacije_o_uvidu"
	 * minOccurs="0"&amp;gt; &amp;lt;complexType&amp;gt;
	 * &amp;lt;complexContent&amp;gt; &amp;lt;restriction
	 * base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt; &amp;lt;sequence
	 * minOccurs="0"&amp;gt; &amp;lt;element name="datum_uvida"
	 * type="{http://www.w3.org/2001/XMLSchema}date"/&amp;gt; &amp;lt;element
	 * name="vreme_uvida"&amp;gt; &amp;lt;complexType&amp;gt;
	 * &amp;lt;complexContent&amp;gt; &amp;lt;restriction
	 * base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
	 * &amp;lt;choice&amp;gt; &amp;lt;element name="interval_uvida"&amp;gt;
	 * &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
	 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
	 * &amp;lt;sequence&amp;gt; &amp;lt;element name="od"&amp;gt;
	 * &amp;lt;simpleType&amp;gt; &amp;lt;restriction
	 * base="{http://www.w3.org/2001/XMLSchema}positiveInteger"&amp;gt;
	 * &amp;lt;minInclusive value="7"/&amp;gt; &amp;lt;maxInclusive
	 * value="15"/&amp;gt; &amp;lt;/restriction&amp;gt; &amp;lt;/simpleType&amp;gt;
	 * &amp;lt;/element&amp;gt; &amp;lt;element name="do"&amp;gt;
	 * &amp;lt;simpleType&amp;gt; &amp;lt;restriction
	 * base="{http://www.w3.org/2001/XMLSchema}positiveInteger"&amp;gt;
	 * &amp;lt;minInclusive value="7"/&amp;gt; &amp;lt;maxInclusive
	 * value="15"/&amp;gt; &amp;lt;/restriction&amp;gt; &amp;lt;/simpleType&amp;gt;
	 * &amp;lt;/element&amp;gt; &amp;lt;/sequence&amp;gt;
	 * &amp;lt;/restriction&amp;gt; &amp;lt;/complexContent&amp;gt;
	 * &amp;lt;/complexType&amp;gt; &amp;lt;/element&amp;gt; &amp;lt;element
	 * name="tacno_vreme_uvida"&amp;gt; &amp;lt;simpleType&amp;gt;
	 * &amp;lt;restriction
	 * base="{http://www.w3.org/2001/XMLSchema}positiveInteger"&amp;gt;
	 * &amp;lt;maxInclusive value="15"/&amp;gt; &amp;lt;minInclusive
	 * value="7"/&amp;gt; &amp;lt;/restriction&amp;gt; &amp;lt;/simpleType&amp;gt;
	 * &amp;lt;/element&amp;gt; &amp;lt;/choice&amp;gt; &amp;lt;/restriction&amp;gt;
	 * &amp;lt;/complexContent&amp;gt; &amp;lt;/complexType&amp;gt;
	 * &amp;lt;/element&amp;gt; &amp;lt;element name="mesto_uvida"&amp;gt;
	 * &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt; &amp;lt;extension
	 * base="{http://www.projekat.org/obavestenje}TAdresa"&amp;gt;
	 * &amp;lt;sequence&amp;gt; &amp;lt;element name="kancelarija"&amp;gt;
	 * &amp;lt;simpleType&amp;gt; &amp;lt;restriction
	 * base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt; &amp;lt;minLength
	 * value="1"/&amp;gt; &amp;lt;/restriction&amp;gt; &amp;lt;/simpleType&amp;gt;
	 * &amp;lt;/element&amp;gt; &amp;lt;/sequence&amp;gt; &amp;lt;/extension&amp;gt;
	 * &amp;lt;/complexContent&amp;gt; &amp;lt;/complexType&amp;gt;
	 * &amp;lt;/element&amp;gt; &amp;lt;/sequence&amp;gt; &amp;lt;attribute
	 * name="status" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean"
	 * /&amp;gt; &amp;lt;/restriction&amp;gt; &amp;lt;/complexContent&amp;gt;
	 * &amp;lt;/complexType&amp;gt; &amp;lt;/element&amp;gt; &amp;lt;element
	 * name="informacije_o_posedovanju" minOccurs="0"&amp;gt;
	 * &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
	 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
	 * &amp;lt;attribute name="poseduje"
	 * type="{http://www.w3.org/2001/XMLSchema}boolean" /&amp;gt; &amp;lt;attribute
	 * name="status" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean"
	 * /&amp;gt; &amp;lt;/restriction&amp;gt; &amp;lt;/complexContent&amp;gt;
	 * &amp;lt;/complexType&amp;gt; &amp;lt;/element&amp;gt; &amp;lt;element
	 * name="informacije_o_izradi_kopije" minOccurs="0"&amp;gt;
	 * &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
	 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
	 * &amp;lt;attribute name="status" use="required"
	 * type="{http://www.w3.org/2001/XMLSchema}boolean" /&amp;gt;
	 * &amp;lt;/restriction&amp;gt; &amp;lt;/complexContent&amp;gt;
	 * &amp;lt;/complexType&amp;gt; &amp;lt;/element&amp;gt; &amp;lt;element
	 * name="informacije_o_dostavljanju_dokumenta" minOccurs="0"&amp;gt;
	 * &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
	 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
	 * &amp;lt;attribute name="status" use="required"
	 * type="{http://www.w3.org/2001/XMLSchema}boolean" /&amp;gt;
	 * &amp;lt;/restriction&amp;gt; &amp;lt;/complexContent&amp;gt;
	 * &amp;lt;/complexType&amp;gt; &amp;lt;/element&amp;gt;
	 * &amp;lt;/sequence&amp;gt; &amp;lt;/restriction&amp;gt;
	 * &amp;lt;/complexContent&amp;gt; &amp;lt;/complexType&amp;gt;
	 * &amp;lt;/element&amp;gt; &amp;lt;/sequence&amp;gt;
	 * &amp;lt;/restriction&amp;gt; &amp;lt;/complexContent&amp;gt;
	 * &amp;lt;/complexType&amp;gt; &lt;/pre&gt;
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "uplataTroskova", "zahtevi" })
	public static class OdgovorNaZahtev {

		@XmlElement(name = "uplata_troskova")
		protected Obavestenje.OdgovorNaZahtev.UplataTroskova uplataTroskova;
		@XmlElement(required = true)
		protected Obavestenje.OdgovorNaZahtev.Zahtevi zahtevi;

		@Override
		public String toString() {
			return "\nOdgovor na zahtev:\n" + zahtevi.toString() + uplataTroskova.toString();
		}

		/**
		 * Gets the value of the uplataTroskova property.
		 * 
		 * @return possible object is
		 *         {@link Obavestenje.OdgovorNaZahtev.UplataTroskova }
		 * 
		 */
		public Obavestenje.OdgovorNaZahtev.UplataTroskova getUplataTroskova() {
			return uplataTroskova;
		}

		/**
		 * Sets the value of the uplataTroskova property.
		 * 
		 * @param value allowed object is
		 *              {@link Obavestenje.OdgovorNaZahtev.UplataTroskova }
		 * 
		 */
		public void setUplataTroskova(Obavestenje.OdgovorNaZahtev.UplataTroskova value) {
			this.uplataTroskova = value;
		}

		/**
		 * Gets the value of the zahtevi property.
		 * 
		 * @return possible object is {@link Obavestenje.OdgovorNaZahtev.Zahtevi }
		 * 
		 */
		public Obavestenje.OdgovorNaZahtev.Zahtevi getZahtevi() {
			return zahtevi;
		}

		/**
		 * Sets the value of the zahtevi property.
		 * 
		 * @param value allowed object is {@link Obavestenje.OdgovorNaZahtev.Zahtevi }
		 * 
		 */
		public void setZahtevi(Obavestenje.OdgovorNaZahtev.Zahtevi value) {
			this.zahtevi = value;
		}

		/**
		 * &lt;p&gt;Java class for anonymous complex type.
		 * 
		 * &lt;p&gt;The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * &lt;pre&gt; &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
		 * &amp;lt;extension
		 * base="{http://www.projekat.org/obavestenje}TUplatnica"&amp;gt;
		 * &amp;lt;sequence&amp;gt; &amp;lt;element name="troskovi"&amp;gt;
		 * &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
		 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
		 * &amp;lt;sequence&amp;gt; &amp;lt;element name="trosak"
		 * maxOccurs="unbounded"&amp;gt; &amp;lt;complexType&amp;gt;
		 * &amp;lt;complexContent&amp;gt; &amp;lt;restriction
		 * base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
		 * &amp;lt;sequence&amp;gt; &amp;lt;element name="stavka"&amp;gt;
		 * &amp;lt;simpleType&amp;gt; &amp;lt;restriction
		 * base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt; &amp;lt;enumeration
		 * value="CD"/&amp;gt; &amp;lt;enumeration value="A4 papir"/&amp;gt;
		 * &amp;lt;enumeration value="A5 papir"/&amp;gt; &amp;lt;enumeration
		 * value="USB"/&amp;gt; &amp;lt;enumeration value="Skeniranje"/&amp;gt;
		 * &amp;lt;enumeration value="Dostava"/&amp;gt; &amp;lt;/restriction&amp;gt;
		 * &amp;lt;/simpleType&amp;gt; &amp;lt;/element&amp;gt; &amp;lt;element
		 * name="kolicina"
		 * type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&amp;gt;
		 * &amp;lt;element name="jedinicna_cijena"&amp;gt; &amp;lt;simpleType&amp;gt;
		 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&amp;gt;
		 * &amp;lt;fractionDigits value="2"/&amp;gt; &amp;lt;/restriction&amp;gt;
		 * &amp;lt;/simpleType&amp;gt; &amp;lt;/element&amp;gt;
		 * &amp;lt;/sequence&amp;gt; &amp;lt;/restriction&amp;gt;
		 * &amp;lt;/complexContent&amp;gt; &amp;lt;/complexType&amp;gt;
		 * &amp;lt;/element&amp;gt; &amp;lt;/sequence&amp;gt;
		 * &amp;lt;/restriction&amp;gt; &amp;lt;/complexContent&amp;gt;
		 * &amp;lt;/complexType&amp;gt; &amp;lt;/element&amp;gt;
		 * &amp;lt;/sequence&amp;gt; &amp;lt;/extension&amp;gt;
		 * &amp;lt;/complexContent&amp;gt; &amp;lt;/complexType&amp;gt; &lt;/pre&gt;
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "uplatnica", "troskovi" })
		public static class UplataTroskova extends TUplatnica {

			@XmlElement(required = true)
			protected Obavestenje.OdgovorNaZahtev.UplataTroskova.Troskovi troskovi;

			@XmlElement(required = true)
			protected TUplatnica uplatnica;

			@Override
			public String toString() {
				return "\tTroskovi koje je potrebno platiti su:\n" + troskovi.toString() + uplatnica.toString();
			}

			/**
			 * Gets the value of the troskovi property.
			 * 
			 * @return possible object is
			 *         {@link Obavestenje.OdgovorNaZahtev.UplataTroskova.Troskovi }
			 * 
			 */
			public Obavestenje.OdgovorNaZahtev.UplataTroskova.Troskovi getTroskovi() {
				return troskovi;
			}

			/**
			 * Sets the value of the troskovi property.
			 * 
			 * @param value allowed object is
			 *              {@link Obavestenje.OdgovorNaZahtev.UplataTroskova.Troskovi }
			 * 
			 */
			public void setTroskovi(Obavestenje.OdgovorNaZahtev.UplataTroskova.Troskovi value) {
				this.troskovi = value;
			}

			/**
			 * &lt;p&gt;Java class for anonymous complex type.
			 * 
			 * &lt;p&gt;The following schema fragment specifies the expected content
			 * contained within this class.
			 * 
			 * &lt;pre&gt; &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
			 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
			 * &amp;lt;sequence&amp;gt; &amp;lt;element name="trosak"
			 * maxOccurs="unbounded"&amp;gt; &amp;lt;complexType&amp;gt;
			 * &amp;lt;complexContent&amp;gt; &amp;lt;restriction
			 * base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
			 * &amp;lt;sequence&amp;gt; &amp;lt;element name="stavka"&amp;gt;
			 * &amp;lt;simpleType&amp;gt; &amp;lt;restriction
			 * base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt; &amp;lt;enumeration
			 * value="CD"/&amp;gt; &amp;lt;enumeration value="A4 papir"/&amp;gt;
			 * &amp;lt;enumeration value="A5 papir"/&amp;gt; &amp;lt;enumeration
			 * value="USB"/&amp;gt; &amp;lt;enumeration value="Skeniranje"/&amp;gt;
			 * &amp;lt;enumeration value="Dostava"/&amp;gt; &amp;lt;/restriction&amp;gt;
			 * &amp;lt;/simpleType&amp;gt; &amp;lt;/element&amp;gt; &amp;lt;element
			 * name="kolicina"
			 * type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&amp;gt;
			 * &amp;lt;element name="jedinicna_cijena"&amp;gt; &amp;lt;simpleType&amp;gt;
			 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&amp;gt;
			 * &amp;lt;fractionDigits value="2"/&amp;gt; &amp;lt;/restriction&amp;gt;
			 * &amp;lt;/simpleType&amp;gt; &amp;lt;/element&amp;gt;
			 * &amp;lt;/sequence&amp;gt; &amp;lt;/restriction&amp;gt;
			 * &amp;lt;/complexContent&amp;gt; &amp;lt;/complexType&amp;gt;
			 * &amp;lt;/element&amp;gt; &amp;lt;/sequence&amp;gt;
			 * &amp;lt;/restriction&amp;gt; &amp;lt;/complexContent&amp;gt;
			 * &amp;lt;/complexType&amp;gt; &lt;/pre&gt;
			 * 
			 * 
			 */
			@XmlAccessorType(XmlAccessType.FIELD)
			@XmlType(name = "", propOrder = { "trosak" })
			public static class Troskovi {

				@XmlElement(required = true)
				protected List<Obavestenje.OdgovorNaZahtev.UplataTroskova.Troskovi.Trosak> trosak;

				@Override
				public String toString() {
					String troskovi = "\n";
					for (Trosak pojedinacanTrosak : trosak) {
						troskovi += pojedinacanTrosak.toString();
					}
					;
					return troskovi += "\n";
				}

				/**
				 * Gets the value of the trosak property.
				 * 
				 * &lt;p&gt; This accessor method returns a reference to the live list, not a
				 * snapshot. Therefore any modification you make to the returned list will be
				 * present inside the JAXB object. This is why there is not a
				 * &lt;CODE&gt;set&lt;/CODE&gt; method for the trosak property.
				 * 
				 * &lt;p&gt; For example, to add a new item, do as follows: &lt;pre&gt;
				 * getTrosak().add(newItem); &lt;/pre&gt;
				 * 
				 * 
				 * &lt;p&gt; Objects of the following type(s) are allowed in the list
				 * {@link Obavestenje.OdgovorNaZahtev.UplataTroskova.Troskovi.Trosak }
				 * 
				 * 
				 */
				public List<Obavestenje.OdgovorNaZahtev.UplataTroskova.Troskovi.Trosak> getTrosak() {
					if (trosak == null) {
						trosak = new ArrayList<Obavestenje.OdgovorNaZahtev.UplataTroskova.Troskovi.Trosak>();
					}
					return this.trosak;
				}

				/**
				 * &lt;p&gt;Java class for anonymous complex type.
				 * 
				 * &lt;p&gt;The following schema fragment specifies the expected content
				 * contained within this class.
				 * 
				 * &lt;pre&gt; &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
				 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
				 * &amp;lt;sequence&amp;gt; &amp;lt;element name="stavka"&amp;gt;
				 * &amp;lt;simpleType&amp;gt; &amp;lt;restriction
				 * base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt; &amp;lt;enumeration
				 * value="CD"/&amp;gt; &amp;lt;enumeration value="A4 papir"/&amp;gt;
				 * &amp;lt;enumeration value="A5 papir"/&amp;gt; &amp;lt;enumeration
				 * value="USB"/&amp;gt; &amp;lt;enumeration value="Skeniranje"/&amp;gt;
				 * &amp;lt;enumeration value="Dostava"/&amp;gt; &amp;lt;/restriction&amp;gt;
				 * &amp;lt;/simpleType&amp;gt; &amp;lt;/element&amp;gt; &amp;lt;element
				 * name="kolicina"
				 * type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&amp;gt;
				 * &amp;lt;element name="jedinicna_cijena"&amp;gt; &amp;lt;simpleType&amp;gt;
				 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&amp;gt;
				 * &amp;lt;fractionDigits value="2"/&amp;gt; &amp;lt;/restriction&amp;gt;
				 * &amp;lt;/simpleType&amp;gt; &amp;lt;/element&amp;gt;
				 * &amp;lt;/sequence&amp;gt; &amp;lt;/restriction&amp;gt;
				 * &amp;lt;/complexContent&amp;gt; &amp;lt;/complexType&amp;gt; &lt;/pre&gt;
				 * 
				 * 
				 */
				@XmlAccessorType(XmlAccessType.FIELD)
				@XmlType(name = "", propOrder = { "stavka", "kolicina", "jedinicnaCijena" })
				public static class Trosak {

					@XmlElement(required = true)
					protected String stavka;
					@XmlElement(required = true)
					@XmlSchemaType(name = "positiveInteger")
					protected BigInteger kolicina;
					@XmlElement(name = "jedinicna_cijena", required = true)
					protected BigDecimal jedinicnaCijena;

					@Override
					public String toString() {
						return String.format("\t\t%s: %d kom. %.2f dinara po komadu\n", stavka, kolicina,
								jedinicnaCijena);
					}

					/**
					 * Gets the value of the stavka property.
					 * 
					 * @return possible object is {@link String }
					 * 
					 */
					public String getStavka() {
						return stavka;
					}

					/**
					 * Sets the value of the stavka property.
					 * 
					 * @param value allowed object is {@link String }
					 * 
					 */
					public void setStavka(String value) {
						this.stavka = value;
					}

					/**
					 * Gets the value of the kolicina property.
					 * 
					 * @return possible object is {@link BigInteger }
					 * 
					 */
					public BigInteger getKolicina() {
						return kolicina;
					}

					/**
					 * Sets the value of the kolicina property.
					 * 
					 * @param value allowed object is {@link BigInteger }
					 * 
					 */
					public void setKolicina(BigInteger value) {
						this.kolicina = value;
					}

					/**
					 * Gets the value of the jedinicnaCijena property.
					 * 
					 * @return possible object is {@link BigDecimal }
					 * 
					 */
					public BigDecimal getJedinicnaCijena() {
						return jedinicnaCijena;
					}

					/**
					 * Sets the value of the jedinicnaCijena property.
					 * 
					 * @param value allowed object is {@link BigDecimal }
					 * 
					 */
					public void setJedinicnaCijena(BigDecimal value) {
						this.jedinicnaCijena = value;
					}

				}

			}

		}

		/**
		 * &lt;p&gt;Java class for anonymous complex type.
		 * 
		 * &lt;p&gt;The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * &lt;pre&gt; &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
		 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
		 * &amp;lt;sequence&amp;gt; &amp;lt;element name="informacije_o_uvidu"
		 * minOccurs="0"&amp;gt; &amp;lt;complexType&amp;gt;
		 * &amp;lt;complexContent&amp;gt; &amp;lt;restriction
		 * base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt; &amp;lt;sequence
		 * minOccurs="0"&amp;gt; &amp;lt;element name="datum_uvida"
		 * type="{http://www.w3.org/2001/XMLSchema}date"/&amp;gt; &amp;lt;element
		 * name="vreme_uvida"&amp;gt; &amp;lt;complexType&amp;gt;
		 * &amp;lt;complexContent&amp;gt; &amp;lt;restriction
		 * base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
		 * &amp;lt;choice&amp;gt; &amp;lt;element name="interval_uvida"&amp;gt;
		 * &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
		 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
		 * &amp;lt;sequence&amp;gt; &amp;lt;element name="od"&amp;gt;
		 * &amp;lt;simpleType&amp;gt; &amp;lt;restriction
		 * base="{http://www.w3.org/2001/XMLSchema}positiveInteger"&amp;gt;
		 * &amp;lt;minInclusive value="7"/&amp;gt; &amp;lt;maxInclusive
		 * value="15"/&amp;gt; &amp;lt;/restriction&amp;gt; &amp;lt;/simpleType&amp;gt;
		 * &amp;lt;/element&amp;gt; &amp;lt;element name="do"&amp;gt;
		 * &amp;lt;simpleType&amp;gt; &amp;lt;restriction
		 * base="{http://www.w3.org/2001/XMLSchema}positiveInteger"&amp;gt;
		 * &amp;lt;minInclusive value="7"/&amp;gt; &amp;lt;maxInclusive
		 * value="15"/&amp;gt; &amp;lt;/restriction&amp;gt; &amp;lt;/simpleType&amp;gt;
		 * &amp;lt;/element&amp;gt; &amp;lt;/sequence&amp;gt;
		 * &amp;lt;/restriction&amp;gt; &amp;lt;/complexContent&amp;gt;
		 * &amp;lt;/complexType&amp;gt; &amp;lt;/element&amp;gt; &amp;lt;element
		 * name="tacno_vreme_uvida"&amp;gt; &amp;lt;simpleType&amp;gt;
		 * &amp;lt;restriction
		 * base="{http://www.w3.org/2001/XMLSchema}positiveInteger"&amp;gt;
		 * &amp;lt;maxInclusive value="15"/&amp;gt; &amp;lt;minInclusive
		 * value="7"/&amp;gt; &amp;lt;/restriction&amp;gt; &amp;lt;/simpleType&amp;gt;
		 * &amp;lt;/element&amp;gt; &amp;lt;/choice&amp;gt; &amp;lt;/restriction&amp;gt;
		 * &amp;lt;/complexContent&amp;gt; &amp;lt;/complexType&amp;gt;
		 * &amp;lt;/element&amp;gt; &amp;lt;element name="mesto_uvida"&amp;gt;
		 * &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt; &amp;lt;extension
		 * base="{http://www.projekat.org/obavestenje}TAdresa"&amp;gt;
		 * &amp;lt;sequence&amp;gt; &amp;lt;element name="kancelarija"&amp;gt;
		 * &amp;lt;simpleType&amp;gt; &amp;lt;restriction
		 * base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt; &amp;lt;minLength
		 * value="1"/&amp;gt; &amp;lt;/restriction&amp;gt; &amp;lt;/simpleType&amp;gt;
		 * &amp;lt;/element&amp;gt; &amp;lt;/sequence&amp;gt; &amp;lt;/extension&amp;gt;
		 * &amp;lt;/complexContent&amp;gt; &amp;lt;/complexType&amp;gt;
		 * &amp;lt;/element&amp;gt; &amp;lt;/sequence&amp;gt; &amp;lt;attribute
		 * name="status" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean"
		 * /&amp;gt; &amp;lt;/restriction&amp;gt; &amp;lt;/complexContent&amp;gt;
		 * &amp;lt;/complexType&amp;gt; &amp;lt;/element&amp;gt; &amp;lt;element
		 * name="informacije_o_posedovanju" minOccurs="0"&amp;gt;
		 * &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
		 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
		 * &amp;lt;attribute name="poseduje"
		 * type="{http://www.w3.org/2001/XMLSchema}boolean" /&amp;gt; &amp;lt;attribute
		 * name="status" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean"
		 * /&amp;gt; &amp;lt;/restriction&amp;gt; &amp;lt;/complexContent&amp;gt;
		 * &amp;lt;/complexType&amp;gt; &amp;lt;/element&amp;gt; &amp;lt;element
		 * name="informacije_o_izradi_kopije" minOccurs="0"&amp;gt;
		 * &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
		 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
		 * &amp;lt;attribute name="status" use="required"
		 * type="{http://www.w3.org/2001/XMLSchema}boolean" /&amp;gt;
		 * &amp;lt;/restriction&amp;gt; &amp;lt;/complexContent&amp;gt;
		 * &amp;lt;/complexType&amp;gt; &amp;lt;/element&amp;gt; &amp;lt;element
		 * name="informacije_o_dostavljanju_dokumenta" minOccurs="0"&amp;gt;
		 * &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
		 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
		 * &amp;lt;attribute name="status" use="required"
		 * type="{http://www.w3.org/2001/XMLSchema}boolean" /&amp;gt;
		 * &amp;lt;/restriction&amp;gt; &amp;lt;/complexContent&amp;gt;
		 * &amp;lt;/complexType&amp;gt; &amp;lt;/element&amp;gt;
		 * &amp;lt;/sequence&amp;gt; &amp;lt;/restriction&amp;gt;
		 * &amp;lt;/complexContent&amp;gt; &amp;lt;/complexType&amp;gt; &lt;/pre&gt;
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "informacijeOUvidu", "informacijeOPosedovanju", "informacijeOIzradiKopije",
				"informacijeODostavljanjuDokumenta" })
		public static class Zahtevi {

			@XmlElement(name = "informacije_o_uvidu")
			protected Obavestenje.OdgovorNaZahtev.Zahtevi.InformacijeOUvidu informacijeOUvidu;
			@XmlElement(name = "informacije_o_posedovanju")
			protected Obavestenje.OdgovorNaZahtev.Zahtevi.InformacijeOPosedovanju informacijeOPosedovanju;
			@XmlElement(name = "informacije_o_izradi_kopije")
			protected Obavestenje.OdgovorNaZahtev.Zahtevi.InformacijeOIzradiKopije informacijeOIzradiKopije;
			@XmlElement(name = "informacije_o_dostavljanju_dokumenta")
			protected Obavestenje.OdgovorNaZahtev.Zahtevi.InformacijeODostavljanjuDokumenta informacijeODostavljanjuDokumenta;

			@Override
			public String toString() {
				String obavestenje = "\t";
				if (informacijeOUvidu != null) {
					obavestenje += informacijeOUvidu.toString();
				}
				if (informacijeOIzradiKopije != null) {
					obavestenje += "\t" + informacijeOIzradiKopije.toString();
				}
				if (informacijeOPosedovanju != null) {
					obavestenje += "\t" + informacijeOPosedovanju.toString();
				}
				if (informacijeODostavljanjuDokumenta != null) {
					obavestenje += "\t" + informacijeODostavljanjuDokumenta.toString();
				}
				;
				return obavestenje;
			}

			/**
			 * Gets the value of the informacijeOUvidu property.
			 * 
			 * @return possible object is
			 *         {@link Obavestenje.OdgovorNaZahtev.Zahtevi.InformacijeOUvidu }
			 * 
			 */
			public Obavestenje.OdgovorNaZahtev.Zahtevi.InformacijeOUvidu getInformacijeOUvidu() {
				return informacijeOUvidu;
			}

			/**
			 * Sets the value of the informacijeOUvidu property.
			 * 
			 * @param value allowed object is
			 *              {@link Obavestenje.OdgovorNaZahtev.Zahtevi.InformacijeOUvidu }
			 * 
			 */
			public void setInformacijeOUvidu(Obavestenje.OdgovorNaZahtev.Zahtevi.InformacijeOUvidu value) {
				this.informacijeOUvidu = value;
			}

			/**
			 * Gets the value of the informacijeOPosedovanju property.
			 * 
			 * @return possible object is
			 *         {@link Obavestenje.OdgovorNaZahtev.Zahtevi.InformacijeOPosedovanju }
			 * 
			 */
			public Obavestenje.OdgovorNaZahtev.Zahtevi.InformacijeOPosedovanju getInformacijeOPosedovanju() {
				return informacijeOPosedovanju;
			}

			/**
			 * Sets the value of the informacijeOPosedovanju property.
			 * 
			 * @param value allowed object is
			 *              {@link Obavestenje.OdgovorNaZahtev.Zahtevi.InformacijeOPosedovanju }
			 * 
			 */
			public void setInformacijeOPosedovanju(Obavestenje.OdgovorNaZahtev.Zahtevi.InformacijeOPosedovanju value) {
				this.informacijeOPosedovanju = value;
			}

			/**
			 * Gets the value of the informacijeOIzradiKopije property.
			 * 
			 * @return possible object is
			 *         {@link Obavestenje.OdgovorNaZahtev.Zahtevi.InformacijeOIzradiKopije }
			 * 
			 */
			public Obavestenje.OdgovorNaZahtev.Zahtevi.InformacijeOIzradiKopije getInformacijeOIzradiKopije() {
				return informacijeOIzradiKopije;
			}

			/**
			 * Sets the value of the informacijeOIzradiKopije property.
			 * 
			 * @param value allowed object is
			 *              {@link Obavestenje.OdgovorNaZahtev.Zahtevi.InformacijeOIzradiKopije }
			 * 
			 */
			public void setInformacijeOIzradiKopije(
					Obavestenje.OdgovorNaZahtev.Zahtevi.InformacijeOIzradiKopije value) {
				this.informacijeOIzradiKopije = value;
			}

			/**
			 * Gets the value of the informacijeODostavljanjuDokumenta property.
			 * 
			 * @return possible object is
			 *         {@link Obavestenje.OdgovorNaZahtev.Zahtevi.InformacijeODostavljanjuDokumenta }
			 * 
			 */
			public Obavestenje.OdgovorNaZahtev.Zahtevi.InformacijeODostavljanjuDokumenta getInformacijeODostavljanjuDokumenta() {
				return informacijeODostavljanjuDokumenta;
			}

			/**
			 * Sets the value of the informacijeODostavljanjuDokumenta property.
			 * 
			 * @param value allowed object is
			 *              {@link Obavestenje.OdgovorNaZahtev.Zahtevi.InformacijeODostavljanjuDokumenta }
			 * 
			 */
			public void setInformacijeODostavljanjuDokumenta(
					Obavestenje.OdgovorNaZahtev.Zahtevi.InformacijeODostavljanjuDokumenta value) {
				this.informacijeODostavljanjuDokumenta = value;
			}

			/**
			 * &lt;p&gt;Java class for anonymous complex type.
			 * 
			 * &lt;p&gt;The following schema fragment specifies the expected content
			 * contained within this class.
			 * 
			 * &lt;pre&gt; &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
			 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
			 * &amp;lt;attribute name="status" use="required"
			 * type="{http://www.w3.org/2001/XMLSchema}boolean" /&amp;gt;
			 * &amp;lt;/restriction&amp;gt; &amp;lt;/complexContent&amp;gt;
			 * &amp;lt;/complexType&amp;gt; &lt;/pre&gt;
			 * 
			 * 
			 */
			@XmlAccessorType(XmlAccessType.FIELD)
			@XmlType(name = "")
			public static class InformacijeODostavljanjuDokumenta {

				@Override
				public String toString() {
					return "Zahtev za dostavljanje trazenih dokumenata je prihvacen.\n"
							+ "\t\tPotrebno je platiti troskove dostavljanja.\n\n";
				}
			}

			/**
			 * &lt;p&gt;Java class for anonymous complex type.
			 * 
			 * &lt;p&gt;The following schema fragment specifies the expected content
			 * contained within this class.
			 * 
			 * &lt;pre&gt; &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
			 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
			 * &amp;lt;attribute name="status" use="required"
			 * type="{http://www.w3.org/2001/XMLSchema}boolean" /&amp;gt;
			 * &amp;lt;/restriction&amp;gt; &amp;lt;/complexContent&amp;gt;
			 * &amp;lt;/complexType&amp;gt; &lt;/pre&gt;
			 * 
			 * 
			 */
			@XmlAccessorType(XmlAccessType.FIELD)
			@XmlType(name = "")
			public static class InformacijeOIzradiKopije {

				@Override
				public String toString() {
					return "Zahtev za izradom kopija trazenih dokumenata je prihvacen.\n"
							+ "\tPotrebno je platiti troskove kopiranja dokumenata.\n\n";
				}

			}

			/**
			 * &lt;p&gt;Java class for anonymous complex type.
			 * 
			 * &lt;p&gt;The following schema fragment specifies the expected content
			 * contained within this class.
			 * 
			 * &lt;pre&gt; &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
			 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
			 * &amp;lt;attribute name="poseduje"
			 * type="{http://www.w3.org/2001/XMLSchema}boolean" /&amp;gt; &amp;lt;attribute
			 * name="status" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean"
			 * /&amp;gt; &amp;lt;/restriction&amp;gt; &amp;lt;/complexContent&amp;gt;
			 * &amp;lt;/complexType&amp;gt; &lt;/pre&gt;
			 * 
			 * 
			 */
			@XmlAccessorType(XmlAccessType.FIELD)
			@XmlType(name = "")
			public static class InformacijeOPosedovanju {

				@XmlAttribute(name = "poseduje", required = true)
				protected Boolean poseduje;

				@Override
				public String toString() {
					String zahtev = "Zahtev za dobijanje informacije o posedovanju trazenog dokumenta kod navedenog organa je prihvacen.\n";
					if (poseduje) {
						zahtev += "\t\tNavedeni organ poseduje trazenu informaciju.\n\n";
					} else {
						zahtev += "\t\tNavedeni organ ne poseduje trazenu informaciju.\n\n";
					}
					return zahtev;
				}

				/**
				 * Gets the value of the poseduje property.
				 * 
				 * @return possible object is {@link Boolean }
				 * 
				 */
				public Boolean isPoseduje() {
					return poseduje;
				}

				/**
				 * Sets the value of the poseduje property.
				 * 
				 * @param value allowed object is {@link Boolean }
				 * 
				 */
				public void setPoseduje(Boolean value) {
					this.poseduje = value;
				}

			}

			/**
			 * &lt;p&gt;Java class for anonymous complex type.
			 * 
			 * &lt;p&gt;The following schema fragment specifies the expected content
			 * contained within this class.
			 * 
			 * &lt;pre&gt; &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
			 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
			 * &amp;lt;sequence minOccurs="0"&amp;gt; &amp;lt;element name="datum_uvida"
			 * type="{http://www.w3.org/2001/XMLSchema}date"/&amp;gt; &amp;lt;element
			 * name="vreme_uvida"&amp;gt; &amp;lt;complexType&amp;gt;
			 * &amp;lt;complexContent&amp;gt; &amp;lt;restriction
			 * base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
			 * &amp;lt;choice&amp;gt; &amp;lt;element name="interval_uvida"&amp;gt;
			 * &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
			 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
			 * &amp;lt;sequence&amp;gt; &amp;lt;element name="od"&amp;gt;
			 * &amp;lt;simpleType&amp;gt; &amp;lt;restriction
			 * base="{http://www.w3.org/2001/XMLSchema}positiveInteger"&amp;gt;
			 * &amp;lt;minInclusive value="7"/&amp;gt; &amp;lt;maxInclusive
			 * value="15"/&amp;gt; &amp;lt;/restriction&amp;gt; &amp;lt;/simpleType&amp;gt;
			 * &amp;lt;/element&amp;gt; &amp;lt;element name="do"&amp;gt;
			 * &amp;lt;simpleType&amp;gt; &amp;lt;restriction
			 * base="{http://www.w3.org/2001/XMLSchema}positiveInteger"&amp;gt;
			 * &amp;lt;minInclusive value="7"/&amp;gt; &amp;lt;maxInclusive
			 * value="15"/&amp;gt; &amp;lt;/restriction&amp;gt; &amp;lt;/simpleType&amp;gt;
			 * &amp;lt;/element&amp;gt; &amp;lt;/sequence&amp;gt;
			 * &amp;lt;/restriction&amp;gt; &amp;lt;/complexContent&amp;gt;
			 * &amp;lt;/complexType&amp;gt; &amp;lt;/element&amp;gt; &amp;lt;element
			 * name="tacno_vreme_uvida"&amp;gt; &amp;lt;simpleType&amp;gt;
			 * &amp;lt;restriction
			 * base="{http://www.w3.org/2001/XMLSchema}positiveInteger"&amp;gt;
			 * &amp;lt;maxInclusive value="15"/&amp;gt; &amp;lt;minInclusive
			 * value="7"/&amp;gt; &amp;lt;/restriction&amp;gt; &amp;lt;/simpleType&amp;gt;
			 * &amp;lt;/element&amp;gt; &amp;lt;/choice&amp;gt; &amp;lt;/restriction&amp;gt;
			 * &amp;lt;/complexContent&amp;gt; &amp;lt;/complexType&amp;gt;
			 * &amp;lt;/element&amp;gt; &amp;lt;element name="mesto_uvida"&amp;gt;
			 * &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt; &amp;lt;extension
			 * base="{http://www.projekat.org/obavestenje}TAdresa"&amp;gt;
			 * &amp;lt;sequence&amp;gt; &amp;lt;element name="kancelarija"&amp;gt;
			 * &amp;lt;simpleType&amp;gt; &amp;lt;restriction
			 * base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt; &amp;lt;minLength
			 * value="1"/&amp;gt; &amp;lt;/restriction&amp;gt; &amp;lt;/simpleType&amp;gt;
			 * &amp;lt;/element&amp;gt; &amp;lt;/sequence&amp;gt; &amp;lt;/extension&amp;gt;
			 * &amp;lt;/complexContent&amp;gt; &amp;lt;/complexType&amp;gt;
			 * &amp;lt;/element&amp;gt; &amp;lt;/sequence&amp;gt; &amp;lt;attribute
			 * name="status" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean"
			 * /&amp;gt; &amp;lt;/restriction&amp;gt; &amp;lt;/complexContent&amp;gt;
			 * &amp;lt;/complexType&amp;gt; &lt;/pre&gt;
			 * 
			 * 
			 */
			@XmlAccessorType(XmlAccessType.FIELD)
			@XmlType(name = "", propOrder = { "datumUvida", "vremeUvida", "mestoUvida" })
			public static class InformacijeOUvidu {

				@XmlElement(name = "datum_uvida")
				@XmlSchemaType(name = "date")
				protected XMLGregorianCalendar datumUvida;
				@XmlElement(name = "vreme_uvida")
				protected Obavestenje.OdgovorNaZahtev.Zahtevi.InformacijeOUvidu.VremeUvida vremeUvida;
				@XmlElement(name = "mesto_uvida")
				protected Obavestenje.OdgovorNaZahtev.Zahtevi.InformacijeOUvidu.MestoUvida mestoUvida;

				@Override
				public String toString() {
					return String.format("Zahtev za uvid u trazene informacije je prihvacen.\n\t\tDatum uvida: %s\n\t"
							+ vremeUvida.toString() + mestoUvida.toString() + "\n", datumUvida);
				}

				/**
				 * Gets the value of the datumUvida property.
				 * 
				 * @return possible object is {@link XMLGregorianCalendar }
				 * 
				 */
				public XMLGregorianCalendar getDatumUvida() {
					return datumUvida;
				}

				/**
				 * Sets the value of the datumUvida property.
				 * 
				 * @param value allowed object is {@link XMLGregorianCalendar }
				 * 
				 */
				public void setDatumUvida(XMLGregorianCalendar value) {
					this.datumUvida = value;
				}

				/**
				 * Gets the value of the vremeUvida property.
				 * 
				 * @return possible object is
				 *         {@link Obavestenje.OdgovorNaZahtev.Zahtevi.InformacijeOUvidu.VremeUvida }
				 * 
				 */
				public Obavestenje.OdgovorNaZahtev.Zahtevi.InformacijeOUvidu.VremeUvida getVremeUvida() {
					return vremeUvida;
				}

				/**
				 * Sets the value of the vremeUvida property.
				 * 
				 * @param value allowed object is
				 *              {@link Obavestenje.OdgovorNaZahtev.Zahtevi.InformacijeOUvidu.VremeUvida }
				 * 
				 */
				public void setVremeUvida(Obavestenje.OdgovorNaZahtev.Zahtevi.InformacijeOUvidu.VremeUvida value) {
					this.vremeUvida = value;
				}

				/**
				 * Gets the value of the mestoUvida property.
				 * 
				 * @return possible object is
				 *         {@link Obavestenje.OdgovorNaZahtev.Zahtevi.InformacijeOUvidu.MestoUvida }
				 * 
				 */
				public Obavestenje.OdgovorNaZahtev.Zahtevi.InformacijeOUvidu.MestoUvida getMestoUvida() {
					return mestoUvida;
				}

				/**
				 * Sets the value of the mestoUvida property.
				 * 
				 * @param value allowed object is
				 *              {@link Obavestenje.OdgovorNaZahtev.Zahtevi.InformacijeOUvidu.MestoUvida }
				 * 
				 */
				public void setMestoUvida(Obavestenje.OdgovorNaZahtev.Zahtevi.InformacijeOUvidu.MestoUvida value) {
					this.mestoUvida = value;
				}

				/**
				 * &lt;p&gt;Java class for anonymous complex type.
				 * 
				 * &lt;p&gt;The following schema fragment specifies the expected content
				 * contained within this class.
				 * 
				 * &lt;pre&gt; &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
				 * &amp;lt;extension base="{http://www.projekat.org/obavestenje}TAdresa"&amp;gt;
				 * &amp;lt;sequence&amp;gt; &amp;lt;element name="kancelarija"&amp;gt;
				 * &amp;lt;simpleType&amp;gt; &amp;lt;restriction
				 * base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt; &amp;lt;minLength
				 * value="1"/&amp;gt; &amp;lt;/restriction&amp;gt; &amp;lt;/simpleType&amp;gt;
				 * &amp;lt;/element&amp;gt; &amp;lt;/sequence&amp;gt; &amp;lt;/extension&amp;gt;
				 * &amp;lt;/complexContent&amp;gt; &amp;lt;/complexType&amp;gt; &lt;/pre&gt;
				 * 
				 * 
				 */
				@XmlAccessorType(XmlAccessType.FIELD)
				@XmlType(name = "", propOrder = { "kancelarija" })
				public static class MestoUvida extends TAdresa {

					@XmlElement(required = true)
					protected String kancelarija;

					@Override
					public String toString() {
						return super.toString() + String.format("\t\tKancelarija: %s\n", kancelarija);
					}

					/**
					 * Gets the value of the kancelarija property.
					 * 
					 * @return possible object is {@link String }
					 * 
					 */
					public String getKancelarija() {
						return kancelarija;
					}

					/**
					 * Sets the value of the kancelarija property.
					 * 
					 * @param value allowed object is {@link String }
					 * 
					 */
					public void setKancelarija(String value) {
						this.kancelarija = value;
					}

				}

				/**
				 * &lt;p&gt;Java class for anonymous complex type.
				 * 
				 * &lt;p&gt;The following schema fragment specifies the expected content
				 * contained within this class.
				 * 
				 * &lt;pre&gt; &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
				 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
				 * &amp;lt;choice&amp;gt; &amp;lt;element name="interval_uvida"&amp;gt;
				 * &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
				 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
				 * &amp;lt;sequence&amp;gt; &amp;lt;element name="od"&amp;gt;
				 * &amp;lt;simpleType&amp;gt; &amp;lt;restriction
				 * base="{http://www.w3.org/2001/XMLSchema}positiveInteger"&amp;gt;
				 * &amp;lt;minInclusive value="7"/&amp;gt; &amp;lt;maxInclusive
				 * value="15"/&amp;gt; &amp;lt;/restriction&amp;gt; &amp;lt;/simpleType&amp;gt;
				 * &amp;lt;/element&amp;gt; &amp;lt;element name="do"&amp;gt;
				 * &amp;lt;simpleType&amp;gt; &amp;lt;restriction
				 * base="{http://www.w3.org/2001/XMLSchema}positiveInteger"&amp;gt;
				 * &amp;lt;minInclusive value="7"/&amp;gt; &amp;lt;maxInclusive
				 * value="15"/&amp;gt; &amp;lt;/restriction&amp;gt; &amp;lt;/simpleType&amp;gt;
				 * &amp;lt;/element&amp;gt; &amp;lt;/sequence&amp;gt;
				 * &amp;lt;/restriction&amp;gt; &amp;lt;/complexContent&amp;gt;
				 * &amp;lt;/complexType&amp;gt; &amp;lt;/element&amp;gt; &amp;lt;element
				 * name="tacno_vreme_uvida"&amp;gt; &amp;lt;simpleType&amp;gt;
				 * &amp;lt;restriction
				 * base="{http://www.w3.org/2001/XMLSchema}positiveInteger"&amp;gt;
				 * &amp;lt;maxInclusive value="15"/&amp;gt; &amp;lt;minInclusive
				 * value="7"/&amp;gt; &amp;lt;/restriction&amp;gt; &amp;lt;/simpleType&amp;gt;
				 * &amp;lt;/element&amp;gt; &amp;lt;/choice&amp;gt; &amp;lt;/restriction&amp;gt;
				 * &amp;lt;/complexContent&amp;gt; &amp;lt;/complexType&amp;gt; &lt;/pre&gt;
				 * 
				 * 
				 */
				@XmlAccessorType(XmlAccessType.FIELD)
				@XmlType(name = "", propOrder = { "intervalUvida", "tacnoVremeUvida" })
				public static class VremeUvida {

					@XmlElement(name = "interval_uvida")
					protected Obavestenje.OdgovorNaZahtev.Zahtevi.InformacijeOUvidu.VremeUvida.IntervalUvida intervalUvida;
					@XmlElement(name = "tacno_vreme_uvida")
					protected Integer tacnoVremeUvida;

					@Override
					public String toString() {
						if (intervalUvida != null) {
							return "\tVreme uvida: " + intervalUvida.toString();
						} else {
							return String.format("Vreme uvida u %dh.\n", tacnoVremeUvida);
						}
					}

					/**
					 * Gets the value of the intervalUvida property.
					 * 
					 * @return possible object is
					 *         {@link Obavestenje.OdgovorNaZahtev.Zahtevi.InformacijeOUvidu.VremeUvida.IntervalUvida }
					 * 
					 */
					public Obavestenje.OdgovorNaZahtev.Zahtevi.InformacijeOUvidu.VremeUvida.IntervalUvida getIntervalUvida() {
						return intervalUvida;
					}

					/**
					 * Sets the value of the intervalUvida property.
					 * 
					 * @param value allowed object is
					 *              {@link Obavestenje.OdgovorNaZahtev.Zahtevi.InformacijeOUvidu.VremeUvida.IntervalUvida }
					 * 
					 */
					public void setIntervalUvida(
							Obavestenje.OdgovorNaZahtev.Zahtevi.InformacijeOUvidu.VremeUvida.IntervalUvida value) {
						this.intervalUvida = value;
					}

					/**
					 * Gets the value of the tacnoVremeUvida property.
					 * 
					 * @return possible object is {@link Integer }
					 * 
					 */
					public Integer getTacnoVremeUvida() {
						return tacnoVremeUvida;
					}

					/**
					 * Sets the value of the tacnoVremeUvida property.
					 * 
					 * @param value allowed object is {@link Integer }
					 * 
					 */
					public void setTacnoVremeUvida(Integer value) {
						this.tacnoVremeUvida = value;
					}

					/**
					 * &lt;p&gt;Java class for anonymous complex type.
					 * 
					 * &lt;p&gt;The following schema fragment specifies the expected content
					 * contained within this class.
					 * 
					 * &lt;pre&gt; &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
					 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
					 * &amp;lt;sequence&amp;gt; &amp;lt;element name="od"&amp;gt;
					 * &amp;lt;simpleType&amp;gt; &amp;lt;restriction
					 * base="{http://www.w3.org/2001/XMLSchema}positiveInteger"&amp;gt;
					 * &amp;lt;minInclusive value="7"/&amp;gt; &amp;lt;maxInclusive
					 * value="15"/&amp;gt; &amp;lt;/restriction&amp;gt; &amp;lt;/simpleType&amp;gt;
					 * &amp;lt;/element&amp;gt; &amp;lt;element name="do"&amp;gt;
					 * &amp;lt;simpleType&amp;gt; &amp;lt;restriction
					 * base="{http://www.w3.org/2001/XMLSchema}positiveInteger"&amp;gt;
					 * &amp;lt;minInclusive value="7"/&amp;gt; &amp;lt;maxInclusive
					 * value="15"/&amp;gt; &amp;lt;/restriction&amp;gt; &amp;lt;/simpleType&amp;gt;
					 * &amp;lt;/element&amp;gt; &amp;lt;/sequence&amp;gt;
					 * &amp;lt;/restriction&amp;gt; &amp;lt;/complexContent&amp;gt;
					 * &amp;lt;/complexType&amp;gt; &lt;/pre&gt;
					 * 
					 * 
					 */
					@XmlAccessorType(XmlAccessType.FIELD)
					@XmlType(name = "", propOrder = { "od", "_do" })
					public static class IntervalUvida {

						protected int od;
						@XmlElement(name = "do")
						protected int _do;

						@Override
						public String toString() {
							return String.format("od %dh do %dh\n", od, _do);
						}

						/**
						 * Gets the value of the od property.
						 * 
						 */
						public int getOd() {
							return od;
						}

						/**
						 * Sets the value of the od property.
						 * 
						 */
						public void setOd(int value) {
							this.od = value;
						}

						/**
						 * Gets the value of the do property.
						 * 
						 */
						public int getDo() {
							return _do;
						}

						/**
						 * Sets the value of the do property.
						 * 
						 */
						public void setDo(int value) {
							this._do = value;
						}

					}

				}

			}

		}

	}

	/**
	 * &lt;p&gt;Java class for anonymous complex type.
	 * 
	 * &lt;p&gt;The following schema fragment specifies the expected content
	 * contained within this class.
	 * 
	 * &lt;pre&gt; &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
	 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
	 * &amp;lt;sequence&amp;gt; &amp;lt;element name="datum_trazenja_informacija"
	 * type="{http://www.w3.org/2001/XMLSchema}date"/&amp;gt; &amp;lt;element
	 * name="opis_trazene_informacije"&amp;gt; &amp;lt;simpleType&amp;gt;
	 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt;
	 * &amp;lt;minLength value="1"/&amp;gt; &amp;lt;/restriction&amp;gt;
	 * &amp;lt;/simpleType&amp;gt; &amp;lt;/element&amp;gt;
	 * &amp;lt;/sequence&amp;gt; &amp;lt;/restriction&amp;gt;
	 * &amp;lt;/complexContent&amp;gt; &amp;lt;/complexType&amp;gt; &lt;/pre&gt;
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "datumTrazenjaInformacija", "opisTrazeneInformacije" })
	public static class Zahtev {

		@XmlElement(name = "datum_trazenja_informacija", required = true)
		@XmlSchemaType(name = "date")
		protected XMLGregorianCalendar datumTrazenjaInformacija;
		@XmlElement(name = "opis_trazene_informacije", required = true)
		protected String opisTrazeneInformacije;

		@Override
		public String toString() {
			return String.format(
					"\nInformacije o zahtevu:\n\tDatum podnosenja zahteva: %s.\n\tOpis trazene informacije: %s\n",
					datumTrazenjaInformacija, opisTrazeneInformacije);
		}

		/**
		 * Gets the value of the datumTrazenjaInformacija property.
		 * 
		 * @return possible object is {@link XMLGregorianCalendar }
		 * 
		 */
		public XMLGregorianCalendar getDatumTrazenjaInformacija() {
			return datumTrazenjaInformacija;
		}

		/**
		 * Sets the value of the datumTrazenjaInformacija property.
		 * 
		 * @param value allowed object is {@link XMLGregorianCalendar }
		 * 
		 */
		public void setDatumTrazenjaInformacija(XMLGregorianCalendar value) {
			this.datumTrazenjaInformacija = value;
		}

		/**
		 * Gets the value of the opisTrazeneInformacije property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getOpisTrazeneInformacije() {
			return opisTrazeneInformacije;
		}

		/**
		 * Sets the value of the opisTrazeneInformacije property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setOpisTrazeneInformacije(String value) {
			this.opisTrazeneInformacije = value;
		}

	}

	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "lice" })
	public static class Trazilac {

		@XmlElement(required = true)
		protected TLice lice;
		@XmlAttribute(name = "property", required = false)
		protected String property;
		@XmlAttribute(name = "content", required = false)
		protected String content;

		public String getProperty() {
			if (property == null) {
				return "pred:trazilac_informacija";
			} else {
				return property;
			}
		}

		/**
		 * Gets the value of the lice property.
		 * 
		 * @return possible object is {@link TLice }
		 * 
		 */
		public TLice getLice() {
			return lice;
		}

		/**
		 * Sets the value of the lice property.
		 * 
		 * @param value allowed object is {@link TLice }
		 * 
		 */
		public void setLice(TLice value) {
			this.lice = value;
		}

		/**
		 * Sets the value of the property property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setProperty() {
			this.property = "pred:trazilac_informacija";
		}

		/**
		 * Gets the value of the resource property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getContent() {
			return content;
		}

		/**
		 * Sets the value of the resource property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setContent(String value) {
			this.content = value;
		}

		public Trazilac() {
			super();
		}

	}

}
