//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.07 at 12:29:30 AM CET 
//


package projectXML.team9.models.zalbaNaOdluku;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gen3 package. 
 * &lt;p&gt;An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gen3
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ZalbaNaOdluku }
     * 
     */
    public ZalbaNaOdluku createZalbaNaOdluku() {
        return new ZalbaNaOdluku();
    }

    /**
     * Create an instance of {@link ZalbaNaOdluku.PodaciOZalbi }
     * 
     */
    public ZalbaNaOdluku.PodaciOZalbi createZalbaNaOdlukuPodaciOZalbi() {
        return new ZalbaNaOdluku.PodaciOZalbi();
    }

    /**
     * Create an instance of {@link TAdresa }
     * 
     */
    public TAdresa createTAdresa() {
        return new TAdresa();
    }

    /**
     * Create an instance of {@link ZalbaNaOdluku.Zalilac }
     * 
     */
    public ZalbaNaOdluku.Zalilac createZalbaNaOdlukuZalilac() {
        return new ZalbaNaOdluku.Zalilac();
    }

    /**
     * Create an instance of {@link ZalbaNaOdluku.PodaciOResenju }
     * 
     */
    public ZalbaNaOdluku.PodaciOResenju createZalbaNaOdlukuPodaciOResenju() {
        return new ZalbaNaOdluku.PodaciOResenju();
    }

    /**
     * Create an instance of {@link TPravnoLice }
     * 
     */
    public TPravnoLice createTPravnoLice() {
        return new TPravnoLice();
    }

    /**
     * Create an instance of {@link TFizickoLice }
     * 
     */
    public TFizickoLice createTFizickoLice() {
        return new TFizickoLice();
    }

    /**
     * Create an instance of {@link ZalbaNaOdluku.PodaciOZalbi.PodnosilacZalbe }
     * 
     */
    public ZalbaNaOdluku.PodaciOZalbi.PodnosilacZalbe createZalbaNaOdlukuPodaciOZalbiPodnosilacZalbe() {
        return new ZalbaNaOdluku.PodaciOZalbi.PodnosilacZalbe();
    }

}
