//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.07 at 12:29:30 AM CET 
//

package projectXML.team9.models.zalbaNaOdluku;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * &lt;p&gt;Java class for anonymous complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content
 * contained within this class.
 * 
 * &lt;pre&gt; &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 * &amp;lt;sequence&amp;gt; &amp;lt;element name="adresa_poverenika"
 * type="{http://www.projekat.org/zalba_na_odluku}TAdresa"/&amp;gt;
 * &amp;lt;element name="zalilac"&amp;gt; &amp;lt;complexType&amp;gt;
 * &amp;lt;complexContent&amp;gt; &amp;lt;restriction
 * base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 * &amp;lt;sequence&amp;gt; &amp;lt;element name="lice"
 * type="{http://www.projekat.org/zalba_na_odluku}TLice"/&amp;gt;
 * &amp;lt;element name="drugi_podaci_za_kontakt"&amp;gt;
 * &amp;lt;simpleType&amp;gt; &amp;lt;restriction
 * base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt; &amp;lt;minLength
 * value="1"/&amp;gt; &amp;lt;/restriction&amp;gt; &amp;lt;/simpleType&amp;gt;
 * &amp;lt;/element&amp;gt; &amp;lt;/sequence&amp;gt;
 * &amp;lt;/restriction&amp;gt; &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt; &amp;lt;/element&amp;gt; &amp;lt;element
 * name="podaci_o_resenju"&amp;gt; &amp;lt;complexType&amp;gt;
 * &amp;lt;complexContent&amp;gt; &amp;lt;restriction
 * base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 * &amp;lt;sequence&amp;gt; &amp;lt;element name="godina"&amp;gt;
 * &amp;lt;simpleType&amp;gt; &amp;lt;restriction
 * base="{http://www.w3.org/2001/XMLSchema}positiveInteger"&amp;gt;
 * &amp;lt;totalDigits value="4"/&amp;gt; &amp;lt;/restriction&amp;gt;
 * &amp;lt;/simpleType&amp;gt; &amp;lt;/element&amp;gt; &amp;lt;element
 * name="naziv_organa"&amp;gt; &amp;lt;simpleType&amp;gt; &amp;lt;restriction
 * base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt; &amp;lt;minLength
 * value="1"/&amp;gt; &amp;lt;/restriction&amp;gt; &amp;lt;/simpleType&amp;gt;
 * &amp;lt;/element&amp;gt; &amp;lt;/sequence&amp;gt;
 * &amp;lt;/restriction&amp;gt; &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt; &amp;lt;/element&amp;gt; &amp;lt;element
 * name="datum_zahteva" type="{http://www.w3.org/2001/XMLSchema}date"/&amp;gt;
 * &amp;lt;element name="podaci_o_zalbi"&amp;gt; &amp;lt;complexType&amp;gt;
 * &amp;lt;complexContent&amp;gt; &amp;lt;restriction
 * base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 * &amp;lt;sequence&amp;gt; &amp;lt;element name="podnosilac_zalbe"&amp;gt;
 * &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 * &amp;lt;sequence&amp;gt; &amp;lt;element name="lice"
 * type="{http://www.projekat.org/zalba_na_odluku}TLice"/&amp;gt;
 * &amp;lt;element name="drugi_podaci_za_kontakt"&amp;gt;
 * &amp;lt;simpleType&amp;gt; &amp;lt;restriction
 * base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt; &amp;lt;minLength
 * value="1"/&amp;gt; &amp;lt;/restriction&amp;gt; &amp;lt;/simpleType&amp;gt;
 * &amp;lt;/element&amp;gt; &amp;lt;/sequence&amp;gt;
 * &amp;lt;/restriction&amp;gt; &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt; &amp;lt;/element&amp;gt; &amp;lt;element
 * name="datum_podnosenja"
 * type="{http://www.w3.org/2001/XMLSchema}date"/&amp;gt; &amp;lt;element
 * name="mesto"&amp;gt; &amp;lt;simpleType&amp;gt; &amp;lt;restriction
 * base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt; &amp;lt;minLength
 * value="1"/&amp;gt; &amp;lt;/restriction&amp;gt; &amp;lt;/simpleType&amp;gt;
 * &amp;lt;/element&amp;gt; &amp;lt;element name="opis"&amp;gt;
 * &amp;lt;simpleType&amp;gt; &amp;lt;restriction
 * base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt; &amp;lt;minLength
 * value="1"/&amp;gt; &amp;lt;/restriction&amp;gt; &amp;lt;/simpleType&amp;gt;
 * &amp;lt;/element&amp;gt; &amp;lt;/sequence&amp;gt;
 * &amp;lt;/restriction&amp;gt; &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt; &amp;lt;/element&amp;gt;
 * &amp;lt;/sequence&amp;gt; &amp;lt;attribute name="broj_zalbe"&amp;gt;
 * &amp;lt;simpleType&amp;gt; &amp;lt;restriction
 * base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt; &amp;lt;minLength
 * value="1"/&amp;gt; &amp;lt;/restriction&amp;gt; &amp;lt;/simpleType&amp;gt;
 * &amp;lt;/attribute&amp;gt; &amp;lt;attribute name="broj_zahteva"&amp;gt;
 * &amp;lt;simpleType&amp;gt; &amp;lt;restriction
 * base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt; &amp;lt;minLength
 * value="1"/&amp;gt; &amp;lt;/restriction&amp;gt; &amp;lt;/simpleType&amp;gt;
 * &amp;lt;/attribute&amp;gt; &amp;lt;attribute name="broj_resenja"&amp;gt;
 * &amp;lt;simpleType&amp;gt; &amp;lt;restriction
 * base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt; &amp;lt;minLength
 * value="1"/&amp;gt; &amp;lt;/restriction&amp;gt; &amp;lt;/simpleType&amp;gt;
 * &amp;lt;/attribute&amp;gt; &amp;lt;/restriction&amp;gt;
 * &amp;lt;/complexContent&amp;gt; &amp;lt;/complexType&amp;gt; &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "adresaPoverenika", "zalilac", "podaciOResenju", "datumZahteva", "podaciOZalbi" })
@XmlRootElement(name = "zalba_na_odluku")
public class ZalbaNaOdluku {

	@XmlElement(name = "adresa_poverenika", required = true)
	protected TAdresa adresaPoverenika;
	@XmlElement(required = true)
	protected ZalbaNaOdluku.Zalilac zalilac;
	@XmlElement(name = "podaci_o_resenju", required = true)
	protected ZalbaNaOdluku.PodaciOResenju podaciOResenju;
	@XmlElement(name = "datum_zahteva", required = true)
	@XmlSchemaType(name = "date")
	protected XMLGregorianCalendar datumZahteva;
	@XmlElement(name = "podaci_o_zalbi", required = true)
	protected ZalbaNaOdluku.PodaciOZalbi podaciOZalbi;
	@XmlAttribute(name = "broj_zalbe")
	protected String brojZalbe;
	@XmlAttribute(name = "broj_zahteva")
	protected String brojZahteva;
	@XmlAttribute(name = "broj_resenja")
	protected String brojResenja;
	
	@Override
	public String toString() {
		String zalbaNaOdluku = String.format("Zalba na odluku\nBroj zalbe je: %s\n", brojZalbe);
		zalbaNaOdluku += "\nAdresa poverenika kojem se salje zalba:\n" + adresaPoverenika.toString();
		zalbaNaOdluku += "\nZalilac:\n" + zalilac.toString();
		zalbaNaOdluku += "\nPodaci o resenju:\n" + podaciOResenju.toString();
		zalbaNaOdluku += "\nDatum zahteva: " + datumZahteva.toString();
		zalbaNaOdluku += "\n\nPodaci o zalbi:\n" + podaciOZalbi.toString();
		return zalbaNaOdluku;
	}

	/**
	 * Gets the value of the adresaPoverenika property.
	 * 
	 * @return possible object is {@link TAdresa }
	 * 
	 */
	public TAdresa getAdresaPoverenika() {
		return adresaPoverenika;
	}

	/**
	 * Sets the value of the adresaPoverenika property.
	 * 
	 * @param value allowed object is {@link TAdresa }
	 * 
	 */
	public void setAdresaPoverenika(TAdresa value) {
		this.adresaPoverenika = value;
	}

	/**
	 * Gets the value of the zalilac property.
	 * 
	 * @return possible object is {@link ZalbaNaOdluku.Zalilac }
	 * 
	 */
	public ZalbaNaOdluku.Zalilac getZalilac() {
		return zalilac;
	}

	/**
	 * Sets the value of the zalilac property.
	 * 
	 * @param value allowed object is {@link ZalbaNaOdluku.Zalilac }
	 * 
	 */
	public void setZalilac(ZalbaNaOdluku.Zalilac value) {
		this.zalilac = value;
	}

	/**
	 * Gets the value of the podaciOResenju property.
	 * 
	 * @return possible object is {@link ZalbaNaOdluku.PodaciOResenju }
	 * 
	 */
	public ZalbaNaOdluku.PodaciOResenju getPodaciOResenju() {
		return podaciOResenju;
	}

	/**
	 * Sets the value of the podaciOResenju property.
	 * 
	 * @param value allowed object is {@link ZalbaNaOdluku.PodaciOResenju }
	 * 
	 */
	public void setPodaciOResenju(ZalbaNaOdluku.PodaciOResenju value) {
		this.podaciOResenju = value;
	}

	/**
	 * Gets the value of the datumZahteva property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getDatumZahteva() {
		return datumZahteva;
	}

	/**
	 * Sets the value of the datumZahteva property.
	 * 
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setDatumZahteva(XMLGregorianCalendar value) {
		this.datumZahteva = value;
	}

	/**
	 * Gets the value of the podaciOZalbi property.
	 * 
	 * @return possible object is {@link ZalbaNaOdluku.PodaciOZalbi }
	 * 
	 */
	public ZalbaNaOdluku.PodaciOZalbi getPodaciOZalbi() {
		return podaciOZalbi;
	}

	/**
	 * Sets the value of the podaciOZalbi property.
	 * 
	 * @param value allowed object is {@link ZalbaNaOdluku.PodaciOZalbi }
	 * 
	 */
	public void setPodaciOZalbi(ZalbaNaOdluku.PodaciOZalbi value) {
		this.podaciOZalbi = value;
	}

	/**
	 * Gets the value of the brojZalbe property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getBrojZalbe() {
		return brojZalbe;
	}

	/**
	 * Sets the value of the brojZalbe property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setBrojZalbe(String value) {
		this.brojZalbe = value;
	}

	/**
	 * Gets the value of the brojZahteva property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getBrojZahteva() {
		return brojZahteva;
	}

	/**
	 * Sets the value of the brojZahteva property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setBrojZahteva(String value) {
		this.brojZahteva = value;
	}

	/**
	 * Gets the value of the brojResenja property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getBrojResenja() {
		return brojResenja;
	}

	/**
	 * Sets the value of the brojResenja property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setBrojResenja(String value) {
		this.brojResenja = value;
	}

	/**
	 * &lt;p&gt;Java class for anonymous complex type.
	 * 
	 * &lt;p&gt;The following schema fragment specifies the expected content
	 * contained within this class.
	 * 
	 * &lt;pre&gt; &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
	 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
	 * &amp;lt;sequence&amp;gt; &amp;lt;element name="godina"&amp;gt;
	 * &amp;lt;simpleType&amp;gt; &amp;lt;restriction
	 * base="{http://www.w3.org/2001/XMLSchema}positiveInteger"&amp;gt;
	 * &amp;lt;totalDigits value="4"/&amp;gt; &amp;lt;/restriction&amp;gt;
	 * &amp;lt;/simpleType&amp;gt; &amp;lt;/element&amp;gt; &amp;lt;element
	 * name="naziv_organa"&amp;gt; &amp;lt;simpleType&amp;gt; &amp;lt;restriction
	 * base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt; &amp;lt;minLength
	 * value="1"/&amp;gt; &amp;lt;/restriction&amp;gt; &amp;lt;/simpleType&amp;gt;
	 * &amp;lt;/element&amp;gt; &amp;lt;/sequence&amp;gt;
	 * &amp;lt;/restriction&amp;gt; &amp;lt;/complexContent&amp;gt;
	 * &amp;lt;/complexType&amp;gt; &lt;/pre&gt;
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "godina", "nazivOrgana" })
	public static class PodaciOResenju {

		@XmlElement(required = true)
		protected BigInteger godina;
		@XmlElement(name = "naziv_organa", required = true)
		protected String nazivOrgana;

		@Override
		public String toString() {
			String resenje = String.format("Godina: %s", godina);
			resenje += "\nNaziv organa: " + nazivOrgana + "\n";
			return resenje;
		}
		
		/**
		 * Gets the value of the godina property.
		 * 
		 * @return possible object is {@link BigInteger }
		 * 
		 */
		public BigInteger getGodina() {
			return godina;
		}

		/**
		 * Sets the value of the godina property.
		 * 
		 * @param value allowed object is {@link BigInteger }
		 * 
		 */
		public void setGodina(BigInteger value) {
			this.godina = value;
		}

		/**
		 * Gets the value of the nazivOrgana property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getNazivOrgana() {
			return nazivOrgana;
		}

		/**
		 * Sets the value of the nazivOrgana property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setNazivOrgana(String value) {
			this.nazivOrgana = value;
		}

	}

	/**
	 * &lt;p&gt;Java class for anonymous complex type.
	 * 
	 * &lt;p&gt;The following schema fragment specifies the expected content
	 * contained within this class.
	 * 
	 * &lt;pre&gt; &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
	 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
	 * &amp;lt;sequence&amp;gt; &amp;lt;element name="podnosilac_zalbe"&amp;gt;
	 * &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
	 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
	 * &amp;lt;sequence&amp;gt; &amp;lt;element name="lice"
	 * type="{http://www.projekat.org/zalba_na_odluku}TLice"/&amp;gt;
	 * &amp;lt;element name="drugi_podaci_za_kontakt"&amp;gt;
	 * &amp;lt;simpleType&amp;gt; &amp;lt;restriction
	 * base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt; &amp;lt;minLength
	 * value="1"/&amp;gt; &amp;lt;/restriction&amp;gt; &amp;lt;/simpleType&amp;gt;
	 * &amp;lt;/element&amp;gt; &amp;lt;/sequence&amp;gt;
	 * &amp;lt;/restriction&amp;gt; &amp;lt;/complexContent&amp;gt;
	 * &amp;lt;/complexType&amp;gt; &amp;lt;/element&amp;gt; &amp;lt;element
	 * name="datum_podnosenja"
	 * type="{http://www.w3.org/2001/XMLSchema}date"/&amp;gt; &amp;lt;element
	 * name="mesto"&amp;gt; &amp;lt;simpleType&amp;gt; &amp;lt;restriction
	 * base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt; &amp;lt;minLength
	 * value="1"/&amp;gt; &amp;lt;/restriction&amp;gt; &amp;lt;/simpleType&amp;gt;
	 * &amp;lt;/element&amp;gt; &amp;lt;element name="opis"&amp;gt;
	 * &amp;lt;simpleType&amp;gt; &amp;lt;restriction
	 * base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt; &amp;lt;minLength
	 * value="1"/&amp;gt; &amp;lt;/restriction&amp;gt; &amp;lt;/simpleType&amp;gt;
	 * &amp;lt;/element&amp;gt; &amp;lt;/sequence&amp;gt;
	 * &amp;lt;/restriction&amp;gt; &amp;lt;/complexContent&amp;gt;
	 * &amp;lt;/complexType&amp;gt; &lt;/pre&gt;
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "podnosilacZalbe", "datumPodnosenja", "mesto", "opis" })
	public static class PodaciOZalbi {

		@XmlElement(name = "podnosilac_zalbe", required = true)
		protected ZalbaNaOdluku.PodaciOZalbi.PodnosilacZalbe podnosilacZalbe;
		@XmlElement(name = "datum_podnosenja", required = true)
		@XmlSchemaType(name = "date")
		protected XMLGregorianCalendar datumPodnosenja;
		@XmlElement(required = true)
		protected String mesto;
		@XmlElement(required = true)
		protected String opis;
		
		@Override
		public String toString() {
			String zalba = String.format("Podnosilac: \n%s", podnosilacZalbe.toString());
			zalba += "\nDatum podnosenja zalbe: " + datumPodnosenja;
			zalba += "\nMesto: " + mesto;
			zalba += "\nOpis: " + opis;
			return zalba;
		}

		/**
		 * Gets the value of the podnosilacZalbe property.
		 * 
		 * @return possible object is
		 *         {@link ZalbaNaOdluku.PodaciOZalbi.PodnosilacZalbe }
		 * 
		 */
		public ZalbaNaOdluku.PodaciOZalbi.PodnosilacZalbe getPodnosilacZalbe() {
			return podnosilacZalbe;
		}

		/**
		 * Sets the value of the podnosilacZalbe property.
		 * 
		 * @param value allowed object is
		 *              {@link ZalbaNaOdluku.PodaciOZalbi.PodnosilacZalbe }
		 * 
		 */
		public void setPodnosilacZalbe(ZalbaNaOdluku.PodaciOZalbi.PodnosilacZalbe value) {
			this.podnosilacZalbe = value;
		}

		/**
		 * Gets the value of the datumPodnosenja property.
		 * 
		 * @return possible object is {@link XMLGregorianCalendar }
		 * 
		 */
		public XMLGregorianCalendar getDatumPodnosenja() {
			return datumPodnosenja;
		}

		/**
		 * Sets the value of the datumPodnosenja property.
		 * 
		 * @param value allowed object is {@link XMLGregorianCalendar }
		 * 
		 */
		public void setDatumPodnosenja(XMLGregorianCalendar value) {
			this.datumPodnosenja = value;
		}

		/**
		 * Gets the value of the mesto property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getMesto() {
			return mesto;
		}

		/**
		 * Sets the value of the mesto property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setMesto(String value) {
			this.mesto = value;
		}

		/**
		 * Gets the value of the opis property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getOpis() {
			return opis;
		}

		/**
		 * Sets the value of the opis property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setOpis(String value) {
			this.opis = value;
		}

		/**
		 * &lt;p&gt;Java class for anonymous complex type.
		 * 
		 * &lt;p&gt;The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * &lt;pre&gt; &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
		 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
		 * &amp;lt;sequence&amp;gt; &amp;lt;element name="lice"
		 * type="{http://www.projekat.org/zalba_na_odluku}TLice"/&amp;gt;
		 * &amp;lt;element name="drugi_podaci_za_kontakt"&amp;gt;
		 * &amp;lt;simpleType&amp;gt; &amp;lt;restriction
		 * base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt; &amp;lt;minLength
		 * value="1"/&amp;gt; &amp;lt;/restriction&amp;gt; &amp;lt;/simpleType&amp;gt;
		 * &amp;lt;/element&amp;gt; &amp;lt;/sequence&amp;gt;
		 * &amp;lt;/restriction&amp;gt; &amp;lt;/complexContent&amp;gt;
		 * &amp;lt;/complexType&amp;gt; &lt;/pre&gt;
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "lice", "drugiPodaciZaKontakt" })
		public static class PodnosilacZalbe {

			@XmlElement(required = true)
			protected TLice lice;
			@XmlElement(name = "drugi_podaci_za_kontakt", required = true)
			protected String drugiPodaciZaKontakt;

			@Override
			public String toString() {
				String zalilac = lice.toString();
				zalilac += "Drugi podaci za kontakt: " + drugiPodaciZaKontakt + "\n";
				return zalilac;
			}
			
			/**
			 * Gets the value of the lice property.
			 * 
			 * @return possible object is {@link TLice }
			 * 
			 */
			public TLice getLice() {
				return lice;
			}

			/**
			 * Sets the value of the lice property.
			 * 
			 * @param value allowed object is {@link TLice }
			 * 
			 */
			public void setLice(TLice value) {
				this.lice = value;
			}

			/**
			 * Gets the value of the drugiPodaciZaKontakt property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getDrugiPodaciZaKontakt() {
				return drugiPodaciZaKontakt;
			}

			/**
			 * Sets the value of the drugiPodaciZaKontakt property.
			 * 
			 * @param value allowed object is {@link String }
			 * 
			 */
			public void setDrugiPodaciZaKontakt(String value) {
				this.drugiPodaciZaKontakt = value;
			}

		}

	}

	/**
	 * &lt;p&gt;Java class for anonymous complex type.
	 * 
	 * &lt;p&gt;The following schema fragment specifies the expected content
	 * contained within this class.
	 * 
	 * &lt;pre&gt; &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
	 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
	 * &amp;lt;sequence&amp;gt; &amp;lt;element name="lice"
	 * type="{http://www.projekat.org/zalba_na_odluku}TLice"/&amp;gt;
	 * &amp;lt;element name="drugi_podaci_za_kontakt"&amp;gt;
	 * &amp;lt;simpleType&amp;gt; &amp;lt;restriction
	 * base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt; &amp;lt;minLength
	 * value="1"/&amp;gt; &amp;lt;/restriction&amp;gt; &amp;lt;/simpleType&amp;gt;
	 * &amp;lt;/element&amp;gt; &amp;lt;/sequence&amp;gt;
	 * &amp;lt;/restriction&amp;gt; &amp;lt;/complexContent&amp;gt;
	 * &amp;lt;/complexType&amp;gt; &lt;/pre&gt;
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "lice", "drugiPodaciZaKontakt" })
	public static class Zalilac {

		@XmlElement(required = true)
		protected TLice lice;
		@XmlElement(name = "drugi_podaci_za_kontakt", required = true)
		protected String drugiPodaciZaKontakt;

		@Override
		public String toString() {
			String zalilac = lice.toString();
			zalilac += "Drugi podaci za kontakt: " + drugiPodaciZaKontakt + "\n";
			return zalilac;
		}
		
		/**
		 * Gets the value of the lice property.
		 * 
		 * @return possible object is {@link TLice }
		 * 
		 */
		public TLice getLice() {
			return lice;
		}

		/**
		 * Sets the value of the lice property.
		 * 
		 * @param value allowed object is {@link TLice }
		 * 
		 */
		public void setLice(TLice value) {
			this.lice = value;
		}

		/**
		 * Gets the value of the drugiPodaciZaKontakt property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getDrugiPodaciZaKontakt() {
			return drugiPodaciZaKontakt;
		}

		/**
		 * Sets the value of the drugiPodaciZaKontakt property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setDrugiPodaciZaKontakt(String value) {
			this.drugiPodaciZaKontakt = value;
		}

	}

}
