//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.04 at 08:48:29 PM CET 
//


package projectXML.team9.models.resenje;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * &lt;p&gt;Java class for anonymous complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *       &amp;lt;sequence&amp;gt;
 *         &amp;lt;element name="opis_žalbe"&amp;gt;
 *           &amp;lt;complexType&amp;gt;
 *             &amp;lt;complexContent&amp;gt;
 *               &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *                 &amp;lt;sequence&amp;gt;
 *                   &amp;lt;element name="žalioc" type="{http://www.projekat.org/resenje}T_žalioc"/&amp;gt;
 *                   &amp;lt;element name="organ"&amp;gt;
 *                     &amp;lt;complexType&amp;gt;
 *                       &amp;lt;complexContent&amp;gt;
 *                         &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *                           &amp;lt;sequence&amp;gt;
 *                             &amp;lt;element name="naziv" type="{http://www.w3.org/2001/XMLSchema}string"/&amp;gt;
 *                             &amp;lt;element name="adresa" type="{http://www.projekat.org/resenje}T_Adresa"/&amp;gt;
 *                           &amp;lt;/sequence&amp;gt;
 *                         &amp;lt;/restriction&amp;gt;
 *                       &amp;lt;/complexContent&amp;gt;
 *                     &amp;lt;/complexType&amp;gt;
 *                   &amp;lt;/element&amp;gt;
 *                   &amp;lt;element name="datum_žalbe" type="{http://www.w3.org/2001/XMLSchema}date"/&amp;gt;
 *                   &amp;lt;element name="ceo_opis" type="{http://www.w3.org/2001/XMLSchema}string"/&amp;gt;
 *                 &amp;lt;/sequence&amp;gt;
 *               &amp;lt;/restriction&amp;gt;
 *             &amp;lt;/complexContent&amp;gt;
 *           &amp;lt;/complexType&amp;gt;
 *         &amp;lt;/element&amp;gt;
 *         &amp;lt;element name="rešenja" type="{http://www.projekat.org/resenje}T_Multi_Paragraf"/&amp;gt;
 *         &amp;lt;element name="obrazloženje"&amp;gt;
 *           &amp;lt;complexType&amp;gt;
 *             &amp;lt;complexContent&amp;gt;
 *               &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *                 &amp;lt;sequence&amp;gt;
 *                   &amp;lt;element name="opis" type="{http://www.projekat.org/resenje}T_Multi_Paragraf"/&amp;gt;
 *                   &amp;lt;element name="razlog" type="{http://www.projekat.org/resenje}T_Multi_Paragraf"/&amp;gt;
 *                   &amp;lt;element name="kona\u010dno_rešenje" type="{http://www.projekat.org/resenje}T_Multi_Paragraf"/&amp;gt;
 *                 &amp;lt;/sequence&amp;gt;
 *               &amp;lt;/restriction&amp;gt;
 *             &amp;lt;/complexContent&amp;gt;
 *           &amp;lt;/complexType&amp;gt;
 *         &amp;lt;/element&amp;gt;
 *         &amp;lt;element name="uputstvo" type="{http://www.w3.org/2001/XMLSchema}string"/&amp;gt;
 *         &amp;lt;element name="datum_rešenja" type="{http://www.w3.org/2001/XMLSchema}date"/&amp;gt;
 *         &amp;lt;element name="poverenik" type="{http://www.projekat.org/resenje}T_Lice"/&amp;gt;
 *       &amp;lt;/sequence&amp;gt;
 *       &amp;lt;attribute name="broj_rešenja" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&amp;gt;
 *       &amp;lt;attribute name="broj_žalbe" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&amp;gt;
 *       &amp;lt;attribute name="broj_zahteva" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&amp;gt;
 *       &amp;lt;attribute name="tip_rešenja" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&amp;gt;
 *     &amp;lt;/restriction&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "opis\u017dalbe",
    "re\u0161enja",
    "obrazlo\u017eenje",
    "uputstvo",
    "datumRe\u0161enja",
    "poverenik"
})
@XmlRootElement(name = "odluka_poverioca")
public class OdlukaPoverioca {

	@XmlElement(name = "opis_\u017ealbe", required = true)
    protected OdlukaPoverioca.OpisŽalbe opisŽalbe;
    @XmlElement(required = true)
    protected TMultiParagraf rešenja;
    @XmlElement(required = true)
    protected Obrazloženje obrazloženje;
    @XmlElement(required = true)
    protected String uputstvo;
    @XmlElement(name = "datum_re\u0161enja", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumRešenja;
    @XmlElement(required = true)
    protected TLice poverenik;
    @XmlAttribute(name = "broj_re\u0161enja")
    @XmlSchemaType(name = "anySimpleType")
    protected String brojRešenja;
    @XmlAttribute(name = "broj_\u017ealbe")
    @XmlSchemaType(name = "anySimpleType")
    protected String brojŽalbe;
    @XmlAttribute(name = "broj_zahteva")
    @XmlSchemaType(name = "anySimpleType")
    protected String brojZahteva;
    @XmlAttribute(name = "tip_re\u0161enja")
    @XmlSchemaType(name = "anySimpleType")
    protected String tipRešenja;

    /**
     * Gets the value of the opisŽalbe property.
     * 
     * @return
     *     possible object is
     *     {@link OdlukaPoverioca.OpisŽalbe }
     *     
     */
    public OdlukaPoverioca.OpisŽalbe getOpisŽalbe() {
        return opisŽalbe;
    }

    /**
     * Sets the value of the opisŽalbe property.
     * 
     * @param value
     *     allowed object is
     *     {@link OdlukaPoverioca.OpisŽalbe }
     *     
     */
    public void setOpisŽalbe(OdlukaPoverioca.OpisŽalbe value) {
        this.opisŽalbe = value;
    }

    /**
     * Gets the value of the rešenja property.
     * 
     * @return
     *     possible object is
     *     {@link TMultiParagraf }
     *     
     */
    public TMultiParagraf getRešenja() {
        return rešenja;
    }

    /**
     * Sets the value of the rešenja property.
     * 
     * @param value
     *     allowed object is
     *     {@link TMultiParagraf }
     *     
     */
    public void setRešenja(TMultiParagraf value) {
        this.rešenja = value;
    }

    /**
     * Gets the value of the obrazloženje property.
     * 
     * @return
     *     possible object is
     *     {@link OdlukaPoverioca.Obrazloženje }
     *     
     */
    public OdlukaPoverioca.Obrazloženje getObrazloženje() {
        return obrazloženje;
    }

    /**
     * Sets the value of the obrazloženje property.
     * 
     * @param value
     *     allowed object is
     *     {@link OdlukaPoverioca.Obrazloženje }
     *     
     */
    public void setObrazloženje(OdlukaPoverioca.Obrazloženje value) {
        this.obrazloženje = value;
    }

    /**
     * Gets the value of the uputstvo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUputstvo() {
        return uputstvo;
    }

    /**
     * Sets the value of the uputstvo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUputstvo(String value) {
        this.uputstvo = value;
    }

    /**
     * Gets the value of the datumRešenja property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumRešenja() {
        return datumRešenja;
    }

    /**
     * Sets the value of the datumRešenja property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumRešenja(XMLGregorianCalendar value) {
        this.datumRešenja = value;
    }

    /**
     * Gets the value of the poverenik property.
     * 
     * @return
     *     possible object is
     *     {@link TLice }
     *     
     */
    public TLice getPoverenik() {
        return poverenik;
    }

    /**
     * Sets the value of the poverenik property.
     * 
     * @param value
     *     allowed object is
     *     {@link TLice }
     *     
     */
    public void setPoverenik(TLice value) {
        this.poverenik = value;
    }

    /**
     * Gets the value of the brojRešenja property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrojRešenja() {
        return brojRešenja;
    }

    /**
     * Sets the value of the brojRešenja property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrojRešenja(String value) {
        this.brojRešenja = value;
    }

    /**
     * Gets the value of the brojšalbe property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrojŽalbe() {
        return brojŽalbe;
    }

    /**
     * Sets the value of the brojŽalbe property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrojŽalbe(String value) {
        this.brojŽalbe = value;
    }

    /**
     * Gets the value of the brojZahteva property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrojZahteva() {
        return brojZahteva;
    }

    /**
     * Sets the value of the brojZahteva property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrojZahteva(String value) {
        this.brojZahteva = value;
    }

    /**
     * Gets the value of the tipReŽenja property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipRešenja() {
        return tipRešenja;
    }

    /**
     * Sets the value of the tipReŽenja property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipRešenja(String value) {
        this.tipRešenja = value;
    }


    /**
     * &lt;p&gt;Java class for anonymous complex type.
     * 
     * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
     * 
     * &lt;pre&gt;
     * &amp;lt;complexType&amp;gt;
     *   &amp;lt;complexContent&amp;gt;
     *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
     *       &amp;lt;sequence&amp;gt;
     *         &amp;lt;element name="opis" type="{http://www.projekat.org/resenje}T_Multi_Paragraf"/&amp;gt;
     *         &amp;lt;element name="razlog" type="{http://www.projekat.org/resenje}T_Multi_Paragraf"/&amp;gt;
     *         &amp;lt;element name="kona\u010dno_reŽenje" type="{http://www.projekat.org/resenje}T_Multi_Paragraf"/&amp;gt;
     *       &amp;lt;/sequence&amp;gt;
     *     &amp;lt;/restriction&amp;gt;
     *   &amp;lt;/complexContent&amp;gt;
     * &amp;lt;/complexType&amp;gt;
     * &lt;/pre&gt;
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "opis",
        "razlog",
        "kona\u010dnoRe\u0161enje"
    })
    public static class Obrazloženje {

        @XmlElement(required = true)
        protected TMultiParagraf opis;
        @XmlElement(required = true)
        protected TMultiParagraf razlog;
        @XmlElement(name = "kona\u010dno_re\u0161enje", required = true)
        protected TMultiParagraf kona\u010dnoReŽenje;

        /**
         * Gets the value of the opis property.
         * 
         * @return
         *     possible object is
         *     {@link TMultiParagraf }
         *     
         */
        public TMultiParagraf getOpis() {
            return opis;
        }

        /**
         * Sets the value of the opis property.
         * 
         * @param value
         *     allowed object is
         *     {@link TMultiParagraf }
         *     
         */
        public void setOpis(TMultiParagraf value) {
            this.opis = value;
        }

        /**
         * Gets the value of the razlog property.
         * 
         * @return
         *     possible object is
         *     {@link TMultiParagraf }
         *     
         */
        public TMultiParagraf getRazlog() {
            return razlog;
        }

        /**
         * Sets the value of the razlog property.
         * 
         * @param value
         *     allowed object is
         *     {@link TMultiParagraf }
         *     
         */
        public void setRazlog(TMultiParagraf value) {
            this.razlog = value;
        }

        /**
         * Gets the value of the kona\u010dnoReŽenje property.
         * 
         * @return
         *     possible object is
         *     {@link TMultiParagraf }
         *     
         */
        public TMultiParagraf getKona\u010dnoReŽenje() {
            return kona\u010dnoReŽenje;
        }

        /**
         * Sets the value of the kona\u010dnoReŽenje property.
         * 
         * @param value
         *     allowed object is
         *     {@link TMultiParagraf }
         *     
         */
        public void setKona\u010dnoReŽenje(TMultiParagraf value) {
            this.kona\u010dnoReŽenje = value;
        }

    }


    /**
     * &lt;p&gt;Java class for anonymous complex type.
     * 
     * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
     * 
     * &lt;pre&gt;
     * &amp;lt;complexType&amp;gt;
     *   &amp;lt;complexContent&amp;gt;
     *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
     *       &amp;lt;sequence&amp;gt;
     *         &amp;lt;element name="Žalioc" type="{http://www.projekat.org/resenje}T_Žalioc"/&amp;gt;
     *         &amp;lt;element name="organ"&amp;gt;
     *           &amp;lt;complexType&amp;gt;
     *             &amp;lt;complexContent&amp;gt;
     *               &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
     *                 &amp;lt;sequence&amp;gt;
     *                   &amp;lt;element name="naziv" type="{http://www.w3.org/2001/XMLSchema}string"/&amp;gt;
     *                   &amp;lt;element name="adresa" type="{http://www.projekat.org/resenje}T_Adresa"/&amp;gt;
     *                 &amp;lt;/sequence&amp;gt;
     *               &amp;lt;/restriction&amp;gt;
     *             &amp;lt;/complexContent&amp;gt;
     *           &amp;lt;/complexType&amp;gt;
     *         &amp;lt;/element&amp;gt;
     *         &amp;lt;element name="datum_Žalbe" type="{http://www.w3.org/2001/XMLSchema}date"/&amp;gt;
     *         &amp;lt;element name="ceo_opis" type="{http://www.w3.org/2001/XMLSchema}string"/&amp;gt;
     *       &amp;lt;/sequence&amp;gt;
     *     &amp;lt;/restriction&amp;gt;
     *   &amp;lt;/complexContent&amp;gt;
     * &amp;lt;/complexType&amp;gt;
     * &lt;/pre&gt;
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "\u017ealioc",
        "organ",
        "datum\u017dalbe",
        "ceoOpis"
    })
    public static class OpisŽalbe {

        @XmlElement(required = true)
        protected TŽalioc Žalioc;
        @XmlElement(required = true)
        protected OdlukaPoverioca.OpisŽalbe.Organ organ;
        @XmlElement(name = "datum_\u017ealbe", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar datumŽalbe;
        @XmlElement(name = "ceo_opis", required = true)
        protected String ceoOpis;

        /**
         * Gets the value of the Žalioc property.
         * 
         * @return
         *     possible object is
         *     {@link TŽalioc }
         *     
         */
        public TŽalioc getŽalioc() {
            return Žalioc;
        }

        /**
         * Sets the value of the Žalioc property.
         * 
         * @param value
         *     allowed object is
         *     {@link TŽalioc }
         *     
         */
        public void setŽalioc(TŽalioc value) {
            this.Žalioc = value;
        }

        /**
         * Gets the value of the organ property.
         * 
         * @return
         *     possible object is
         *     {@link OdlukaPoverioca.OpisŽalbe.Organ }
         *     
         */
        public OdlukaPoverioca.OpisŽalbe.Organ getOrgan() {
            return organ;
        }

        /**
         * Sets the value of the organ property.
         * 
         * @param value
         *     allowed object is
         *     {@link OdlukaPoverioca.OpisŽalbe.Organ }
         *     
         */
        public void setOrgan(OdlukaPoverioca.OpisŽalbe.Organ value) {
            this.organ = value;
        }

        /**
         * Gets the value of the datumŽalbe property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDatumŽalbe() {
            return datumŽalbe;
        }

        /**
         * Sets the value of the datumŽalbe property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDatumŽalbe(XMLGregorianCalendar value) {
            this.datumŽalbe = value;
        }

        /**
         * Gets the value of the ceoOpis property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCeoOpis() {
            return ceoOpis;
        }

        /**
         * Sets the value of the ceoOpis property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCeoOpis(String value) {
            this.ceoOpis = value;
        }


        /**
         * &lt;p&gt;Java class for anonymous complex type.
         * 
         * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
         * 
         * &lt;pre&gt;
         * &amp;lt;complexType&amp;gt;
         *   &amp;lt;complexContent&amp;gt;
         *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
         *       &amp;lt;sequence&amp;gt;
         *         &amp;lt;element name="naziv" type="{http://www.w3.org/2001/XMLSchema}string"/&amp;gt;
         *         &amp;lt;element name="adresa" type="{http://www.projekat.org/resenje}T_Adresa"/&amp;gt;
         *       &amp;lt;/sequence&amp;gt;
         *     &amp;lt;/restriction&amp;gt;
         *   &amp;lt;/complexContent&amp;gt;
         * &amp;lt;/complexType&amp;gt;
         * &lt;/pre&gt;
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "naziv",
            "adresa"
        })
        public static class Organ {

            @XmlElement(required = true)
            protected String naziv;
            @XmlElement(required = true)
            protected TAdresa adresa;

            /**
             * Gets the value of the naziv property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNaziv() {
                return naziv;
            }

            /**
             * Sets the value of the naziv property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNaziv(String value) {
                this.naziv = value;
            }

            /**
             * Gets the value of the adresa property.
             * 
             * @return
             *     possible object is
             *     {@link TAdresa }
             *     
             */
            public TAdresa getAdresa() {
                return adresa;
            }

            /**
             * Sets the value of the adresa property.
             * 
             * @param value
             *     allowed object is
             *     {@link TAdresa }
             *     
             */
            public void setAdresa(TAdresa value) {
                this.adresa = value;
            }

        }

    }

}
