//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.01 at 02:49:33 PM CET 
//


package projectXML.team9.models.zahtev;

import javax.xml.bind.annotation.XmlRegistry;

import org.springframework.stereotype.Component;

import projectXML.team9.models.common.TAdresa;
import projectXML.team9.models.common.TFizickoLice;
import projectXML.team9.models.common.TPravnoLice;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the projectXML.team9.models.zahtev package. 
 * &lt;p&gt;An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@Component(value="someBean")
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: projectXML.team9.models.zahtev
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ZahtevGradjana }
     * 
     */
    public ZahtevGradjana createZahtevGradjana() {
        return new ZahtevGradjana();
    }

    /**
     * Create an instance of {@link ZahtevGradjana.InformacijeVezaneZaZahtev }
     * 
     */
    public ZahtevGradjana.InformacijeVezaneZaZahtev createZahtevGradjanaInformacijeVezaneZaZahtev() {
        return new ZahtevGradjana.InformacijeVezaneZaZahtev();
    }

    /**
     * Create an instance of {@link ZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva }
     * 
     */
    public ZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva createZahtevGradjanaInformacijeVezaneZaZahtevTipZahteva() {
        return new ZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva();
    }

    /**
     * Create an instance of {@link ZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva.DostavljanjeKopije }
     * 
     */
    public ZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva.DostavljanjeKopije createZahtevGradjanaInformacijeVezaneZaZahtevTipZahtevaDostavljanjeKopije() {
        return new ZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva.DostavljanjeKopije();
    }

    /**
     * Create an instance of {@link TPravnoLice }
     * 
     */
    public TPravnoLice createTPravnoLice() {
        return new TPravnoLice();
    }

    /**
     * Create an instance of {@link ZahtevGradjana.Trazilac }
     * 
     */
    public ZahtevGradjana.Trazilac createZahtevGradjanaTrazilac() {
        return new ZahtevGradjana.Trazilac();
    }

    /**
     * Create an instance of {@link TAdresa }
     * 
     */
    public TAdresa createTAdresa() {
        return new TAdresa();
    }

    /**
     * Create an instance of {@link TFizickoLice }
     * 
     */
    public TFizickoLice createTFizickoLice() {
        return new TFizickoLice();
    }

    /**
     * Create an instance of {@link ZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva.ObavestenjePosedovanjaInformacije }
     * 
     */
    public ZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva.ObavestenjePosedovanjaInformacije createZahtevGradjanaInformacijeVezaneZaZahtevTipZahtevaObavestenjePosedovanjaInformacije() {
        return new ZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva.ObavestenjePosedovanjaInformacije();
    }

    /**
     * Create an instance of {@link ZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva.UvidUDokument }
     * 
     */
    public ZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva.UvidUDokument createZahtevGradjanaInformacijeVezaneZaZahtevTipZahtevaUvidUDokument() {
        return new ZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva.UvidUDokument();
    }

    /**
     * Create an instance of {@link ZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva.KopijuDokumenta }
     * 
     */
    public ZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva.KopijuDokumenta createZahtevGradjanaInformacijeVezaneZaZahtevTipZahtevaKopijuDokumenta() {
        return new ZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva.KopijuDokumenta();
    }

    /**
     * Create an instance of {@link ZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva.DostavljanjeKopije.Posta }
     * 
     */
    public ZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva.DostavljanjeKopije.Posta createZahtevGradjanaInformacijeVezaneZaZahtevTipZahtevaDostavljanjeKopijePosta() {
        return new ZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva.DostavljanjeKopije.Posta();
    }

    /**
     * Create an instance of {@link ZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva.DostavljanjeKopije.Faks }
     * 
     */
    public ZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva.DostavljanjeKopije.Faks createZahtevGradjanaInformacijeVezaneZaZahtevTipZahtevaDostavljanjeKopijeFaks() {
        return new ZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva.DostavljanjeKopije.Faks();
    }

    /**
     * Create an instance of {@link ZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva.DostavljanjeKopije.EPosta }
     * 
     */
    public ZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva.DostavljanjeKopije.EPosta createZahtevGradjanaInformacijeVezaneZaZahtevTipZahtevaDostavljanjeKopijeEPosta() {
        return new ZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva.DostavljanjeKopije.EPosta();
    }

    /**
     * Create an instance of {@link ZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva.DostavljanjeKopije.DrugiNacin }
     * 
     */
    public ZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva.DostavljanjeKopije.DrugiNacin createZahtevGradjanaInformacijeVezaneZaZahtevTipZahtevaDostavljanjeKopijeDrugiNacin() {
        return new ZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva.DostavljanjeKopije.DrugiNacin();
    }

}
