//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.01 at 02:49:33 PM CET 
//

package projectXML.team9.models.zahtev;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;

import projectXML.team9.models.common.TLice;
import projectXML.team9.models.common.TPravnoLice;

/**
 * &lt;p&gt;Java class for anonymous complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content
 * contained within this class.
 * 
 * &lt;pre&gt; &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 * &amp;lt;sequence&amp;gt; &amp;lt;element name="organ"
 * type="{http://www.projekat.org/zahtev}TPravno_lice"/&amp;gt; &amp;lt;element
 * name="trazilac"&amp;gt; &amp;lt;complexType&amp;gt;
 * &amp;lt;complexContent&amp;gt; &amp;lt;restriction
 * base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 * &amp;lt;sequence&amp;gt; &amp;lt;element name="drugi_podatak_za_kontakt"
 * minOccurs="0"&amp;gt; &amp;lt;simpleType&amp;gt; &amp;lt;restriction
 * base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt; &amp;lt;minLength
 * value="1"/&amp;gt; &amp;lt;maxLength value="30"/&amp;gt;
 * &amp;lt;/restriction&amp;gt; &amp;lt;/simpleType&amp;gt;
 * &amp;lt;/element&amp;gt; &amp;lt;element name="lice"
 * type="{http://www.projekat.org/zahtev}TLice"/&amp;gt;
 * &amp;lt;/sequence&amp;gt; &amp;lt;/restriction&amp;gt;
 * &amp;lt;/complexContent&amp;gt; &amp;lt;/complexType&amp;gt;
 * &amp;lt;/element&amp;gt; &amp;lt;element
 * name="informacije_vezane_za_zahtev"&amp;gt; &amp;lt;complexType&amp;gt;
 * &amp;lt;complexContent&amp;gt; &amp;lt;restriction
 * base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 * &amp;lt;sequence&amp;gt; &amp;lt;element name="tip_zahteva"&amp;gt;
 * &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 * &amp;lt;sequence&amp;gt; &amp;lt;element
 * name="obavestenje_posedovanja_informacije" minOccurs="0"&amp;gt;
 * &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 * &amp;lt;attribute name="tip" type="{http://www.w3.org/2001/XMLSchema}string"
 * fixed="obave�tenje da li poseduje tra�enu informaciju" /&amp;gt;
 * &amp;lt;/restriction&amp;gt; &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt; &amp;lt;/element&amp;gt; &amp;lt;element
 * name="uvid_u_dokument" minOccurs="0"&amp;gt; &amp;lt;complexType&amp;gt;
 * &amp;lt;complexContent&amp;gt; &amp;lt;restriction
 * base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt; &amp;lt;attribute
 * name="tip" type="{http://www.w3.org/2001/XMLSchema}string" fixed="uvid u
 * dokument koji sadr�i tra�enu informaciju" /&amp;gt;
 * &amp;lt;/restriction&amp;gt; &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt; &amp;lt;/element&amp;gt; &amp;lt;element
 * name="kopiju_dokumenta" minOccurs="0"&amp;gt; &amp;lt;complexType&amp;gt;
 * &amp;lt;complexContent&amp;gt; &amp;lt;restriction
 * base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt; &amp;lt;attribute
 * name="tip" type="{http://www.w3.org/2001/XMLSchema}string" fixed="kopiju
 * dokumenta koji sadr�i tra�enu informaciju" /&amp;gt;
 * &amp;lt;/restriction&amp;gt; &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt; &amp;lt;/element&amp;gt; &amp;lt;element
 * name="dostavljanje_kopije" minOccurs="0"&amp;gt; &amp;lt;complexType&amp;gt;
 * &amp;lt;complexContent&amp;gt; &amp;lt;restriction
 * base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 * &amp;lt;sequence&amp;gt; &amp;lt;element name="posta" minOccurs="0"&amp;gt;
 * &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 * &amp;lt;attribute name="tip" type="{http://www.w3.org/2001/XMLSchema}string"
 * fixed="po�tom" /&amp;gt; &amp;lt;/restriction&amp;gt;
 * &amp;lt;/complexContent&amp;gt; &amp;lt;/complexType&amp;gt;
 * &amp;lt;/element&amp;gt; &amp;lt;element name="faks" minOccurs="0"&amp;gt;
 * &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 * &amp;lt;attribute name="tip" type="{http://www.w3.org/2001/XMLSchema}string"
 * fixed="faksom" /&amp;gt; &amp;lt;/restriction&amp;gt;
 * &amp;lt;/complexContent&amp;gt; &amp;lt;/complexType&amp;gt;
 * &amp;lt;/element&amp;gt; &amp;lt;element name="e-posta" minOccurs="0"&amp;gt;
 * &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 * &amp;lt;attribute name="tip" type="{http://www.w3.org/2001/XMLSchema}string"
 * fixed="elektronskom postom" /&amp;gt; &amp;lt;/restriction&amp;gt;
 * &amp;lt;/complexContent&amp;gt; &amp;lt;/complexType&amp;gt;
 * &amp;lt;/element&amp;gt; &amp;lt;element name="drugi_nacin"
 * minOccurs="0"&amp;gt; &amp;lt;complexType&amp;gt;
 * &amp;lt;complexContent&amp;gt; &amp;lt;restriction
 * base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 * &amp;lt;sequence&amp;gt; &amp;lt;element name="opis_dostave"&amp;gt;
 * &amp;lt;simpleType&amp;gt; &amp;lt;restriction
 * base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt; &amp;lt;minLength
 * value="1"/&amp;gt; &amp;lt;maxLength value="30"/&amp;gt;
 * &amp;lt;/restriction&amp;gt; &amp;lt;/simpleType&amp;gt;
 * &amp;lt;/element&amp;gt; &amp;lt;/sequence&amp;gt; &amp;lt;attribute
 * name="tip" type="{http://www.w3.org/2001/XMLSchema}string" fixed="na drugi
 * nacin" /&amp;gt; &amp;lt;/restriction&amp;gt; &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt; &amp;lt;/element&amp;gt;
 * &amp;lt;/sequence&amp;gt; &amp;lt;attribute name="tip"
 * type="{http://www.w3.org/2001/XMLSchema}string" fixed="dostavljanje kopije
 * dokumenta koji sad�i tra�enu informaciju" /&amp;gt;
 * &amp;lt;/restriction&amp;gt; &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt; &amp;lt;/element&amp;gt;
 * &amp;lt;/sequence&amp;gt; &amp;lt;/restriction&amp;gt;
 * &amp;lt;/complexContent&amp;gt; &amp;lt;/complexType&amp;gt;
 * &amp;lt;/element&amp;gt; &amp;lt;element name="opis_zahteva"
 * type="{http://www.w3.org/2001/XMLSchema}string"/&amp;gt; &amp;lt;element
 * name="mesto" type="{http://www.w3.org/2001/XMLSchema}string"/&amp;gt;
 * &amp;lt;element name="datum"
 * type="{http://www.w3.org/2001/XMLSchema}date"/&amp;gt;
 * &amp;lt;/sequence&amp;gt; &amp;lt;/restriction&amp;gt;
 * &amp;lt;/complexContent&amp;gt; &amp;lt;/complexType&amp;gt;
 * &amp;lt;/element&amp;gt; &amp;lt;/sequence&amp;gt; &amp;lt;attribute
 * name="broj_zahteva" use="required"&amp;gt; &amp;lt;simpleType&amp;gt;
 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt;
 * &amp;lt;minLength value="1"/&amp;gt; &amp;lt;/restriction&amp;gt;
 * &amp;lt;/simpleType&amp;gt; &amp;lt;/attribute&amp;gt;
 * &amp;lt;/restriction&amp;gt; &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt; &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TZahtevGradjana", propOrder = { "organ", "trazilac", "informacijeVezaneZaZahtev" })
public class TZahtevGradjana {

	@Override
	public String toString() {
		String obavestenje = String.format("!Dokument zahtev!\n");
		obavestenje += "Organ:\n\t" + organ.toString();
		obavestenje += "\nPodnosilac zahteva:\n\t" + trazilac.toString();
		obavestenje += "\n" + informacijeVezaneZaZahtev.toString();
		return obavestenje;
	}

	@XmlElement(required = true)
	protected OrganOdKojegSeTrazi organ;
	@XmlElement(required = true)
	protected TZahtevGradjana.Trazilac trazilac;
	@XmlElement(name = "informacije_vezane_za_zahtev", required = true)
	protected TZahtevGradjana.InformacijeVezaneZaZahtev informacijeVezaneZaZahtev;
	@XmlAttribute(name = "id", required = false)
	@XmlSchemaType(name = "anyURI")
	protected String id;
	@XmlAttribute(name = "vocab", required = false)
	protected String vocab;
	@XmlAttribute(name = "about", required = false)
	@XmlSchemaType(name = "anyURI")
	protected String about;

	public TZahtevGradjana() {
		
	}
	
	public TZahtevGradjana(ZahtevGradjana zg) {
		this.about = zg.getAbout();
		this.id = zg.getId();
		this.vocab = zg.getVocab();

		this.informacijeVezaneZaZahtev = new TZahtevGradjana.InformacijeVezaneZaZahtev();
		this.informacijeVezaneZaZahtev.setDatum(new TZahtevGradjana.InformacijeVezaneZaZahtev.DatumPodnosenja());
		this.informacijeVezaneZaZahtev.getDatum().setDatatype(zg.getInformacijeVezaneZaZahtev().getDatum().getDatatype());
		this.informacijeVezaneZaZahtev.getDatum().setProperty();
		this.informacijeVezaneZaZahtev.getDatum().setValue(zg.getInformacijeVezaneZaZahtev().getDatum().getValue());
		this.informacijeVezaneZaZahtev.setMesto(new TZahtevGradjana.InformacijeVezaneZaZahtev.Mesto());
		this.informacijeVezaneZaZahtev.getMesto().getDatatype();
		this.informacijeVezaneZaZahtev.getMesto().getProperty();
		this.informacijeVezaneZaZahtev.getMesto().getValue();
		this.informacijeVezaneZaZahtev.setOpisZahteva(zg.getInformacijeVezaneZaZahtev().getOpisZahteva());
		
		this.informacijeVezaneZaZahtev.setTipZahteva(new TZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva());
		this.informacijeVezaneZaZahtev.getTipZahteva().setDostavljanjeKopije(zg.getInformacijeVezaneZaZahtev().getTipZahteva().getDostavljanjeKopije() != null ? new TZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva.DostavljanjeKopije() : null);
		if (zg.getInformacijeVezaneZaZahtev().getTipZahteva().getDostavljanjeKopije() != null) {
			this.informacijeVezaneZaZahtev.getTipZahteva().getDostavljanjeKopije().setDrugiNacin(zg.getInformacijeVezaneZaZahtev().getTipZahteva().getDostavljanjeKopije().getDrugiNacin() != null ? new TZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva.DostavljanjeKopije.DrugiNacin() : null);
			if (this.informacijeVezaneZaZahtev.getTipZahteva().getDostavljanjeKopije().getDrugiNacin().getOpisDostave() != null) {
				this.informacijeVezaneZaZahtev.getTipZahteva().getDostavljanjeKopije().getDrugiNacin().setOpisDostave(zg.getInformacijeVezaneZaZahtev().getTipZahteva().getDostavljanjeKopije().getDrugiNacin().getOpisDostave());
			}
			this.informacijeVezaneZaZahtev.getTipZahteva().getDostavljanjeKopije().setEPosta(zg.getInformacijeVezaneZaZahtev().getTipZahteva().getDostavljanjeKopije().getEPosta() != null ? new TZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva.DostavljanjeKopije.EPosta() : null);
			this.informacijeVezaneZaZahtev.getTipZahteva().getDostavljanjeKopije().setFaks(zg.getInformacijeVezaneZaZahtev().getTipZahteva().getDostavljanjeKopije().getFaks() != null ? new TZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva.DostavljanjeKopije.Faks() : null);
			this.informacijeVezaneZaZahtev.getTipZahteva().getDostavljanjeKopije().setPosta(zg.getInformacijeVezaneZaZahtev().getTipZahteva().getDostavljanjeKopije().getPosta() != null ? new TZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva.DostavljanjeKopije.Posta() : null);
		}
		this.informacijeVezaneZaZahtev.getTipZahteva().setKopijuDokumenta(zg.getInformacijeVezaneZaZahtev().getTipZahteva().getKopijuDokumenta() != null ? new TZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva.KopijuDokumenta() : null);
		this.informacijeVezaneZaZahtev.getTipZahteva().setObavestenjePosedovanjaInformacije(zg.getInformacijeVezaneZaZahtev().getTipZahteva().getObavestenjePosedovanjaInformacije() != null ? new TZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva.ObavestenjePosedovanjaInformacije() : null);
		this.informacijeVezaneZaZahtev.getTipZahteva().setUvidUDokument(zg.getInformacijeVezaneZaZahtev().getTipZahteva().getUvidUDokument() != null ? new TZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva.UvidUDokument() : null);
		
		this.organ = new OrganOdKojegSeTrazi();
		this.organ.setAdresa(zg.getOrgan().getAdresa());
		this.organ.setContent(zg.getOrgan().getContent());
		this.organ.setNaziv(zg.getOrgan().getNaziv());
		this.organ.setProperty();
		
		this.trazilac = new Trazilac();
		this.trazilac.setContent(zg.getTrazilac().getContent());
		this.trazilac.setDrugiPodatakZaKontakt(zg.getTrazilac().getDrugiPodatakZaKontakt());
		this.trazilac.setLice(zg.getTrazilac().getLice());
		this.trazilac.setProperty();
	}
	
	/**
	 * Gets the value of the organ property.
	 * 
	 * @return possible object is {@link TPravnoLice }
	 * 
	 */
	public OrganOdKojegSeTrazi getOrgan() {
		return organ;
	}

	/**
	 * Sets the value of the organ property.
	 * 
	 * @param value allowed object is {@link TPravnoLice }
	 * 
	 */
	public void setOrgan(OrganOdKojegSeTrazi value) {
		this.organ = value;
	}

	/**
	 * Gets the value of the trazilac property.
	 * 
	 * @return possible object is {@link TZahtevGradjana.Trazilac }
	 * 
	 */
	public TZahtevGradjana.Trazilac getTrazilac() {
		return trazilac;
	}

	/**
	 * Sets the value of the trazilac property.
	 * 
	 * @param value allowed object is {@link TZahtevGradjana.Trazilac }
	 * 
	 */
	public void setTrazilac(TZahtevGradjana.Trazilac value) {
		this.trazilac = value;
	}

	/**
	 * Gets the value of the informacijeVezaneZaZahtev property.
	 * 
	 * @return possible object is {@link TZahtevGradjana.InformacijeVezaneZaZahtev }
	 * 
	 */
	public TZahtevGradjana.InformacijeVezaneZaZahtev getInformacijeVezaneZaZahtev() {
		return informacijeVezaneZaZahtev;
	}

	/**
	 * Sets the value of the informacijeVezaneZaZahtev property.
	 * 
	 * @param value allowed object is
	 *              {@link TZahtevGradjana.InformacijeVezaneZaZahtev }
	 * 
	 */
	public void setInformacijeVezaneZaZahtev(TZahtevGradjana.InformacijeVezaneZaZahtev value) {
		this.informacijeVezaneZaZahtev = value;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = "http://localhost:4200/zahtev/" + id;
	}

	public String getVocab() {
		if (vocab == null) {
			return "http://www.projekat.org/predicate";
		} else {
			return vocab;
		}
	}

	/**
	 * Sets the value of the vocab property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setVocab() {
		this.vocab = "http://www.projekat.org/predicate";
	}

	/**
	 * Gets the value of the about property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAbout() {
		return about;
	}

	/**
	 * Sets the value of the about property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setAbout(String value) {
		this.about = "http://localhost:4200/zahtev/" + value;
	}

	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "")
	public static class OrganOdKojegSeTrazi extends TPravnoLice {

		@XmlAttribute(name = "property", required = false)
		protected String property;
		@XmlAttribute(name = "content", required = false)
		protected String content;

		/**
		 * Gets the value of the property property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getProperty() {
			if (property == null) {
				return "pred:organ_od_kojeg_se_trazi";
			} else {
				return property;
			}
		}

		/**
		 * Sets the value of the property property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setProperty() {
			this.property = "pred:organ_od_kojeg_se_trazi";
		}

		/**
		 * Gets the value of the datatype property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getContent() {
			return content;
		}

		/**
		 * Sets the value of the datatype property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setContent(String value) {
			this.content = value;
		}

	}

	/**
	 * &lt;p&gt;Java class for anonymous complex type.
	 * 
	 * &lt;p&gt;The following schema fragment specifies the expected content
	 * contained within this class.
	 * 
	 * &lt;pre&gt; &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
	 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
	 * &amp;lt;sequence&amp;gt; &amp;lt;element name="tip_zahteva"&amp;gt;
	 * &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
	 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
	 * &amp;lt;sequence&amp;gt; &amp;lt;element
	 * name="obavestenje_posedovanja_informacije" minOccurs="0"&amp;gt;
	 * &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
	 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
	 * &amp;lt;attribute name="tip" type="{http://www.w3.org/2001/XMLSchema}string"
	 * fixed="obave�tenje da li poseduje tra�enu informaciju" /&amp;gt;
	 * &amp;lt;/restriction&amp;gt; &amp;lt;/complexContent&amp;gt;
	 * &amp;lt;/complexType&amp;gt; &amp;lt;/element&amp;gt; &amp;lt;element
	 * name="uvid_u_dokument" minOccurs="0"&amp;gt; &amp;lt;complexType&amp;gt;
	 * &amp;lt;complexContent&amp;gt; &amp;lt;restriction
	 * base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt; &amp;lt;attribute
	 * name="tip" type="{http://www.w3.org/2001/XMLSchema}string" fixed="uvid u
	 * dokument koji sadr�i tra�enu informaciju" /&amp;gt;
	 * &amp;lt;/restriction&amp;gt; &amp;lt;/complexContent&amp;gt;
	 * &amp;lt;/complexType&amp;gt; &amp;lt;/element&amp;gt; &amp;lt;element
	 * name="kopiju_dokumenta" minOccurs="0"&amp;gt; &amp;lt;complexType&amp;gt;
	 * &amp;lt;complexContent&amp;gt; &amp;lt;restriction
	 * base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt; &amp;lt;attribute
	 * name="tip" type="{http://www.w3.org/2001/XMLSchema}string" fixed="kopiju
	 * dokumenta koji sadr�i tra�enu informaciju" /&amp;gt;
	 * &amp;lt;/restriction&amp;gt; &amp;lt;/complexContent&amp;gt;
	 * &amp;lt;/complexType&amp;gt; &amp;lt;/element&amp;gt; &amp;lt;element
	 * name="dostavljanje_kopije" minOccurs="0"&amp;gt; &amp;lt;complexType&amp;gt;
	 * &amp;lt;complexContent&amp;gt; &amp;lt;restriction
	 * base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
	 * &amp;lt;sequence&amp;gt; &amp;lt;element name="posta" minOccurs="0"&amp;gt;
	 * &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
	 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
	 * &amp;lt;attribute name="tip" type="{http://www.w3.org/2001/XMLSchema}string"
	 * fixed="po�tom" /&amp;gt; &amp;lt;/restriction&amp;gt;
	 * &amp;lt;/complexContent&amp;gt; &amp;lt;/complexType&amp;gt;
	 * &amp;lt;/element&amp;gt; &amp;lt;element name="faks" minOccurs="0"&amp;gt;
	 * &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
	 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
	 * &amp;lt;attribute name="tip" type="{http://www.w3.org/2001/XMLSchema}string"
	 * fixed="faksom" /&amp;gt; &amp;lt;/restriction&amp;gt;
	 * &amp;lt;/complexContent&amp;gt; &amp;lt;/complexType&amp;gt;
	 * &amp;lt;/element&amp;gt; &amp;lt;element name="e-posta" minOccurs="0"&amp;gt;
	 * &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
	 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
	 * &amp;lt;attribute name="tip" type="{http://www.w3.org/2001/XMLSchema}string"
	 * fixed="elektronskom postom" /&amp;gt; &amp;lt;/restriction&amp;gt;
	 * &amp;lt;/complexContent&amp;gt; &amp;lt;/complexType&amp;gt;
	 * &amp;lt;/element&amp;gt; &amp;lt;element name="drugi_nacin"
	 * minOccurs="0"&amp;gt; &amp;lt;complexType&amp;gt;
	 * &amp;lt;complexContent&amp;gt; &amp;lt;restriction
	 * base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
	 * &amp;lt;sequence&amp;gt; &amp;lt;element name="opis_dostave"&amp;gt;
	 * &amp;lt;simpleType&amp;gt; &amp;lt;restriction
	 * base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt; &amp;lt;minLength
	 * value="1"/&amp;gt; &amp;lt;maxLength value="30"/&amp;gt;
	 * &amp;lt;/restriction&amp;gt; &amp;lt;/simpleType&amp;gt;
	 * &amp;lt;/element&amp;gt; &amp;lt;/sequence&amp;gt; &amp;lt;attribute
	 * name="tip" type="{http://www.w3.org/2001/XMLSchema}string" fixed="na drugi
	 * nacin" /&amp;gt; &amp;lt;/restriction&amp;gt; &amp;lt;/complexContent&amp;gt;
	 * &amp;lt;/complexType&amp;gt; &amp;lt;/element&amp;gt;
	 * &amp;lt;/sequence&amp;gt; &amp;lt;attribute name="tip"
	 * type="{http://www.w3.org/2001/XMLSchema}string" fixed="dostavljanje kopije
	 * dokumenta koji sad�i tra�enu informaciju" /&amp;gt;
	 * &amp;lt;/restriction&amp;gt; &amp;lt;/complexContent&amp;gt;
	 * &amp;lt;/complexType&amp;gt; &amp;lt;/element&amp;gt;
	 * &amp;lt;/sequence&amp;gt; &amp;lt;/restriction&amp;gt;
	 * &amp;lt;/complexContent&amp;gt; &amp;lt;/complexType&amp;gt;
	 * &amp;lt;/element&amp;gt; &amp;lt;element name="opis_zahteva"
	 * type="{http://www.w3.org/2001/XMLSchema}string"/&amp;gt; &amp;lt;element
	 * name="mesto" type="{http://www.w3.org/2001/XMLSchema}string"/&amp;gt;
	 * &amp;lt;element name="datum"
	 * type="{http://www.w3.org/2001/XMLSchema}date"/&amp;gt;
	 * &amp;lt;/sequence&amp;gt; &amp;lt;/restriction&amp;gt;
	 * &amp;lt;/complexContent&amp;gt; &amp;lt;/complexType&amp;gt; &lt;/pre&gt;
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "tipZahteva", "opisZahteva", "mesto", "datum" })
	public static class InformacijeVezaneZaZahtev {

		@Override
		public String toString() {
			return String.format("Opis zahteva: %s.\nMesto podnosenja zahteva: %s.\nDatum podnosenja zahteva: %s.\n",
					opisZahteva, mesto, datum) + tipZahteva.toString();
		}

		@XmlElement(name = "tip_zahteva", required = true)
		protected TZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva tipZahteva;
		@XmlElement(name = "opis_zahteva", required = true)
		protected String opisZahteva;
		@XmlElement(required = true)
		protected Mesto mesto;
		@XmlElement(required = true)
		@XmlSchemaType(name = "date")
		protected DatumPodnosenja datum;

		/**
		 * Gets the value of the tipZahteva property.
		 * 
		 * @return possible object is
		 *         {@link TZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva }
		 * 
		 */
		public TZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva getTipZahteva() {
			return tipZahteva;
		}

		/**
		 * Sets the value of the tipZahteva property.
		 * 
		 * @param value allowed object is
		 *              {@link TZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva }
		 * 
		 */
		public void setTipZahteva(TZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva value) {
			this.tipZahteva = value;
		}

		/**
		 * Gets the value of the opisZahteva property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getOpisZahteva() {
			return opisZahteva;
		}

		/**
		 * Sets the value of the opisZahteva property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setOpisZahteva(String value) {
			this.opisZahteva = value;
		}

		/**
		 * Gets the value of the mesto property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public Mesto getMesto() {
			return mesto;
		}

		/**
		 * Sets the value of the mesto property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setMesto(Mesto value) {
			this.mesto = value;
		}

		/**
		 * Gets the value of the datum property.
		 * 
		 * @return possible object is {@link XMLGregorianCalendar }
		 * 
		 */
		public DatumPodnosenja getDatum() {
			return datum;
		}

		/**
		 * Sets the value of the datum property.
		 * 
		 * @param value allowed object is {@link XMLGregorianCalendar }
		 * 
		 */
		public void setDatum(DatumPodnosenja value) {
			this.datum = value;
		}

		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "value" })
		public static class Mesto {

			@XmlValue
			protected String value;
			@XmlAttribute(name = "property", required = true)
			protected String property;
			@XmlAttribute(name = "datatype", required = true)
			protected String datatype;

			/**
			 * Gets the value of the value property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getValue() {
				return value;
			}

			/**
			 * Sets the value of the value property.
			 * 
			 * @param value allowed object is {@link String }
			 * 
			 */
			public void setValue(String value) {
				this.value = value;
			}

			/**
			 * Gets the value of the property property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getProperty() {
				if (property == null) {
					return "pred:mesto_podnosenja";
				} else {
					return property;
				}
			}

			/**
			 * Sets the value of the property property.
			 * 
			 * @param value allowed object is {@link String }
			 * 
			 */
			public void setProperty() {
				this.property = "pred:mesto_podnosenja";
				;
			}

			/**
			 * Gets the value of the datatype property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getDatatype() {
				if (datatype == null) {
					return "xs:string";
				} else {
					return datatype;
				}
			}

			/**
			 * Sets the value of the datatype property.
			 * 
			 * @param value allowed object is {@link String }
			 * 
			 */
			public void setDatatype(String value) {
				this.datatype = value;
			}

		}

		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "value" })
		public static class DatumPodnosenja {

			@XmlValue
			@XmlSchemaType(name = "date")
			protected XMLGregorianCalendar value;
			@XmlAttribute(name = "property", required = false)
			protected String property;
			@XmlAttribute(name = "datatype", required = false)
			protected String datatype;

			/**
			 * Gets the value of the value property.
			 * 
			 * @return possible object is {@link XMLGregorianCalendar }
			 * 
			 */
			public XMLGregorianCalendar getValue() {
				return value;
			}

			/**
			 * Sets the value of the value property.
			 * 
			 * @param value allowed object is {@link XMLGregorianCalendar }
			 * 
			 */
			public void setValue(XMLGregorianCalendar value) {
				this.value = value;
			}

			/**
			 * Gets the value of the property property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getProperty() {
				if (property == null) {
					return "pred:datum_podnosenja";
				} else {
					return property;
				}
			}

			/**
			 * Sets the value of the property property.
			 * 
			 * @param value allowed object is {@link String }
			 * 
			 */
			public void setProperty() {
				this.property = "pred:datum_podnosenja";
			}

			/**
			 * Gets the value of the datatype property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getDatatype() {
				if (datatype == null) {
					return "xs:dateTime";
				} else {
					return datatype;
				}
			}

			/**
			 * Sets the value of the datatype property.
			 * 
			 * @param value allowed object is {@link String }
			 * 
			 */
			public void setDatatype(String value) {
				this.datatype = value;
			}

		}

		/**
		 * &lt;p&gt;Java class for anonymous complex type.
		 * 
		 * &lt;p&gt;The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * &lt;pre&gt; &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
		 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
		 * &amp;lt;sequence&amp;gt; &amp;lt;element
		 * name="obavestenje_posedovanja_informacije" minOccurs="0"&amp;gt;
		 * &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
		 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
		 * &amp;lt;attribute name="tip" type="{http://www.w3.org/2001/XMLSchema}string"
		 * fixed="obave�tenje da li poseduje tra�enu informaciju" /&amp;gt;
		 * &amp;lt;/restriction&amp;gt; &amp;lt;/complexContent&amp;gt;
		 * &amp;lt;/complexType&amp;gt; &amp;lt;/element&amp;gt; &amp;lt;element
		 * name="uvid_u_dokument" minOccurs="0"&amp;gt; &amp;lt;complexType&amp;gt;
		 * &amp;lt;complexContent&amp;gt; &amp;lt;restriction
		 * base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt; &amp;lt;attribute
		 * name="tip" type="{http://www.w3.org/2001/XMLSchema}string" fixed="uvid u
		 * dokument koji sadr�i tra�enu informaciju" /&amp;gt;
		 * &amp;lt;/restriction&amp;gt; &amp;lt;/complexContent&amp;gt;
		 * &amp;lt;/complexType&amp;gt; &amp;lt;/element&amp;gt; &amp;lt;element
		 * name="kopiju_dokumenta" minOccurs="0"&amp;gt; &amp;lt;complexType&amp;gt;
		 * &amp;lt;complexContent&amp;gt; &amp;lt;restriction
		 * base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt; &amp;lt;attribute
		 * name="tip" type="{http://www.w3.org/2001/XMLSchema}string" fixed="kopiju
		 * dokumenta koji sadr�i tra�enu informaciju" /&amp;gt;
		 * &amp;lt;/restriction&amp;gt; &amp;lt;/complexContent&amp;gt;
		 * &amp;lt;/complexType&amp;gt; &amp;lt;/element&amp;gt; &amp;lt;element
		 * name="dostavljanje_kopije" minOccurs="0"&amp;gt; &amp;lt;complexType&amp;gt;
		 * &amp;lt;complexContent&amp;gt; &amp;lt;restriction
		 * base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
		 * &amp;lt;sequence&amp;gt; &amp;lt;element name="posta" minOccurs="0"&amp;gt;
		 * &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
		 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
		 * &amp;lt;attribute name="tip" type="{http://www.w3.org/2001/XMLSchema}string"
		 * fixed="po�tom" /&amp;gt; &amp;lt;/restriction&amp;gt;
		 * &amp;lt;/complexContent&amp;gt; &amp;lt;/complexType&amp;gt;
		 * &amp;lt;/element&amp;gt; &amp;lt;element name="faks" minOccurs="0"&amp;gt;
		 * &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
		 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
		 * &amp;lt;attribute name="tip" type="{http://www.w3.org/2001/XMLSchema}string"
		 * fixed="faksom" /&amp;gt; &amp;lt;/restriction&amp;gt;
		 * &amp;lt;/complexContent&amp;gt; &amp;lt;/complexType&amp;gt;
		 * &amp;lt;/element&amp;gt; &amp;lt;element name="e-posta" minOccurs="0"&amp;gt;
		 * &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
		 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
		 * &amp;lt;attribute name="tip" type="{http://www.w3.org/2001/XMLSchema}string"
		 * fixed="elektronskom postom" /&amp;gt; &amp;lt;/restriction&amp;gt;
		 * &amp;lt;/complexContent&amp;gt; &amp;lt;/complexType&amp;gt;
		 * &amp;lt;/element&amp;gt; &amp;lt;element name="drugi_nacin"
		 * minOccurs="0"&amp;gt; &amp;lt;complexType&amp;gt;
		 * &amp;lt;complexContent&amp;gt; &amp;lt;restriction
		 * base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
		 * &amp;lt;sequence&amp;gt; &amp;lt;element name="opis_dostave"&amp;gt;
		 * &amp;lt;simpleType&amp;gt; &amp;lt;restriction
		 * base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt; &amp;lt;minLength
		 * value="1"/&amp;gt; &amp;lt;maxLength value="30"/&amp;gt;
		 * &amp;lt;/restriction&amp;gt; &amp;lt;/simpleType&amp;gt;
		 * &amp;lt;/element&amp;gt; &amp;lt;/sequence&amp;gt; &amp;lt;attribute
		 * name="tip" type="{http://www.w3.org/2001/XMLSchema}string" fixed="na drugi
		 * nacin" /&amp;gt; &amp;lt;/restriction&amp;gt; &amp;lt;/complexContent&amp;gt;
		 * &amp;lt;/complexType&amp;gt; &amp;lt;/element&amp;gt;
		 * &amp;lt;/sequence&amp;gt; &amp;lt;attribute name="tip"
		 * type="{http://www.w3.org/2001/XMLSchema}string" fixed="dostavljanje kopije
		 * dokumenta koji sad�i tra�enu informaciju" /&amp;gt;
		 * &amp;lt;/restriction&amp;gt; &amp;lt;/complexContent&amp;gt;
		 * &amp;lt;/complexType&amp;gt; &amp;lt;/element&amp;gt;
		 * &amp;lt;/sequence&amp;gt; &amp;lt;/restriction&amp;gt;
		 * &amp;lt;/complexContent&amp;gt; &amp;lt;/complexType&amp;gt; &lt;/pre&gt;
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "obavestenjePosedovanjaInformacije", "uvidUDokument", "kopijuDokumenta",
				"dostavljanjeKopije" })
		public static class TipZahteva {

			@Override
			public String toString() {
				String zahtev = "Zahtevi koje je podnosilac zahteva naveo: \n\t";
				if (obavestenjePosedovanjaInformacije != null) {
					zahtev += obavestenjePosedovanjaInformacije.toString() + "\t";
				}
				if (uvidUDokument != null) {
					zahtev += uvidUDokument.toString() + "\t";
				}
				if (kopijuDokumenta != null) {
					zahtev += kopijuDokumenta.toString() + "\t";
				}
				if (dostavljanjeKopije != null) {
					zahtev += dostavljanjeKopije.toString();
				}
				return zahtev;
			}

			@XmlElement(name = "obavestenje_posedovanja_informacije")
			protected TZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva.ObavestenjePosedovanjaInformacije obavestenjePosedovanjaInformacije;
			@XmlElement(name = "uvid_u_dokument")
			protected TZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva.UvidUDokument uvidUDokument;
			@XmlElement(name = "kopiju_dokumenta")
			protected TZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva.KopijuDokumenta kopijuDokumenta;
			@XmlElement(name = "dostavljanje_kopije")
			protected TZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva.DostavljanjeKopije dostavljanjeKopije;

			/**
			 * Gets the value of the obavestenjePosedovanjaInformacije property.
			 * 
			 * @return possible object is
			 *         {@link TZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva.ObavestenjePosedovanjaInformacije }
			 * 
			 */
			public TZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva.ObavestenjePosedovanjaInformacije getObavestenjePosedovanjaInformacije() {
				return obavestenjePosedovanjaInformacije;
			}

			/**
			 * Sets the value of the obavestenjePosedovanjaInformacije property.
			 * 
			 * @param value allowed object is
			 *              {@link TZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva.ObavestenjePosedovanjaInformacije }
			 * 
			 */
			public void setObavestenjePosedovanjaInformacije(
					TZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva.ObavestenjePosedovanjaInformacije value) {
				this.obavestenjePosedovanjaInformacije = value;
			}

			/**
			 * Gets the value of the uvidUDokument property.
			 * 
			 * @return possible object is
			 *         {@link TZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva.UvidUDokument }
			 * 
			 */
			public TZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva.UvidUDokument getUvidUDokument() {
				return uvidUDokument;
			}

			/**
			 * Sets the value of the uvidUDokument property.
			 * 
			 * @param value allowed object is
			 *              {@link TZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva.UvidUDokument }
			 * 
			 */
			public void setUvidUDokument(TZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva.UvidUDokument value) {
				this.uvidUDokument = value;
			}

			/**
			 * Gets the value of the kopijuDokumenta property.
			 * 
			 * @return possible object is
			 *         {@link TZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva.KopijuDokumenta }
			 * 
			 */
			public TZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva.KopijuDokumenta getKopijuDokumenta() {
				return kopijuDokumenta;
			}

			/**
			 * Sets the value of the kopijuDokumenta property.
			 * 
			 * @param value allowed object is
			 *              {@link TZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva.KopijuDokumenta }
			 * 
			 */
			public void setKopijuDokumenta(TZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva.KopijuDokumenta value) {
				this.kopijuDokumenta = value;
			}

			/**
			 * Gets the value of the dostavljanjeKopije property.
			 * 
			 * @return possible object is
			 *         {@link TZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva.DostavljanjeKopije }
			 * 
			 */
			public TZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva.DostavljanjeKopije getDostavljanjeKopije() {
				return dostavljanjeKopije;
			}

			/**
			 * Sets the value of the dostavljanjeKopije property.
			 * 
			 * @param value allowed object is
			 *              {@link TZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva.DostavljanjeKopije }
			 * 
			 */
			public void setDostavljanjeKopije(
					TZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva.DostavljanjeKopije value) {
				this.dostavljanjeKopije = value;
			}

			/**
			 * &lt;p&gt;Java class for anonymous complex type.
			 * 
			 * &lt;p&gt;The following schema fragment specifies the expected content
			 * contained within this class.
			 * 
			 * &lt;pre&gt; &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
			 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
			 * &amp;lt;sequence&amp;gt; &amp;lt;element name="posta" minOccurs="0"&amp;gt;
			 * &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
			 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
			 * &amp;lt;attribute name="tip" type="{http://www.w3.org/2001/XMLSchema}string"
			 * fixed="po�tom" /&amp;gt; &amp;lt;/restriction&amp;gt;
			 * &amp;lt;/complexContent&amp;gt; &amp;lt;/complexType&amp;gt;
			 * &amp;lt;/element&amp;gt; &amp;lt;element name="faks" minOccurs="0"&amp;gt;
			 * &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
			 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
			 * &amp;lt;attribute name="tip" type="{http://www.w3.org/2001/XMLSchema}string"
			 * fixed="faksom" /&amp;gt; &amp;lt;/restriction&amp;gt;
			 * &amp;lt;/complexContent&amp;gt; &amp;lt;/complexType&amp;gt;
			 * &amp;lt;/element&amp;gt; &amp;lt;element name="e-posta" minOccurs="0"&amp;gt;
			 * &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
			 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
			 * &amp;lt;attribute name="tip" type="{http://www.w3.org/2001/XMLSchema}string"
			 * fixed="elektronskom postom" /&amp;gt; &amp;lt;/restriction&amp;gt;
			 * &amp;lt;/complexContent&amp;gt; &amp;lt;/complexType&amp;gt;
			 * &amp;lt;/element&amp;gt; &amp;lt;element name="drugi_nacin"
			 * minOccurs="0"&amp;gt; &amp;lt;complexType&amp;gt;
			 * &amp;lt;complexContent&amp;gt; &amp;lt;restriction
			 * base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
			 * &amp;lt;sequence&amp;gt; &amp;lt;element name="opis_dostave"&amp;gt;
			 * &amp;lt;simpleType&amp;gt; &amp;lt;restriction
			 * base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt; &amp;lt;minLength
			 * value="1"/&amp;gt; &amp;lt;maxLength value="30"/&amp;gt;
			 * &amp;lt;/restriction&amp;gt; &amp;lt;/simpleType&amp;gt;
			 * &amp;lt;/element&amp;gt; &amp;lt;/sequence&amp;gt; &amp;lt;attribute
			 * name="tip" type="{http://www.w3.org/2001/XMLSchema}string" fixed="na drugi
			 * nacin" /&amp;gt; &amp;lt;/restriction&amp;gt; &amp;lt;/complexContent&amp;gt;
			 * &amp;lt;/complexType&amp;gt; &amp;lt;/element&amp;gt;
			 * &amp;lt;/sequence&amp;gt; &amp;lt;attribute name="tip"
			 * type="{http://www.w3.org/2001/XMLSchema}string" fixed="dostavljanje kopije
			 * dokumenta koji sad�i tra�enu informaciju" /&amp;gt;
			 * &amp;lt;/restriction&amp;gt; &amp;lt;/complexContent&amp;gt;
			 * &amp;lt;/complexType&amp;gt; &lt;/pre&gt;
			 * 
			 * 
			 */
			@XmlAccessorType(XmlAccessType.FIELD)
			@XmlType(name = "", propOrder = { "posta", "faks", "ePosta", "drugiNacin" })
			public static class DostavljanjeKopije {

				@Override
				public String toString() {
					String zahtev = "-dostavljanje kopije dokumenta koji sadr\u017ei tra\u017eenu informaciju:\n\t\tNacini dostave:\n";
					zahtev += posta != null ? posta.toString() : "";
					zahtev += faks != null ? faks.toString() : "";
					zahtev += ePosta != null ? ePosta.toString() : "";
					zahtev += drugiNacin != null ? drugiNacin.toString() : "";
					return zahtev + "\n";
				}

				protected TZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva.DostavljanjeKopije.Posta posta;
				protected TZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva.DostavljanjeKopije.Faks faks;
				@XmlElement(name = "eposta")
				protected TZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva.DostavljanjeKopije.EPosta ePosta;
				@XmlElement(name = "drugi_nacin")
				protected TZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva.DostavljanjeKopije.DrugiNacin drugiNacin;
				@XmlAttribute(name = "tip")
				protected String tip;

				/**
				 * Gets the value of the posta property.
				 * 
				 * @return possible object is
				 *         {@link TZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva.DostavljanjeKopije.Posta }
				 * 
				 */
				public TZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva.DostavljanjeKopije.Posta getPosta() {
					return posta;
				}

				/**
				 * Sets the value of the posta property.
				 * 
				 * @param value allowed object is
				 *              {@link TZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva.DostavljanjeKopije.Posta }
				 * 
				 */
				public void setPosta(
						TZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva.DostavljanjeKopije.Posta value) {
					this.posta = value;
				}

				/**
				 * Gets the value of the faks property.
				 * 
				 * @return possible object is
				 *         {@link TZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva.DostavljanjeKopije.Faks }
				 * 
				 */
				public TZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva.DostavljanjeKopije.Faks getFaks() {
					return faks;
				}

				/**
				 * Sets the value of the faks property.
				 * 
				 * @param value allowed object is
				 *              {@link TZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva.DostavljanjeKopije.Faks }
				 * 
				 */
				public void setFaks(TZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva.DostavljanjeKopije.Faks value) {
					this.faks = value;
				}

				/**
				 * Gets the value of the ePosta property.
				 * 
				 * @return possible object is
				 *         {@link TZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva.DostavljanjeKopije.EPosta }
				 * 
				 */
				public TZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva.DostavljanjeKopije.EPosta getEPosta() {
					return ePosta;
				}

				/**
				 * Sets the value of the ePosta property.
				 * 
				 * @param value allowed object is
				 *              {@link TZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva.DostavljanjeKopije.EPosta }
				 * 
				 */
				public void setEPosta(
						TZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva.DostavljanjeKopije.EPosta value) {
					this.ePosta = value;
				}

				/**
				 * Gets the value of the drugiNacin property.
				 * 
				 * @return possible object is
				 *         {@link TZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva.DostavljanjeKopije.DrugiNacin }
				 * 
				 */
				public TZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva.DostavljanjeKopije.DrugiNacin getDrugiNacin() {
					return drugiNacin;
				}

				/**
				 * Sets the value of the drugiNacin property.
				 * 
				 * @param value allowed object is
				 *              {@link TZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva.DostavljanjeKopije.DrugiNacin }
				 * 
				 */
				public void setDrugiNacin(
						TZahtevGradjana.InformacijeVezaneZaZahtev.TipZahteva.DostavljanjeKopije.DrugiNacin value) {
					this.drugiNacin = value;
				}

				/**
				 * &lt;p&gt;Java class for anonymous complex type.
				 * 
				 * &lt;p&gt;The following schema fragment specifies the expected content
				 * contained within this class.
				 * 
				 * &lt;pre&gt; &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
				 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
				 * &amp;lt;sequence&amp;gt; &amp;lt;element name="opis_dostave"&amp;gt;
				 * &amp;lt;simpleType&amp;gt; &amp;lt;restriction
				 * base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt; &amp;lt;minLength
				 * value="1"/&amp;gt; &amp;lt;maxLength value="30"/&amp;gt;
				 * &amp;lt;/restriction&amp;gt; &amp;lt;/simpleType&amp;gt;
				 * &amp;lt;/element&amp;gt; &amp;lt;/sequence&amp;gt; &amp;lt;attribute
				 * name="tip" type="{http://www.w3.org/2001/XMLSchema}string" fixed="na drugi
				 * nacin" /&amp;gt; &amp;lt;/restriction&amp;gt; &amp;lt;/complexContent&amp;gt;
				 * &amp;lt;/complexType&amp;gt; &lt;/pre&gt;
				 * 
				 * 
				 */
				@XmlAccessorType(XmlAccessType.FIELD)
				@XmlType(name = "", propOrder = { "opisDostave" })
				public static class DrugiNacin {

					@Override
					public String toString() {
						return String.format("\t\t\tna drugi nacin: %s.\n", opisDostave);
					}

					@XmlElement(name = "opis_dostave", required = true)
					protected String opisDostave;

					/**
					 * Gets the value of the opisDostave property.
					 * 
					 * @return possible object is {@link String }
					 * 
					 */
					public String getOpisDostave() {
						return opisDostave;
					}

					/**
					 * Sets the value of the opisDostave property.
					 * 
					 * @param value allowed object is {@link String }
					 * 
					 */
					public void setOpisDostave(String value) {
						this.opisDostave = value;
					}
				}

				/**
				 * &lt;p&gt;Java class for anonymous complex type.
				 * 
				 * &lt;p&gt;The following schema fragment specifies the expected content
				 * contained within this class.
				 * 
				 * &lt;pre&gt; &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
				 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
				 * &amp;lt;attribute name="tip" type="{http://www.w3.org/2001/XMLSchema}string"
				 * fixed="elektronskom postom" /&amp;gt; &amp;lt;/restriction&amp;gt;
				 * &amp;lt;/complexContent&amp;gt; &amp;lt;/complexType&amp;gt; &lt;/pre&gt;
				 * 
				 * 
				 */
				@XmlAccessorType(XmlAccessType.FIELD)
				@XmlType(name = "")
				public static class EPosta {

					@Override
					public String toString() {
						return "\t\t\telektronskom postom\n";
					}
				}

				/**
				 * &lt;p&gt;Java class for anonymous complex type.
				 * 
				 * &lt;p&gt;The following schema fragment specifies the expected content
				 * contained within this class.
				 * 
				 * &lt;pre&gt; &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
				 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
				 * &amp;lt;attribute name="tip" type="{http://www.w3.org/2001/XMLSchema}string"
				 * fixed="faksom" /&amp;gt; &amp;lt;/restriction&amp;gt;
				 * &amp;lt;/complexContent&amp;gt; &amp;lt;/complexType&amp;gt; &lt;/pre&gt;
				 * 
				 * 
				 */
				@XmlAccessorType(XmlAccessType.FIELD)
				@XmlType(name = "")
				public static class Faks {

					@Override
					public String toString() {
						return "\t\t\tfaksom\n";
					}

				}

				/**
				 * &lt;p&gt;Java class for anonymous complex type.
				 * 
				 * &lt;p&gt;The following schema fragment specifies the expected content
				 * contained within this class.
				 * 
				 * &lt;pre&gt; &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
				 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
				 * &amp;lt;attribute name="tip" type="{http://www.w3.org/2001/XMLSchema}string"
				 * fixed="po�tom" /&amp;gt; &amp;lt;/restriction&amp;gt;
				 * &amp;lt;/complexContent&amp;gt; &amp;lt;/complexType&amp;gt; &lt;/pre&gt;
				 * 
				 * 
				 */
				@XmlAccessorType(XmlAccessType.FIELD)
				@XmlType(name = "")
				public static class Posta {

					@Override
					public String toString() {
						return "\t\t\tpo\u0161tom\n";
					}

				}

			}

			/**
			 * &lt;p&gt;Java class for anonymous complex type.
			 * 
			 * &lt;p&gt;The following schema fragment specifies the expected content
			 * contained within this class.
			 * 
			 * &lt;pre&gt; &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
			 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
			 * &amp;lt;attribute name="tip" type="{http://www.w3.org/2001/XMLSchema}string"
			 * fixed="kopiju dokumenta koji sadr�i tra�enu informaciju" /&amp;gt;
			 * &amp;lt;/restriction&amp;gt; &amp;lt;/complexContent&amp;gt;
			 * &amp;lt;/complexType&amp;gt; &lt;/pre&gt;
			 * 
			 * 
			 */
			@XmlAccessorType(XmlAccessType.FIELD)
			@XmlType(name = "")
			public static class KopijuDokumenta {

				@Override
				public String toString() {
					return "-kopiju dokumenta koji sadr\u017ei tra\u017eenu informaciju\n";
				}
			}

			/**
			 * &lt;p&gt;Java class for anonymous complex type.
			 * 
			 * &lt;p&gt;The following schema fragment specifies the expected content
			 * contained within this class.
			 * 
			 * &lt;pre&gt; &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
			 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
			 * &amp;lt;attribute name="tip" type="{http://www.w3.org/2001/XMLSchema}string"
			 * fixed="obave�tenje da li poseduje tra�enu informaciju" /&amp;gt;
			 * &amp;lt;/restriction&amp;gt; &amp;lt;/complexContent&amp;gt;
			 * &amp;lt;/complexType&amp;gt; &lt;/pre&gt;
			 * 
			 * 
			 */
			@XmlAccessorType(XmlAccessType.FIELD)
			@XmlType(name = "")
			public static class ObavestenjePosedovanjaInformacije {

				@Override
				public String toString() {
					return "-obave\u0161tenje da li poseduje tra\u017eenu informaciju\n";
				}

			}

			/**
			 * &lt;p&gt;Java class for anonymous complex type.
			 * 
			 * &lt;p&gt;The following schema fragment specifies the expected content
			 * contained within this class.
			 * 
			 * &lt;pre&gt; &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
			 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
			 * &amp;lt;attribute name="tip" type="{http://www.w3.org/2001/XMLSchema}string"
			 * fixed="uvid u dokument koji sadr�i tra�enu informaciju" /&amp;gt;
			 * &amp;lt;/restriction&amp;gt; &amp;lt;/complexContent&amp;gt;
			 * &amp;lt;/complexType&amp;gt; &lt;/pre&gt;
			 * 
			 * 
			 */
			@XmlAccessorType(XmlAccessType.FIELD)
			@XmlType(name = "")
			public static class UvidUDokument {

				@Override
				public String toString() {
					return "-uvid u dokument koji sadr\u017ei tra\u017eenu informaciju\n";
				}
			}

		}

	}

	/**
	 * &lt;p&gt;Java class for anonymous complex type.
	 * 
	 * &lt;p&gt;The following schema fragment specifies the expected content
	 * contained within this class.
	 * 
	 * &lt;pre&gt; &amp;lt;complexType&amp;gt; &amp;lt;complexContent&amp;gt;
	 * &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
	 * &amp;lt;sequence&amp;gt; &amp;lt;element name="drugi_podatak_za_kontakt"
	 * minOccurs="0"&amp;gt; &amp;lt;simpleType&amp;gt; &amp;lt;restriction
	 * base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt; &amp;lt;minLength
	 * value="1"/&amp;gt; &amp;lt;maxLength value="30"/&amp;gt;
	 * &amp;lt;/restriction&amp;gt; &amp;lt;/simpleType&amp;gt;
	 * &amp;lt;/element&amp;gt; &amp;lt;element name="lice"
	 * type="{http://www.projekat.org/zahtev}TLice"/&amp;gt;
	 * &amp;lt;/sequence&amp;gt; &amp;lt;/restriction&amp;gt;
	 * &amp;lt;/complexContent&amp;gt; &amp;lt;/complexType&amp;gt; &lt;/pre&gt;
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "lice", "drugiPodatakZaKontakt" })
	public static class Trazilac {

		@Override
		public String toString() {
			return lice.toString() + String.format("\tDrugi podatak za kontakt: %s.\n", drugiPodatakZaKontakt);
		}

		@XmlElement(required = true)
		protected TLice lice;
		@XmlElement(name = "drugi_podatak_za_kontakt")
		protected String drugiPodatakZaKontakt;
		@XmlAttribute(name = "property", required = false)
		protected String property;
		@XmlAttribute(name = "content", required = false)
		protected String content;

		/**
		 * Gets the value of the drugiPodatakZaKontakt property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getDrugiPodatakZaKontakt() {
			return drugiPodatakZaKontakt;
		}

		/**
		 * Sets the value of the drugiPodatakZaKontakt property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setDrugiPodatakZaKontakt(String value) {
			this.drugiPodatakZaKontakt = value;
		}

		/**
		 * Gets the value of the lice property.
		 * 
		 * @return possible object is {@link TLice }
		 * 
		 */
		public TLice getLice() {
			return lice;
		}

		/**
		 * Sets the value of the lice property.
		 * 
		 * @param value allowed object is {@link TLice }
		 * 
		 */
		public void setLice(TLice value) {
			this.lice = value;
		}

		public String getProperty() {
			if (property == null) {
				return "pred:podnosilac_zahteva";
			} else {
				return property;
			}
		}

		/**
		 * Sets the value of the property property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setProperty() {
			this.property = "pred:podnosilac_zahteva";
		}

		/**
		 * Gets the value of the resource property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getContent() {
			return content;
		}

		/**
		 * Sets the value of the resource property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setContent(String value) {
			this.content = value;
		}

		public Trazilac() {
			super();
		}

	}

}
