//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.06 at 02:59:25 PM CET 
//


package projectXML.team9.models.zalbaCutanje;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gen2 package. 
 * &lt;p&gt;An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gen2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ZalbaNaCutanje }
     * 
     */
    public ZalbaNaCutanje createZalbaNaCutanje() {
        return new ZalbaNaCutanje();
    }

    /**
     * Create an instance of {@link ZalbaNaCutanje.PodaciOZalbi }
     * 
     */
    public ZalbaNaCutanje.PodaciOZalbi createZalbaNaCutanjePodaciOZalbi() {
        return new ZalbaNaCutanje.PodaciOZalbi();
    }

    /**
     * Create an instance of {@link ZalbaNaCutanje.PodaciOZahtevu }
     * 
     */
    public ZalbaNaCutanje.PodaciOZahtevu createZalbaNaCutanjePodaciOZahtevu() {
        return new ZalbaNaCutanje.PodaciOZahtevu();
    }

    /**
     * Create an instance of {@link TAdresa }
     * 
     */
    public TAdresa createTAdresa() {
        return new TAdresa();
    }

    /**
     * Create an instance of {@link TPravnoLice }
     * 
     */
    public TPravnoLice createTPravnoLice() {
        return new TPravnoLice();
    }

    /**
     * Create an instance of {@link TFizickoLice }
     * 
     */
    public TFizickoLice createTFizickoLice() {
        return new TFizickoLice();
    }

    /**
     * Create an instance of {@link ZalbaNaCutanje.PodaciOZalbi.PodnosilacZalbe }
     * 
     */
    public ZalbaNaCutanje.PodaciOZalbi.PodnosilacZalbe createZalbaNaCutanjePodaciOZalbiPodnosilacZalbe() {
        return new ZalbaNaCutanje.PodaciOZalbi.PodnosilacZalbe();
    }

    /**
     * Create an instance of {@link ZalbaNaCutanje.PodaciOZahtevu.Zahtevi }
     * 
     */
    public ZalbaNaCutanje.PodaciOZahtevu.Zahtevi createZalbaNaCutanjePodaciOZahtevuZahtevi() {
        return new ZalbaNaCutanje.PodaciOZahtevu.Zahtevi();
    }

}
