//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.04 at 08:48:29 PM CET 
//


package projectXML.team9.models.resenje;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the projectXML.team9.models.resenje package. 
 * &lt;p&gt;An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: projectXML.team9.models.resenje
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OdlukaPoverioca }
     * 
     */
    public OdlukaPoverioca createOdlukaPoverioca() {
        return new OdlukaPoverioca();
    }

    /**
     * Create an instance of {@link OdlukaPoverioca.OpisŽalbe }
     * 
     */
    public OdlukaPoverioca.OpisŽalbe createOdlukaPoveriocaOpisŽalbe() {
        return new OdlukaPoverioca.OpisŽalbe();
    }

    /**
     * Create an instance of {@link TMultiParagraf }
     * 
     */
    public TMultiParagraf createTMultiParagraf() {
        return new TMultiParagraf();
    }

    /**
     * Create an instance of {@link OdlukaPoverioca.Obrazloženje }
     * 
     */
    public OdlukaPoverioca.Obrazloženje createOdlukaPoveriocaObrazloženje() {
        return new OdlukaPoverioca.Obrazloženje();
    }

    /**
     * Create an instance of {@link TLice }
     * 
     */
    public TLice createTLice() {
        return new TLice();
    }

    /**
     * Create an instance of {@link TŽalioc }
     * 
     */
    public TŽalioc createTŽalioc() {
        return new TŽalioc();
    }

    /**
     * Create an instance of {@link TAdresa }
     * 
     */
    public TAdresa createTAdresa() {
        return new TAdresa();
    }

    /**
     * Create an instance of {@link OdlukaPoverioca.OpisŽalbe.Organ }
     * 
     */
    public OdlukaPoverioca.OpisŽalbe.Organ createOdlukaPoveriocaOpisŽalbeOrgan() {
        return new OdlukaPoverioca.OpisŽalbe.Organ();
    }

}
