//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.10 at 07:48:35 PM CET 
//


package projectXML.team9.models.resenje;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import projectXML.team9.models.common.TAdresa;
import projectXML.team9.models.common.TFizickoLice;


/**
 * &lt;p&gt;Java class for anonymous complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *       &amp;lt;sequence&amp;gt;
 *         &amp;lt;element name="opis_Zalbe"&amp;gt;
 *           &amp;lt;complexType&amp;gt;
 *             &amp;lt;complexContent&amp;gt;
 *               &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *                 &amp;lt;sequence&amp;gt;
 *                   &amp;lt;element name="Zalioc" type="{http://www.projekat.org/common}TFizicko_lice"/&amp;gt;
 *                   &amp;lt;element name="organ"&amp;gt;
 *                     &amp;lt;complexType&amp;gt;
 *                       &amp;lt;complexContent&amp;gt;
 *                         &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *                           &amp;lt;sequence&amp;gt;
 *                             &amp;lt;element name="naziv"&amp;gt;
 *                               &amp;lt;simpleType&amp;gt;
 *                                 &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt;
 *                                   &amp;lt;minLength value="1"/&amp;gt;
 *                                 &amp;lt;/restriction&amp;gt;
 *                               &amp;lt;/simpleType&amp;gt;
 *                             &amp;lt;/element&amp;gt;
 *                             &amp;lt;element name="adresa" type="{http://www.projekat.org/common}TAdresa"/&amp;gt;
 *                           &amp;lt;/sequence&amp;gt;
 *                         &amp;lt;/restriction&amp;gt;
 *                       &amp;lt;/complexContent&amp;gt;
 *                     &amp;lt;/complexType&amp;gt;
 *                   &amp;lt;/element&amp;gt;
 *                   &amp;lt;element name="datum_Zalbe" type="{http://www.w3.org/2001/XMLSchema}date"/&amp;gt;
 *                   &amp;lt;element name="ceo_opis"&amp;gt;
 *                     &amp;lt;simpleType&amp;gt;
 *                       &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt;
 *                         &amp;lt;minLength value="1"/&amp;gt;
 *                       &amp;lt;/restriction&amp;gt;
 *                     &amp;lt;/simpleType&amp;gt;
 *                   &amp;lt;/element&amp;gt;
 *                 &amp;lt;/sequence&amp;gt;
 *               &amp;lt;/restriction&amp;gt;
 *             &amp;lt;/complexContent&amp;gt;
 *           &amp;lt;/complexType&amp;gt;
 *         &amp;lt;/element&amp;gt;
 *         &amp;lt;element name="resenja" type="{http://www.projekat.org/resenje}T_Multi_Paragraf"/&amp;gt;
 *         &amp;lt;element name="obrazlozenje"&amp;gt;
 *           &amp;lt;complexType&amp;gt;
 *             &amp;lt;complexContent&amp;gt;
 *               &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *                 &amp;lt;sequence&amp;gt;
 *                   &amp;lt;element name="opis" type="{http://www.projekat.org/resenje}T_Multi_Paragraf"/&amp;gt;
 *                   &amp;lt;element name="razlog" type="{http://www.projekat.org/resenje}T_Multi_Paragraf"/&amp;gt;
 *                   &amp;lt;element name="kona\u010dno_resenje" type="{http://www.projekat.org/resenje}T_Multi_Paragraf"/&amp;gt;
 *                 &amp;lt;/sequence&amp;gt;
 *               &amp;lt;/restriction&amp;gt;
 *             &amp;lt;/complexContent&amp;gt;
 *           &amp;lt;/complexType&amp;gt;
 *         &amp;lt;/element&amp;gt;
 *         &amp;lt;element name="uputstvo" type="{http://www.w3.org/2001/XMLSchema}string"/&amp;gt;
 *         &amp;lt;element name="datum_resenja" type="{http://www.w3.org/2001/XMLSchema}date"/&amp;gt;
 *         &amp;lt;element name="poverenik" type="{http://www.projekat.org/common}TFizicko_lice"/&amp;gt;
 *       &amp;lt;/sequence&amp;gt;
 *       &amp;lt;attribute name="broj_resenja" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&amp;gt;
 *       &amp;lt;attribute name="broj_Zalbe" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&amp;gt;
 *       &amp;lt;attribute name="broj_zahteva" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&amp;gt;
 *       &amp;lt;attribute name="tip_resenja" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&amp;gt;
 *     &amp;lt;/restriction&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "opis\u017dalbe",
    "re\u0161enja",
    "obrazlo\u017eenje",
    "uputstvo",
    "datumRe\u0161enja",
    "poverenik"
})
@XmlRootElement(name = "odluka_poverioca", namespace = "http://www.projekat.org/resenje")
public class OdlukaPoverioca {

    @XmlElement(name = "opis_\u017ealbe", namespace = "http://www.projekat.org/resenje", required = true)
    protected OdlukaPoverioca.OpisZalbe opisZalbe;
    @XmlElement(namespace = "http://www.projekat.org/resenje", required = true)
    protected TMultiParagraf resenja;
    @XmlElement(namespace = "http://www.projekat.org/resenje", required = true)
    protected OdlukaPoverioca.Obrazlozenje obrazlozenje;
    @XmlElement(namespace = "http://www.projekat.org/resenje", required = true)
    protected String uputstvo;
    @XmlElement(name = "datum_re\u0161enja", namespace = "http://www.projekat.org/resenje", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumResenja;
    @XmlElement(namespace = "http://www.projekat.org/resenje", required = true)
    protected TFizickoLice poverenik;
    @XmlAttribute(name = "broj_re\u0161enja")
    @XmlSchemaType(name = "anySimpleType")
    protected String brojResenja;
    @XmlAttribute(name = "broj_\u017ealbe")
    @XmlSchemaType(name = "anySimpleType")
    protected String brojZalbe;
    @XmlAttribute(name = "broj_zahteva")
    @XmlSchemaType(name = "anySimpleType")
    protected String brojZahteva;
    @XmlAttribute(name = "tip_re\u0161enja")
    @XmlSchemaType(name = "anySimpleType")
    protected String tipResenja;

    /**
     * Gets the value of the opisZalbe property.
     * 
     * @return
     *     possible object is
     *     {@link OdlukaPoverioca.OpisZalbe }
     *     
     */
    public OdlukaPoverioca.OpisZalbe getOpisZalbe() {
        return opisZalbe;
    }

    /**
     * Sets the value of the opisZalbe property.
     * 
     * @param value
     *     allowed object is
     *     {@link OdlukaPoverioca.OpisZalbe }
     *     
     */
    public void setOpisZalbe(OdlukaPoverioca.OpisZalbe value) {
        this.opisZalbe = value;
    }

    /**
     * Gets the value of the resenja property.
     * 
     * @return
     *     possible object is
     *     {@link TMultiParagraf }
     *     
     */
    public TMultiParagraf getResenja() {
        return resenja;
    }

    /**
     * Sets the value of the resenja property.
     * 
     * @param value
     *     allowed object is
     *     {@link TMultiParagraf }
     *     
     */
    public void setResenja(TMultiParagraf value) {
        this.resenja = value;
    }

    /**
     * Gets the value of the obrazlozenje property.
     * 
     * @return
     *     possible object is
     *     {@link OdlukaPoverioca.Obrazlozenje }
     *     
     */
    public OdlukaPoverioca.Obrazlozenje getObrazlozenje() {
        return obrazlozenje;
    }

    /**
     * Sets the value of the obrazlozenje property.
     * 
     * @param value
     *     allowed object is
     *     {@link OdlukaPoverioca.Obrazlozenje }
     *     
     */
    public void setObrazlozenje(OdlukaPoverioca.Obrazlozenje value) {
        this.obrazlozenje = value;
    }

    /**
     * Gets the value of the uputstvo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUputstvo() {
        return uputstvo;
    }

    /**
     * Sets the value of the uputstvo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUputstvo(String value) {
        this.uputstvo = value;
    }

    /**
     * Gets the value of the datumResenja property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumResenja() {
        return datumResenja;
    }

    /**
     * Sets the value of the datumResenja property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumResenja(XMLGregorianCalendar value) {
        this.datumResenja = value;
    }

    /**
     * Gets the value of the poverenik property.
     * 
     * @return
     *     possible object is
     *     {@link TFizickoLice }
     *     
     */
    public TFizickoLice getPoverenik() {
        return poverenik;
    }

    /**
     * Sets the value of the poverenik property.
     * 
     * @param value
     *     allowed object is
     *     {@link TFizickoLice }
     *     
     */
    public void setPoverenik(TFizickoLice value) {
        this.poverenik = value;
    }

    /**
     * Gets the value of the brojResenja property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrojResenja() {
        return brojResenja;
    }

    /**
     * Sets the value of the brojResenja property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrojResenja(String value) {
        this.brojResenja = value;
    }

    /**
     * Gets the value of the brojZalbe property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrojZalbe() {
        return brojZalbe;
    }

    /**
     * Sets the value of the brojZalbe property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrojZalbe(String value) {
        this.brojZalbe = value;
    }

    /**
     * Gets the value of the brojZahteva property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrojZahteva() {
        return brojZahteva;
    }

    /**
     * Sets the value of the brojZahteva property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrojZahteva(String value) {
        this.brojZahteva = value;
    }

    /**
     * Gets the value of the tipResenja property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipResenja() {
        return tipResenja;
    }

    /**
     * Sets the value of the tipResenja property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipResenja(String value) {
        this.tipResenja = value;
    }


    /**
     * &lt;p&gt;Java class for anonymous complex type.
     * 
     * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
     * 
     * &lt;pre&gt;
     * &amp;lt;complexType&amp;gt;
     *   &amp;lt;complexContent&amp;gt;
     *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
     *       &amp;lt;sequence&amp;gt;
     *         &amp;lt;element name="opis" type="{http://www.projekat.org/resenje}T_Multi_Paragraf"/&amp;gt;
     *         &amp;lt;element name="razlog" type="{http://www.projekat.org/resenje}T_Multi_Paragraf"/&amp;gt;
     *         &amp;lt;element name="kona\u010dno_resenje" type="{http://www.projekat.org/resenje}T_Multi_Paragraf"/&amp;gt;
     *       &amp;lt;/sequence&amp;gt;
     *     &amp;lt;/restriction&amp;gt;
     *   &amp;lt;/complexContent&amp;gt;
     * &amp;lt;/complexType&amp;gt;
     * &lt;/pre&gt;
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "opis",
        "razlog",
        "kona\u010dnoRe\u0161enje"
    })
    public static class Obrazlozenje {

        @XmlElement(namespace = "http://www.projekat.org/resenje", required = true)
        protected TMultiParagraf opis;
        @XmlElement(namespace = "http://www.projekat.org/resenje", required = true)
        protected TMultiParagraf razlog;
        @XmlElement(name = "kona\u010dno_re\u0161enje", namespace = "http://www.projekat.org/resenje", required = true)
        protected TMultiParagraf kona\u010dnoResenje;

        /**
         * Gets the value of the opis property.
         * 
         * @return
         *     possible object is
         *     {@link TMultiParagraf }
         *     
         */
        public TMultiParagraf getOpis() {
            return opis;
        }

        /**
         * Sets the value of the opis property.
         * 
         * @param value
         *     allowed object is
         *     {@link TMultiParagraf }
         *     
         */
        public void setOpis(TMultiParagraf value) {
            this.opis = value;
        }

        /**
         * Gets the value of the razlog property.
         * 
         * @return
         *     possible object is
         *     {@link TMultiParagraf }
         *     
         */
        public TMultiParagraf getRazlog() {
            return razlog;
        }

        /**
         * Sets the value of the razlog property.
         * 
         * @param value
         *     allowed object is
         *     {@link TMultiParagraf }
         *     
         */
        public void setRazlog(TMultiParagraf value) {
            this.razlog = value;
        }

        /**
         * Gets the value of the kona\u010dnoResenje property.
         * 
         * @return
         *     possible object is
         *     {@link TMultiParagraf }
         *     
         */
        public TMultiParagraf getKona\u010dnoResenje() {
            return kona\u010dnoResenje;
        }

        /**
         * Sets the value of the kona\u010dnoResenje property.
         * 
         * @param value
         *     allowed object is
         *     {@link TMultiParagraf }
         *     
         */
        public void setKona\u010dnoResenje(TMultiParagraf value) {
            this.kona\u010dnoResenje = value;
        }

    }


    /**
     * &lt;p&gt;Java class for anonymous complex type.
     * 
     * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
     * 
     * &lt;pre&gt;
     * &amp;lt;complexType&amp;gt;
     *   &amp;lt;complexContent&amp;gt;
     *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
     *       &amp;lt;sequence&amp;gt;
     *         &amp;lt;element name="Zalioc" type="{http://www.projekat.org/common}TFizicko_lice"/&amp;gt;
     *         &amp;lt;element name="organ"&amp;gt;
     *           &amp;lt;complexType&amp;gt;
     *             &amp;lt;complexContent&amp;gt;
     *               &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
     *                 &amp;lt;sequence&amp;gt;
     *                   &amp;lt;element name="naziv"&amp;gt;
     *                     &amp;lt;simpleType&amp;gt;
     *                       &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt;
     *                         &amp;lt;minLength value="1"/&amp;gt;
     *                       &amp;lt;/restriction&amp;gt;
     *                     &amp;lt;/simpleType&amp;gt;
     *                   &amp;lt;/element&amp;gt;
     *                   &amp;lt;element name="adresa" type="{http://www.projekat.org/common}TAdresa"/&amp;gt;
     *                 &amp;lt;/sequence&amp;gt;
     *               &amp;lt;/restriction&amp;gt;
     *             &amp;lt;/complexContent&amp;gt;
     *           &amp;lt;/complexType&amp;gt;
     *         &amp;lt;/element&amp;gt;
     *         &amp;lt;element name="datum_Zalbe" type="{http://www.w3.org/2001/XMLSchema}date"/&amp;gt;
     *         &amp;lt;element name="ceo_opis"&amp;gt;
     *           &amp;lt;simpleType&amp;gt;
     *             &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt;
     *               &amp;lt;minLength value="1"/&amp;gt;
     *             &amp;lt;/restriction&amp;gt;
     *           &amp;lt;/simpleType&amp;gt;
     *         &amp;lt;/element&amp;gt;
     *       &amp;lt;/sequence&amp;gt;
     *     &amp;lt;/restriction&amp;gt;
     *   &amp;lt;/complexContent&amp;gt;
     * &amp;lt;/complexType&amp;gt;
     * &lt;/pre&gt;
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "\u017ealioc",
        "organ",
        "datum\u017dalbe",
        "ceoOpis"
    })
    public static class OpisZalbe {

        @XmlElement(namespace = "http://www.projekat.org/resenje", required = true)
        protected TFizickoLice Zalioc;
        @XmlElement(namespace = "http://www.projekat.org/resenje", required = true)
        protected OdlukaPoverioca.OpisZalbe.Organ organ;
        @XmlElement(name = "datum_\u017ealbe", namespace = "http://www.projekat.org/resenje", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar datumZalbe;
        @XmlElement(name = "ceo_opis", namespace = "http://www.projekat.org/resenje", required = true)
        protected String ceoOpis;

        /**
         * Gets the value of the Zalioc property.
         * 
         * @return
         *     possible object is
         *     {@link TFizickoLice }
         *     
         */
        public TFizickoLice getZalioc() {
            return Zalioc;
        }

        /**
         * Sets the value of the Zalioc property.
         * 
         * @param value
         *     allowed object is
         *     {@link TFizickoLice }
         *     
         */
        public void setZalioc(TFizickoLice value) {
            this.Zalioc = value;
        }

        /**
         * Gets the value of the organ property.
         * 
         * @return
         *     possible object is
         *     {@link OdlukaPoverioca.OpisZalbe.Organ }
         *     
         */
        public OdlukaPoverioca.OpisZalbe.Organ getOrgan() {
            return organ;
        }

        /**
         * Sets the value of the organ property.
         * 
         * @param value
         *     allowed object is
         *     {@link OdlukaPoverioca.OpisZalbe.Organ }
         *     
         */
        public void setOrgan(OdlukaPoverioca.OpisZalbe.Organ value) {
            this.organ = value;
        }

        /**
         * Gets the value of the datumZalbe property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDatumZalbe() {
            return datumZalbe;
        }

        /**
         * Sets the value of the datumZalbe property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDatumZalbe(XMLGregorianCalendar value) {
            this.datumZalbe = value;
        }

        /**
         * Gets the value of the ceoOpis property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCeoOpis() {
            return ceoOpis;
        }

        /**
         * Sets the value of the ceoOpis property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCeoOpis(String value) {
            this.ceoOpis = value;
        }


        /**
         * &lt;p&gt;Java class for anonymous complex type.
         * 
         * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
         * 
         * &lt;pre&gt;
         * &amp;lt;complexType&amp;gt;
         *   &amp;lt;complexContent&amp;gt;
         *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
         *       &amp;lt;sequence&amp;gt;
         *         &amp;lt;element name="naziv"&amp;gt;
         *           &amp;lt;simpleType&amp;gt;
         *             &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt;
         *               &amp;lt;minLength value="1"/&amp;gt;
         *             &amp;lt;/restriction&amp;gt;
         *           &amp;lt;/simpleType&amp;gt;
         *         &amp;lt;/element&amp;gt;
         *         &amp;lt;element name="adresa" type="{http://www.projekat.org/common}TAdresa"/&amp;gt;
         *       &amp;lt;/sequence&amp;gt;
         *     &amp;lt;/restriction&amp;gt;
         *   &amp;lt;/complexContent&amp;gt;
         * &amp;lt;/complexType&amp;gt;
         * &lt;/pre&gt;
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "naziv",
            "adresa"
        })
        public static class Organ {

            @XmlElement(namespace = "http://www.projekat.org/resenje", required = true)
            protected String naziv;
            @XmlElement(namespace = "http://www.projekat.org/resenje", required = true)
            protected TAdresa adresa;

            /**
             * Gets the value of the naziv property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNaziv() {
                return naziv;
            }

            /**
             * Sets the value of the naziv property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNaziv(String value) {
                this.naziv = value;
            }

            /**
             * Gets the value of the adresa property.
             * 
             * @return
             *     possible object is
             *     {@link TAdresa }
             *     
             */
            public TAdresa getAdresa() {
                return adresa;
            }

            /**
             * Sets the value of the adresa property.
             * 
             * @param value
             *     allowed object is
             *     {@link TAdresa }
             *     
             */
            public void setAdresa(TAdresa value) {
                this.adresa = value;
            }

        }

    }

}
