//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.03 at 11:08:50 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.projekat.org/izvestaj", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED, xmlns={@javax.xml.bind.annotation.XmlNs(prefix="iz", namespaceURI="http://www.projekat.org/izvestaj"), @javax.xml.bind.annotation.XmlNs(prefix="pred", namespaceURI="http://www.projekat.org/predicate/"), @javax.xml.bind.annotation.XmlNs(prefix="xs", namespaceURI="http://www.w3.org/2001/XMLSchema#"),})
package projectXML.team9.models.izvestaj;
