//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.06 at 02:59:25 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.projekat.org/zalba_cutanja", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package projectXML.team9.models.zalbaCutanje;
