//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.06 at 02:59:25 PM CET 
//

package projectXML.team9.models.zalbaCutanje;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonSubTypes.Type;
import com.fasterxml.jackson.annotation.JsonTypeInfo;

import lombok.NoArgsConstructor;

/**
 * &lt;p&gt;Java class for TLice complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content
 * contained within this class.
 * 
 * &lt;pre&gt; &amp;lt;complexType name="TLice"&amp;gt;
 * &amp;lt;complexContent&amp;gt; &amp;lt;restriction
 * base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 * &amp;lt;sequence&amp;gt; &amp;lt;element name="adresa"
 * type="{http://www.projekat.org/zalba_cutanja}TAdresa"/&amp;gt;
 * &amp;lt;/sequence&amp;gt; &amp;lt;/restriction&amp;gt;
 * &amp;lt;/complexContent&amp;gt; &amp;lt;/complexType&amp;gt; &lt;/pre&gt;
 * 
 * 
 */
@NoArgsConstructor
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TLice", propOrder = { "adresa" })
@XmlSeeAlso({ TPravnoLice.class, TFizickoLice.class })
@JsonTypeInfo(
	  use = JsonTypeInfo.Id.NAME, 
	  include = JsonTypeInfo.As.PROPERTY, 
	  property = "type")
	@JsonSubTypes({ 
	  @Type(value = TFizickoLice.class, name = "fizicko_lice"), 
	  @Type(value = TPravnoLice.class, name = "pravno_lice") 
	})
public abstract class TLice {
	
	public TLice(TAdresa a) {
		this.adresa = a;
	}

	@XmlElement(required = true)
	protected TAdresa adresa;

	/**
	 * Gets the value of the adresa property.
	 * 
	 * @return possible object is {@link TAdresa }
	 * 
	 */
	public TAdresa getAdresa() {
		return adresa;
	}

	/**
	 * Sets the value of the adresa property.
	 * 
	 * @param value allowed object is {@link TAdresa }
	 * 
	 */
	public void setAdresa(TAdresa value) {
		this.adresa = value;
	}

	@Override
	public String toString() {
		return "Adresa:\n" + adresa.toString();
	}

}
