//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.10 at 07:48:35 PM CET 
//


package projectXML.team10.poverenik.models.resenje;

import javax.xml.bind.annotation.XmlRegistry;

import projectXML.team10.poverenik.models.common.TAdresa;
import projectXML.team10.poverenik.models.common.TFizickoLice;
import projectXML.team10.poverenik.models.common.TPravnoLice;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the projectXML.team10.poverenik.models.resenje package. 
 * &lt;p&gt;An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: projectXML.team10.poverenik.models.resenje
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OdlukaPoverioca }
     * 
     */
    public OdlukaPoverioca createOdlukaPoverioca() {
        return new OdlukaPoverioca();
    }

    /**
     * Create an instance of {@link OdlukaPoverioca.OpisZalbe }
     * 
     */
    public OdlukaPoverioca.OpisZalbe createOdlukaPoveriocaOpisZalbe() {
        return new OdlukaPoverioca.OpisZalbe();
    }

    /**
     * Create an instance of {@link TMultiParagraf }
     * 
     */
    public TMultiParagraf createTMultiParagraf() {
        return new TMultiParagraf();
    }

    /**
     * Create an instance of {@link OdlukaPoverioca.Obrazlo�enje }
     * 
     */
    public OdlukaPoverioca.Obrazlozenje createOdlukaPoveriocaObrazlozenje() {
        return new OdlukaPoverioca.Obrazlozenje();
    }

    /**
     * Create an instance of {@link TFizickoLice }
     * 
     */
    public TFizickoLice createTFizickoLice() {
        return new TFizickoLice();
    }

    /**
     * Create an instance of {@link TAdresa }
     * 
     */
    public TAdresa createTAdresa() {
        return new TAdresa();
    }

    /**
     * Create an instance of {@link TPravnoLice }
     * 
     */
    public TPravnoLice createTPravnoLice() {
        return new TPravnoLice();
    }

    /**
     * Create an instance of {@link OdlukaPoverioca.Opis�albe.Organ }
     * 
     */
    public OdlukaPoverioca.OpisZalbe.Organ createOdlukaPoveriocaOpisZalbeOrgan() {
        return new OdlukaPoverioca.OpisZalbe.Organ();
    }

}
